//! Instance events for other types.
//!
//! Auto-generated by codegen. Do not edit manually.

mod my_inventory;
mod my_procedural_logical_sector;
mod my_property_sync_state_group;

pub use my_inventory::*;
pub use my_procedural_logical_sector::*;
pub use my_property_sync_state_group::*;
