//! Static event payloads declared in Sandbox.Game.Gui.MyGuiScreenDebugSystem.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for HavokMemoryStatsReply event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct HavokMemoryStatsReplyPayload {
    pub stats: VarString,
}

