//! Static event payloads declared in Sandbox.Game.Entities.MyFloatingObjects.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for RequestSpawnCreative_Implementation event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RequestSpawnCreative_ImplementationPayload {
    pub obj: space_engineers_sys::types::MyObjectBuilder_FloatingObject,
}

