//! Static event payloads declared in Sandbox.Game.Screens.DebugScreens.MyGuiScreenDebugAi.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for AddAnimal event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddAnimalPayload {
    pub sub_type_name: VarString,
}

/// Payload for AddHumanoid event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddHumanoidPayload {
    pub sub_type_name: VarString,
}

