//! Static event payloads declared in Sandbox.Game.Screens.DebugScreens.MyGuiScreenDebugTravel.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for HeatmapTeleportClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct HeatmapTeleportClientPayload {
    pub heat_point: Vector3D,
    pub heat: BitAligned<f32>,
}

