//! Static event payloads declared in Sandbox.Engine.Physics.MyPhysics.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for SetScheduling event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SetSchedulingPayload {
    pub multithread: BitBool,
    pub parallel: BitBool,
}

/// Payload for OnClustersReordered event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct OnClustersReorderedPayload {
    pub list: VarVec<space_engineers_sys::math::BoundingBoxD>,
}

/// Payload for UpdateServerDebugCamera event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UpdateServerDebugCameraPayload {
    pub wm: space_engineers_sys::math::MatrixD,
}

/// Payload for ControlVDBRecording event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ControlVDBRecordingPayload {
    pub file_name: VarString,
}

