//! Static event payloads declared in Sandbox.Game.SessionComponents.MySectorWeatherComponent.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for RequestLightningServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RequestLightningServerPayload {
    pub camera_translation: Vector3D,
    pub hit_position: Vector3D,
}

/// Payload for UpdateWeathersOnClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UpdateWeathersOnClientsPayload {
    pub planet_data: VarVec<space_engineers_sys::types::MyObjectBuilder_WeatherPlanetData>,
}

/// Payload for UpdateLightningsOnClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UpdateLightningsOnClientsPayload {
    pub lightnings: VarVec<space_engineers_sys::types::MyObjectBuilder_WeatherLightning>,
}

/// Payload for UpdateWeathersOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UpdateWeathersOnClientPayload {
    pub planet_data: VarVec<space_engineers_sys::types::MyObjectBuilder_WeatherPlanetData>,
}

