//! Static event payloads declared in Sandbox.Game.SessionComponents.MySessionComponentTrash.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for RevertForageableItem event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RevertForageableItemPayload {
    pub item: space_engineers_sys::types::MySessionComponentTrash_ForageableItemInfo,
}

/// Payload for SetPlayerAFKTimeout_Server event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SetPlayerAFKTimeout_ServerPayload {
    pub min: BitAligned<i32>,
}

/// Payload for SetPlayerAFKTimeout_Broadcast event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SetPlayerAFKTimeout_BroadcastPayload {
    pub min: BitAligned<i32>,
}

