//! Static event payloads declared in Sandbox.Game.GameSystems.Trading.MyTradingManager.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for TradeRequest_Server event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct TradeRequest_ServerPayload {
    pub requested_id: BitAligned<u64>,
}

/// Payload for TradeRequest_StartTrade event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct TradeRequest_StartTradePayload {
    pub requesting_id: BitAligned<u64>,
}

/// Payload for TradeRequest_StartTrade_Server event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct TradeRequest_StartTrade_ServerPayload {
    pub reason: space_engineers_sys::types::MyTradeResponseReason,
}

/// Payload for TradeRequest_Response event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct TradeRequest_ResponsePayload {
    pub other_player_id: BitAligned<u64>,
    pub reason: space_engineers_sys::types::MyTradeResponseReason,
}

/// Payload for SubmitTradingOffer_Server event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SubmitTradingOffer_ServerPayload {
    pub ob_offer: space_engineers_sys::types::MyObjectBuilder_SubmitOffer,
}

/// Payload for SubmitTradingOffer_ClientRecieve event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SubmitTradingOffer_ClientRecievePayload {
    pub ob_offer: space_engineers_sys::types::MyObjectBuilder_SubmitOffer,
}

/// Payload for AcceptOffer_Server event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AcceptOffer_ServerPayload {
    pub is_accepted: BitBool,
}

/// Payload for AcceptOffer_ClientRecieve event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AcceptOffer_ClientRecievePayload {
    pub is_accepted: BitBool,
}

