//! Static event payloads declared in Sandbox.Game.EntityComponents.MyTurretController.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for RequestUseMessageStatic event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RequestUseMessageStaticPayload {
    pub use_action: space_engineers_compat::BitField<space_engineers_sys::types::UseActionEnum>,
    pub used_by_id: BitAligned<i64>,
    pub entity_id: BitAligned<i64>,
}

/// Payload for UseSuccessStatic event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UseSuccessStaticPayload {
    pub use_action: space_engineers_compat::BitField<space_engineers_sys::types::UseActionEnum>,
    pub used_by_id: BitAligned<i64>,
    pub use_result: space_engineers_sys::types::UseActionResult,
    pub entity_id: BitAligned<i64>,
}

/// Payload for UseFailureStatic event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct UseFailureStaticPayload {
    pub use_action: space_engineers_compat::BitField<space_engineers_sys::types::UseActionEnum>,
    pub used_by_id: BitAligned<i64>,
    pub use_result: space_engineers_sys::types::UseActionResult,
    pub entity_id: BitAligned<i64>,
}

