//! Static event payloads declared in Sandbox.Game.Multiplayer.MyFactionCollection.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for CreateFactionByDefinition event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct CreateFactionByDefinitionPayload {
    pub tag: VarString,
}

/// Payload for MyFactionCollection_UnlockAchievementForClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyFactionCollection_UnlockAchievementForClientPayload {
    pub achievement: VarString,
}

/// Payload for Invoke_AddRep_DEBUG event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct Invoke_AddRep_DEBUGPayload {
    pub player_id: BitAligned<i64>,
    pub faction_id: BitAligned<i64>,
    pub delta: BitAligned<i32>,
}

/// Payload for AddFactionPlayerReputationSuccess event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddFactionPlayerReputationSuccessPayload {
    pub player_id: BitAligned<i64>,
    pub changes: VarVec<space_engineers_sys::types::MyFactionCollection_MyReputationChangeWrapper>,
    pub reason: space_engineers_sys::types::ReputationChangeReason,
}

/// Payload for FactionStateChangeRequest event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct FactionStateChangeRequestPayload {
    pub action: space_engineers_sys::types::MyFactionStateChange,
    pub from_faction_id: BitAligned<i64>,
    pub to_faction_id: BitAligned<i64>,
    pub player_id: BitAligned<i64>,
}

/// Payload for FactionStateChangeSuccess event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct FactionStateChangeSuccessPayload {
    pub action: space_engineers_sys::types::MyFactionStateChange,
    pub from_faction_id: BitAligned<i64>,
    pub to_faction_id: BitAligned<i64>,
    pub player_id: BitAligned<i64>,
    pub sender_id: BitAligned<i64>,
}

/// Payload for ChangeAutoAcceptRequest event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeAutoAcceptRequestPayload {
    pub faction_id: BitAligned<i64>,
    pub auto_accept_member: BitBool,
    pub auto_accept_peace: BitBool,
}

/// Payload for ChangeAutoAcceptSuccess event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeAutoAcceptSuccessPayload {
    pub faction_id: BitAligned<i64>,
    pub auto_accept_member: BitBool,
    pub auto_accept_peace: BitBool,
}

/// Payload for EditFactionRequest event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct EditFactionRequestPayload {
    pub msg_edit: space_engineers_sys::types::MyFactionCollection_AddFactionMsg,
}

/// Payload for EditFactionSuccess_AcceptHumans event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct EditFactionSuccess_AcceptHumansPayload {
    pub faction_id: BitAligned<i64>,
    pub accept_humans: BitBool,
}

/// Payload for EditFactionSuccess event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct EditFactionSuccessPayload {
    pub msg_edit: space_engineers_sys::types::MyFactionCollection_AddFactionMsg,
    pub sender_id: BitAligned<i64>,
}

/// Payload for RequestFactionScoreAndPercentageUpdate event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RequestFactionScoreAndPercentageUpdatePayload {
    pub faction_id: BitAligned<i64>,
}

/// Payload for RecieveFactionScoreAndPercentage event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RecieveFactionScoreAndPercentagePayload {
    pub faction_id: BitAligned<i64>,
    pub score: BitAligned<i32>,
    pub percentage_finished: BitAligned<f32>,
}

/// Payload for CreateFactionRequest event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct CreateFactionRequestPayload {
    pub msg: space_engineers_sys::types::MyFactionCollection_AddFactionMsg,
}

/// Payload for CreateFactionSuccess event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct CreateFactionSuccessPayload {
    pub msg: space_engineers_sys::types::MyFactionCollection_AddFactionMsg,
}

/// Payload for SetDefaultFactionStates event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct SetDefaultFactionStatesPayload {
    pub recived_faction_id: BitAligned<i64>,
}

/// Payload for AddDiscoveredFaction_Clients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddDiscoveredFaction_ClientsPayload {
    pub player_id: BitAligned<u64>,
    pub serial_id: BitAligned<i32>,
    pub faction_id: BitAligned<i64>,
}

/// Payload for RemoveDiscoveredFaction_Clients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RemoveDiscoveredFaction_ClientsPayload {
    pub player_id: BitAligned<u64>,
    pub serial_id: BitAligned<i32>,
    pub faction_id: BitAligned<i64>,
}

/// Payload for RemovePlayerFromVisibility_Broadcast event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct RemovePlayerFromVisibility_BroadcastPayload {
    pub player_id: space_engineers_sys::types::MyPlayer_PlayerId,
}

