//! Static event payloads declared in Sandbox.Game.Multiplayer.MyGpsCollection.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for AddGpsOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddGpsOnClientPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_AddMsg,
}

/// Payload for AddGpsOnAllClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddGpsOnAllClientsPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_AddMsg,
}

/// Payload for AddGpsOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct AddGpsOnServerPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_AddMsg,
}

/// Payload for DeleteGpsOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct DeleteGpsOnClientPayload {
    pub gps_hash: BitAligned<i32>,
}

/// Payload for DeleteGpsOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct DeleteGpsOnServerPayload {
    pub gps_hash: BitAligned<i32>,
}

/// Payload for DeleteContainerGpsOnAllClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct DeleteContainerGpsOnAllClientsPayload {
    pub entity_id: BitAligned<i64>,
}

/// Payload for DeleteContainerGpsOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct DeleteContainerGpsOnClientPayload {
    pub entity_id: BitAligned<i64>,
}

/// Payload for ModifyGpsOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ModifyGpsOnServerPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_ModifyMsg,
}

/// Payload for ModifyGpsOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ModifyGpsOnClientPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_ModifyMsg,
}

/// Payload for ModifyGpsOnAllClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ModifyGpsOnAllClientsPayload {
    pub msg: space_engineers_sys::types::MyGpsCollection_ModifyMsg,
}

/// Payload for ChangeShowOnHudOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeShowOnHudOnServerPayload {
    pub gps_hash: BitAligned<i32>,
    pub show: BitBool,
}

/// Payload for ChangeShowOnHudOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeShowOnHudOnClientPayload {
    pub gps_hash: BitAligned<i32>,
    pub show: BitBool,
}

/// Payload for ChangeContainerPositionOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeContainerPositionOnClientPayload {
    pub grid_entity_id: BitAligned<i64>,
    pub grid_position: Vector3D,
}

/// Payload for ChangeContainerPositionOnAllClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeContainerPositionOnAllClientsPayload {
    pub grid_entity_id: BitAligned<i64>,
    pub grid_position: Vector3D,
}

/// Payload for ChangeAlwaysVisibleOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeAlwaysVisibleOnServerPayload {
    pub gps_hash: BitAligned<i32>,
    pub always_visible: BitBool,
}

/// Payload for ChangeAlwaysVisibleOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeAlwaysVisibleOnClientPayload {
    pub gps_hash: BitAligned<i32>,
    pub always_visible: BitBool,
}

/// Payload for ChangeColorOnClient event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeColorOnClientPayload {
    pub gps_hash: BitAligned<i32>,
    pub color: space_engineers_sys::types::Color,
}

/// Payload for ChangeColorOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeColorOnServerPayload {
    pub gps_hash: BitAligned<i32>,
    pub color: space_engineers_sys::types::Color,
}

/// Payload for ChangeContainerColorOnAllClients event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeContainerColorOnAllClientsPayload {
    pub entity_id: BitAligned<i64>,
    pub color: space_engineers_sys::types::Color,
}

/// Payload for ChangeContainerColorOnServer event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct ChangeContainerColorOnServerPayload {
    pub grid_entity_id: BitAligned<i64>,
    pub color: space_engineers_sys::types::Color,
}

