//! Static event payloads declared in Sandbox.Engine.Multiplayer.MyMultiplayer.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for OnTeleport event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct OnTeleportPayload {
    pub user_id: BitAligned<u64>,
    pub location: Vector3D,
}

