//! Instance events for SpaceEngineers.Game.EntityComponents.Blocks.MyBasicMissionAutopilot.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyBasicMissionAutopilot::OnPasteAutopilotSetupStatic instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_OnPasteAutopilotSetupStaticPayload {
    pub clipboard: space_engineers_sys::types::MyObjectBuilder_AutopilotClipboard,
}

/// Payload for MyBasicMissionAutopilot::RemoveWaypoints instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_RemoveWaypointsPayload {
    pub indexes: VarVec<BitAligned<i32>>,
}

/// Payload for MyBasicMissionAutopilot::MoveWaypointsIndex instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_MoveWaypointsIndexPayload {
    pub up: BitBool,
    pub indexes: VarVec<BitAligned<i32>>,
}

/// Payload for MyBasicMissionAutopilot::ChangeActions instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_ChangeActionsPayload {
    pub waypoint_index: BitAligned<i32>,
    pub actions: VarVec<space_engineers_sys::types::ToolbarItem>,
}

/// Payload for MyBasicMissionAutopilot::AddWaypoints instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_AddWaypointsPayload {
    pub positions: VarVec<Vector3D>,
    pub names: VarVec<VarString>,
}

/// Payload for MyBasicMissionAutopilot::AddWaypointBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyBasicMissionAutopilot_AddWaypointBroadcastPayload {
    pub matrix: space_engineers_sys::math::MatrixD,
    pub related_entity_id: BitAligned<i64>,
    pub name: VarString,
}

/// Stable instance event identities for SpaceEngineers.Game.EntityComponents.Blocks.MyBasicMissionAutopilot.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyBasicMissionAutopilotInstanceEvent {
    /// Hash: -333179875
    OnPasteAutopilotSetupStatic,
    /// Hash: 713296825
    OnResetWaypoint,
    /// Hash: -1046010110
    RemoveWaypoints,
    /// Hash: 771352631
    MoveWaypointsIndex,
    /// Hash: -1374070667
    ChangeActions,
    /// Hash: 1677816635
    AddWaypoints,
    /// Hash: -2001178050
    AddWaypointBroadcast,
}

impl MyBasicMissionAutopilotInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::OnPasteAutopilotSetupStatic => -333179875,
            Self::OnResetWaypoint => 713296825,
            Self::RemoveWaypoints => -1046010110,
            Self::MoveWaypointsIndex => 771352631,
            Self::ChangeActions => -1374070667,
            Self::AddWaypoints => 1677816635,
            Self::AddWaypointBroadcast => -2001178050,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -333179875 => Some(Self::OnPasteAutopilotSetupStatic),
            713296825 => Some(Self::OnResetWaypoint),
            -1046010110 => Some(Self::RemoveWaypoints),
            771352631 => Some(Self::MoveWaypointsIndex),
            -1374070667 => Some(Self::ChangeActions),
            1677816635 => Some(Self::AddWaypoints),
            -2001178050 => Some(Self::AddWaypointBroadcast),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.EntityComponents.Blocks.MyBasicMissionAutopilot.
///
/// Use `MyBasicMissionAutopilotInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyBasicMissionAutopilotInstanceEventPayload {
    /// OnPasteAutopilotSetupStatic event payload
    OnPasteAutopilotSetupStatic(MyBasicMissionAutopilot_OnPasteAutopilotSetupStaticPayload),
    /// OnResetWaypoint event (no payload)
    OnResetWaypoint,
    /// RemoveWaypoints event payload
    RemoveWaypoints(MyBasicMissionAutopilot_RemoveWaypointsPayload),
    /// MoveWaypointsIndex event payload
    MoveWaypointsIndex(MyBasicMissionAutopilot_MoveWaypointsIndexPayload),
    /// ChangeActions event payload
    ChangeActions(MyBasicMissionAutopilot_ChangeActionsPayload),
    /// AddWaypoints event payload
    AddWaypoints(MyBasicMissionAutopilot_AddWaypointsPayload),
    /// AddWaypointBroadcast event payload
    AddWaypointBroadcast(MyBasicMissionAutopilot_AddWaypointBroadcastPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyBasicMissionAutopilotInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyBasicMissionAutopilotInstanceEventPayload, deku::DekuError> {
        match self {
            Self::OnPasteAutopilotSetupStatic => {
                let (_, payload) = MyBasicMissionAutopilot_OnPasteAutopilotSetupStaticPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::OnPasteAutopilotSetupStatic(payload))
            }
            Self::OnResetWaypoint => Ok(MyBasicMissionAutopilotInstanceEventPayload::OnResetWaypoint),
            Self::RemoveWaypoints => {
                let (_, payload) = MyBasicMissionAutopilot_RemoveWaypointsPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::RemoveWaypoints(payload))
            }
            Self::MoveWaypointsIndex => {
                let (_, payload) = MyBasicMissionAutopilot_MoveWaypointsIndexPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::MoveWaypointsIndex(payload))
            }
            Self::ChangeActions => {
                let (_, payload) = MyBasicMissionAutopilot_ChangeActionsPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::ChangeActions(payload))
            }
            Self::AddWaypoints => {
                let (_, payload) = MyBasicMissionAutopilot_AddWaypointsPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::AddWaypoints(payload))
            }
            Self::AddWaypointBroadcast => {
                let (_, payload) = MyBasicMissionAutopilot_AddWaypointBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyBasicMissionAutopilotInstanceEventPayload::AddWaypointBroadcast(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyBasicMissionAutopilot from raw event hash and bytes.
pub fn parse_my_basic_mission_autopilot_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyBasicMissionAutopilotInstanceEventPayload, deku::DekuError> {
    match MyBasicMissionAutopilotInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyBasicMissionAutopilotInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyBasicMissionAutopilot instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyBasicMissionAutopilotInstanceEventVisitor {
    /// Called when visiting OnPasteAutopilotSetupStatic event.
    fn visit_on_paste_autopilot_setup_static(&mut self, payload: &MyBasicMissionAutopilot_OnPasteAutopilotSetupStaticPayload) {}
    /// Called when visiting OnResetWaypoint event (no payload).
    fn visit_on_reset_waypoint(&mut self) {}
    /// Called when visiting RemoveWaypoints event.
    fn visit_remove_waypoints(&mut self, payload: &MyBasicMissionAutopilot_RemoveWaypointsPayload) {}
    /// Called when visiting MoveWaypointsIndex event.
    fn visit_move_waypoints_index(&mut self, payload: &MyBasicMissionAutopilot_MoveWaypointsIndexPayload) {}
    /// Called when visiting ChangeActions event.
    fn visit_change_actions(&mut self, payload: &MyBasicMissionAutopilot_ChangeActionsPayload) {}
    /// Called when visiting AddWaypoints event.
    fn visit_add_waypoints(&mut self, payload: &MyBasicMissionAutopilot_AddWaypointsPayload) {}
    /// Called when visiting AddWaypointBroadcast event.
    fn visit_add_waypoint_broadcast(&mut self, payload: &MyBasicMissionAutopilot_AddWaypointBroadcastPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyBasicMissionAutopilotInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyBasicMissionAutopilotInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::OnPasteAutopilotSetupStatic(payload) => visitor.visit_on_paste_autopilot_setup_static(payload),
            Self::OnResetWaypoint => visitor.visit_on_reset_waypoint(),
            Self::RemoveWaypoints(payload) => visitor.visit_remove_waypoints(payload),
            Self::MoveWaypointsIndex(payload) => visitor.visit_move_waypoints_index(payload),
            Self::ChangeActions(payload) => visitor.visit_change_actions(payload),
            Self::AddWaypoints(payload) => visitor.visit_add_waypoints(payload),
            Self::AddWaypointBroadcast(payload) => visitor.visit_add_waypoint_broadcast(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyBasicMissionAutopilotInstanceEvent> {
        match self {
            Self::OnPasteAutopilotSetupStatic(_) => Some(MyBasicMissionAutopilotInstanceEvent::OnPasteAutopilotSetupStatic),
            Self::OnResetWaypoint => Some(MyBasicMissionAutopilotInstanceEvent::OnResetWaypoint),
            Self::RemoveWaypoints(_) => Some(MyBasicMissionAutopilotInstanceEvent::RemoveWaypoints),
            Self::MoveWaypointsIndex(_) => Some(MyBasicMissionAutopilotInstanceEvent::MoveWaypointsIndex),
            Self::ChangeActions(_) => Some(MyBasicMissionAutopilotInstanceEvent::ChangeActions),
            Self::AddWaypoints(_) => Some(MyBasicMissionAutopilotInstanceEvent::AddWaypoints),
            Self::AddWaypointBroadcast(_) => Some(MyBasicMissionAutopilotInstanceEvent::AddWaypointBroadcast),
            Self::Unknown { .. } => None,
        }
    }
}
