//! Instance events for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventStoredPower.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyEventStoredPower::UpdateDetailedInfoLimitedBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEventStoredPower_UpdateDetailedInfoLimitedBroadcastPayload {
    pub slot: BitAligned<i32>,
    pub entity_id: BitAligned<i64>,
    pub value: BitAligned<f32>,
}

/// Payload for MyEventStoredPower::UpdateDetailedInfoAllBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEventStoredPower_UpdateDetailedInfoAllBroadcastPayload {
    pub slot: BitAligned<i32>,
    pub entity_id: BitAligned<i64>,
    pub value: BitAligned<f32>,
}

/// Stable instance event identities for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventStoredPower.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyEventStoredPowerInstanceEvent {
    /// Hash: 1250730332
    UpdateDetailedInfoLimitedBroadcast,
    /// Hash: 2007381711
    UpdateDetailedInfoAllBroadcast,
}

impl MyEventStoredPowerInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast => 1250730332,
            Self::UpdateDetailedInfoAllBroadcast => 2007381711,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            1250730332 => Some(Self::UpdateDetailedInfoLimitedBroadcast),
            2007381711 => Some(Self::UpdateDetailedInfoAllBroadcast),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventStoredPower.
///
/// Use `MyEventStoredPowerInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyEventStoredPowerInstanceEventPayload {
    /// UpdateDetailedInfoLimitedBroadcast event payload
    UpdateDetailedInfoLimitedBroadcast(MyEventStoredPower_UpdateDetailedInfoLimitedBroadcastPayload),
    /// UpdateDetailedInfoAllBroadcast event payload
    UpdateDetailedInfoAllBroadcast(MyEventStoredPower_UpdateDetailedInfoAllBroadcastPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyEventStoredPowerInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyEventStoredPowerInstanceEventPayload, deku::DekuError> {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast => {
                let (_, payload) = MyEventStoredPower_UpdateDetailedInfoLimitedBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyEventStoredPowerInstanceEventPayload::UpdateDetailedInfoLimitedBroadcast(payload))
            }
            Self::UpdateDetailedInfoAllBroadcast => {
                let (_, payload) = MyEventStoredPower_UpdateDetailedInfoAllBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyEventStoredPowerInstanceEventPayload::UpdateDetailedInfoAllBroadcast(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyEventStoredPower from raw event hash and bytes.
pub fn parse_my_event_stored_power_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyEventStoredPowerInstanceEventPayload, deku::DekuError> {
    match MyEventStoredPowerInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyEventStoredPowerInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyEventStoredPower instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyEventStoredPowerInstanceEventVisitor {
    /// Called when visiting UpdateDetailedInfoLimitedBroadcast event.
    fn visit_update_detailed_info_limited_broadcast(&mut self, payload: &MyEventStoredPower_UpdateDetailedInfoLimitedBroadcastPayload) {}
    /// Called when visiting UpdateDetailedInfoAllBroadcast event.
    fn visit_update_detailed_info_all_broadcast(&mut self, payload: &MyEventStoredPower_UpdateDetailedInfoAllBroadcastPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyEventStoredPowerInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyEventStoredPowerInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast(payload) => visitor.visit_update_detailed_info_limited_broadcast(payload),
            Self::UpdateDetailedInfoAllBroadcast(payload) => visitor.visit_update_detailed_info_all_broadcast(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyEventStoredPowerInstanceEvent> {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast(_) => Some(MyEventStoredPowerInstanceEvent::UpdateDetailedInfoLimitedBroadcast),
            Self::UpdateDetailedInfoAllBroadcast(_) => Some(MyEventStoredPowerInstanceEvent::UpdateDetailedInfoAllBroadcast),
            Self::Unknown { .. } => None,
        }
    }
}
