//! Instance events for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventGridSpeedChanged.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyEventGridSpeedChanged::UpdateDetailedInfoLimitedBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEventGridSpeedChanged_UpdateDetailedInfoLimitedBroadcastPayload {
    pub slot: BitAligned<i32>,
    pub value: BitAligned<f32>,
}

/// Payload for MyEventGridSpeedChanged::UpdateDetailedInfoAllBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEventGridSpeedChanged_UpdateDetailedInfoAllBroadcastPayload {
    pub slot: BitAligned<i32>,
    pub value: BitAligned<f32>,
}

/// Stable instance event identities for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventGridSpeedChanged.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyEventGridSpeedChangedInstanceEvent {
    /// Hash: -1134125224
    UpdateDetailedInfoLimitedBroadcast,
    /// Hash: 2029100886
    UpdateDetailedInfoAllBroadcast,
}

impl MyEventGridSpeedChangedInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast => -1134125224,
            Self::UpdateDetailedInfoAllBroadcast => 2029100886,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1134125224 => Some(Self::UpdateDetailedInfoLimitedBroadcast),
            2029100886 => Some(Self::UpdateDetailedInfoAllBroadcast),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.EntityComponents.Blocks.Events.MyEventGridSpeedChanged.
///
/// Use `MyEventGridSpeedChangedInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyEventGridSpeedChangedInstanceEventPayload {
    /// UpdateDetailedInfoLimitedBroadcast event payload
    UpdateDetailedInfoLimitedBroadcast(MyEventGridSpeedChanged_UpdateDetailedInfoLimitedBroadcastPayload),
    /// UpdateDetailedInfoAllBroadcast event payload
    UpdateDetailedInfoAllBroadcast(MyEventGridSpeedChanged_UpdateDetailedInfoAllBroadcastPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyEventGridSpeedChangedInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyEventGridSpeedChangedInstanceEventPayload, deku::DekuError> {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast => {
                let (_, payload) = MyEventGridSpeedChanged_UpdateDetailedInfoLimitedBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyEventGridSpeedChangedInstanceEventPayload::UpdateDetailedInfoLimitedBroadcast(payload))
            }
            Self::UpdateDetailedInfoAllBroadcast => {
                let (_, payload) = MyEventGridSpeedChanged_UpdateDetailedInfoAllBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyEventGridSpeedChangedInstanceEventPayload::UpdateDetailedInfoAllBroadcast(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyEventGridSpeedChanged from raw event hash and bytes.
pub fn parse_my_event_grid_speed_changed_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyEventGridSpeedChangedInstanceEventPayload, deku::DekuError> {
    match MyEventGridSpeedChangedInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyEventGridSpeedChangedInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyEventGridSpeedChanged instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyEventGridSpeedChangedInstanceEventVisitor {
    /// Called when visiting UpdateDetailedInfoLimitedBroadcast event.
    fn visit_update_detailed_info_limited_broadcast(&mut self, payload: &MyEventGridSpeedChanged_UpdateDetailedInfoLimitedBroadcastPayload) {}
    /// Called when visiting UpdateDetailedInfoAllBroadcast event.
    fn visit_update_detailed_info_all_broadcast(&mut self, payload: &MyEventGridSpeedChanged_UpdateDetailedInfoAllBroadcastPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyEventGridSpeedChangedInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyEventGridSpeedChangedInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast(payload) => visitor.visit_update_detailed_info_limited_broadcast(payload),
            Self::UpdateDetailedInfoAllBroadcast(payload) => visitor.visit_update_detailed_info_all_broadcast(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyEventGridSpeedChangedInstanceEvent> {
        match self {
            Self::UpdateDetailedInfoLimitedBroadcast(_) => Some(MyEventGridSpeedChangedInstanceEvent::UpdateDetailedInfoLimitedBroadcast),
            Self::UpdateDetailedInfoAllBroadcast(_) => Some(MyEventGridSpeedChangedInstanceEvent::UpdateDetailedInfoAllBroadcast),
            Self::Unknown { .. } => None,
        }
    }
}
