//! Instance events for Sandbox.Game.Components.MyEntityStatComponent.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyEntityStatComponent::OnStatChangedMessage instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEntityStatComponent_OnStatChangedMessagePayload {
    pub changed_stats: VarVec<space_engineers_sys::types::MyEntityStat_MyStatSyncData>,
}

/// Payload for MyEntityStatComponent::OnStatActionMessage instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyEntityStatComponent_OnStatActionMessagePayload {
    pub stat_actions: VarMap<VarString, space_engineers_sys::types::MyStatLogic_MyStatAction>,
}

/// Stable instance event identities for Sandbox.Game.Components.MyEntityStatComponent.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyEntityStatComponentInstanceEvent {
    /// Hash: 460704751
    OnStatChangedMessage,
    /// Hash: 257407946
    OnStatActionRequest,
    /// Hash: 775909653
    OnStatActionMessage,
}

impl MyEntityStatComponentInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::OnStatChangedMessage => 460704751,
            Self::OnStatActionRequest => 257407946,
            Self::OnStatActionMessage => 775909653,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            460704751 => Some(Self::OnStatChangedMessage),
            257407946 => Some(Self::OnStatActionRequest),
            775909653 => Some(Self::OnStatActionMessage),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Components.MyEntityStatComponent.
///
/// Use `MyEntityStatComponentInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyEntityStatComponentInstanceEventPayload {
    /// OnStatChangedMessage event payload
    OnStatChangedMessage(MyEntityStatComponent_OnStatChangedMessagePayload),
    /// OnStatActionRequest event (no payload)
    OnStatActionRequest,
    /// OnStatActionMessage event payload
    OnStatActionMessage(MyEntityStatComponent_OnStatActionMessagePayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyEntityStatComponentInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyEntityStatComponentInstanceEventPayload, deku::DekuError> {
        match self {
            Self::OnStatChangedMessage => {
                let (_, payload) = MyEntityStatComponent_OnStatChangedMessagePayload::from_bytes((bytes, 0))?;
                Ok(MyEntityStatComponentInstanceEventPayload::OnStatChangedMessage(payload))
            }
            Self::OnStatActionRequest => Ok(MyEntityStatComponentInstanceEventPayload::OnStatActionRequest),
            Self::OnStatActionMessage => {
                let (_, payload) = MyEntityStatComponent_OnStatActionMessagePayload::from_bytes((bytes, 0))?;
                Ok(MyEntityStatComponentInstanceEventPayload::OnStatActionMessage(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyEntityStatComponent from raw event hash and bytes.
pub fn parse_my_entity_stat_component_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyEntityStatComponentInstanceEventPayload, deku::DekuError> {
    match MyEntityStatComponentInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyEntityStatComponentInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyEntityStatComponent instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyEntityStatComponentInstanceEventVisitor {
    /// Called when visiting OnStatChangedMessage event.
    fn visit_on_stat_changed_message(&mut self, payload: &MyEntityStatComponent_OnStatChangedMessagePayload) {}
    /// Called when visiting OnStatActionRequest event (no payload).
    fn visit_on_stat_action_request(&mut self) {}
    /// Called when visiting OnStatActionMessage event.
    fn visit_on_stat_action_message(&mut self, payload: &MyEntityStatComponent_OnStatActionMessagePayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyEntityStatComponentInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyEntityStatComponentInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::OnStatChangedMessage(payload) => visitor.visit_on_stat_changed_message(payload),
            Self::OnStatActionRequest => visitor.visit_on_stat_action_request(),
            Self::OnStatActionMessage(payload) => visitor.visit_on_stat_action_message(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyEntityStatComponentInstanceEvent> {
        match self {
            Self::OnStatChangedMessage(_) => Some(MyEntityStatComponentInstanceEvent::OnStatChangedMessage),
            Self::OnStatActionRequest => Some(MyEntityStatComponentInstanceEvent::OnStatActionRequest),
            Self::OnStatActionMessage(_) => Some(MyEntityStatComponentInstanceEvent::OnStatActionMessage),
            Self::Unknown { .. } => None,
        }
    }
}
