//! Instance events for SpaceEngineers.Game.EntityComponents.Blocks.MyLcdSurfaceComponent.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyLcdSurfaceComponent::SetSelectedRotationIndex instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_SetSelectedRotationIndexPayload {
    pub new_index: BitAligned<i32>,
}

/// Payload for MyLcdSurfaceComponent::OnSelectImageRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnSelectImageRequestPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyLcdSurfaceComponent::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyLcdSurfaceComponent::OnRemoveSelectedImageRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnRemoveSelectedImageRequestPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyLcdSurfaceComponent::OnRemoveSelectedImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnRemoveSelectedImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyLcdSurfaceComponent::OnChangeTextRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnChangeTextRequestPayload {
    pub panel_index: BitAligned<i32>,
    pub text: VarString,
}

/// Payload for MyLcdSurfaceComponent::OnUpdateSpriteCollection instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLcdSurfaceComponent_OnUpdateSpriteCollectionPayload {
    pub panel_index: BitAligned<i32>,
    pub sprites: space_engineers_sys::types::MySerializableSpriteCollection,
}

/// Stable instance event identities for SpaceEngineers.Game.EntityComponents.Blocks.MyLcdSurfaceComponent.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyLcdSurfaceComponentInstanceEvent {
    /// Hash: 1125732510
    SetSelectedRotationIndex,
    /// Hash: 1133880669
    OnSelectImageRequest,
    /// Hash: 1688543411
    OnSelectImageSuccess,
    /// Hash: 1165781810
    OnRemoveSelectedImageRequest,
    /// Hash: 190474540
    OnRemoveSelectedImageSuccess,
    /// Hash: -1447265374
    OnChangeTextRequest,
    /// Hash: 485481666
    OnUpdateSpriteCollection,
}

impl MyLcdSurfaceComponentInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetSelectedRotationIndex => 1125732510,
            Self::OnSelectImageRequest => 1133880669,
            Self::OnSelectImageSuccess => 1688543411,
            Self::OnRemoveSelectedImageRequest => 1165781810,
            Self::OnRemoveSelectedImageSuccess => 190474540,
            Self::OnChangeTextRequest => -1447265374,
            Self::OnUpdateSpriteCollection => 485481666,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            1125732510 => Some(Self::SetSelectedRotationIndex),
            1133880669 => Some(Self::OnSelectImageRequest),
            1688543411 => Some(Self::OnSelectImageSuccess),
            1165781810 => Some(Self::OnRemoveSelectedImageRequest),
            190474540 => Some(Self::OnRemoveSelectedImageSuccess),
            -1447265374 => Some(Self::OnChangeTextRequest),
            485481666 => Some(Self::OnUpdateSpriteCollection),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.EntityComponents.Blocks.MyLcdSurfaceComponent.
///
/// Use `MyLcdSurfaceComponentInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyLcdSurfaceComponentInstanceEventPayload {
    /// SetSelectedRotationIndex event payload
    SetSelectedRotationIndex(MyLcdSurfaceComponent_SetSelectedRotationIndexPayload),
    /// OnSelectImageRequest event payload
    OnSelectImageRequest(MyLcdSurfaceComponent_OnSelectImageRequestPayload),
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyLcdSurfaceComponent_OnSelectImageSuccessPayload),
    /// OnRemoveSelectedImageRequest event payload
    OnRemoveSelectedImageRequest(MyLcdSurfaceComponent_OnRemoveSelectedImageRequestPayload),
    /// OnRemoveSelectedImageSuccess event payload
    OnRemoveSelectedImageSuccess(MyLcdSurfaceComponent_OnRemoveSelectedImageSuccessPayload),
    /// OnChangeTextRequest event payload
    OnChangeTextRequest(MyLcdSurfaceComponent_OnChangeTextRequestPayload),
    /// OnUpdateSpriteCollection event payload
    OnUpdateSpriteCollection(MyLcdSurfaceComponent_OnUpdateSpriteCollectionPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyLcdSurfaceComponentInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyLcdSurfaceComponentInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetSelectedRotationIndex => {
                let (_, payload) = MyLcdSurfaceComponent_SetSelectedRotationIndexPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::SetSelectedRotationIndex(payload))
            }
            Self::OnSelectImageRequest => {
                let (_, payload) = MyLcdSurfaceComponent_OnSelectImageRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnSelectImageRequest(payload))
            }
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyLcdSurfaceComponent_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::OnRemoveSelectedImageRequest => {
                let (_, payload) = MyLcdSurfaceComponent_OnRemoveSelectedImageRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnRemoveSelectedImageRequest(payload))
            }
            Self::OnRemoveSelectedImageSuccess => {
                let (_, payload) = MyLcdSurfaceComponent_OnRemoveSelectedImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnRemoveSelectedImageSuccess(payload))
            }
            Self::OnChangeTextRequest => {
                let (_, payload) = MyLcdSurfaceComponent_OnChangeTextRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnChangeTextRequest(payload))
            }
            Self::OnUpdateSpriteCollection => {
                let (_, payload) = MyLcdSurfaceComponent_OnUpdateSpriteCollectionPayload::from_bytes((bytes, 0))?;
                Ok(MyLcdSurfaceComponentInstanceEventPayload::OnUpdateSpriteCollection(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyLcdSurfaceComponent from raw event hash and bytes.
pub fn parse_my_lcd_surface_component_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyLcdSurfaceComponentInstanceEventPayload, deku::DekuError> {
    match MyLcdSurfaceComponentInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyLcdSurfaceComponentInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyLcdSurfaceComponent instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyLcdSurfaceComponentInstanceEventVisitor {
    /// Called when visiting SetSelectedRotationIndex event.
    fn visit_set_selected_rotation_index(&mut self, payload: &MyLcdSurfaceComponent_SetSelectedRotationIndexPayload) {}
    /// Called when visiting OnSelectImageRequest event.
    fn visit_on_select_image_request(&mut self, payload: &MyLcdSurfaceComponent_OnSelectImageRequestPayload) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyLcdSurfaceComponent_OnSelectImageSuccessPayload) {}
    /// Called when visiting OnRemoveSelectedImageRequest event.
    fn visit_on_remove_selected_image_request(&mut self, payload: &MyLcdSurfaceComponent_OnRemoveSelectedImageRequestPayload) {}
    /// Called when visiting OnRemoveSelectedImageSuccess event.
    fn visit_on_remove_selected_image_success(&mut self, payload: &MyLcdSurfaceComponent_OnRemoveSelectedImageSuccessPayload) {}
    /// Called when visiting OnChangeTextRequest event.
    fn visit_on_change_text_request(&mut self, payload: &MyLcdSurfaceComponent_OnChangeTextRequestPayload) {}
    /// Called when visiting OnUpdateSpriteCollection event.
    fn visit_on_update_sprite_collection(&mut self, payload: &MyLcdSurfaceComponent_OnUpdateSpriteCollectionPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyLcdSurfaceComponentInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyLcdSurfaceComponentInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetSelectedRotationIndex(payload) => visitor.visit_set_selected_rotation_index(payload),
            Self::OnSelectImageRequest(payload) => visitor.visit_on_select_image_request(payload),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::OnRemoveSelectedImageRequest(payload) => visitor.visit_on_remove_selected_image_request(payload),
            Self::OnRemoveSelectedImageSuccess(payload) => visitor.visit_on_remove_selected_image_success(payload),
            Self::OnChangeTextRequest(payload) => visitor.visit_on_change_text_request(payload),
            Self::OnUpdateSpriteCollection(payload) => visitor.visit_on_update_sprite_collection(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyLcdSurfaceComponentInstanceEvent> {
        match self {
            Self::SetSelectedRotationIndex(_) => Some(MyLcdSurfaceComponentInstanceEvent::SetSelectedRotationIndex),
            Self::OnSelectImageRequest(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnSelectImageRequest),
            Self::OnSelectImageSuccess(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnSelectImageSuccess),
            Self::OnRemoveSelectedImageRequest(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnRemoveSelectedImageRequest),
            Self::OnRemoveSelectedImageSuccess(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnRemoveSelectedImageSuccess),
            Self::OnChangeTextRequest(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnChangeTextRequest),
            Self::OnUpdateSpriteCollection(_) => Some(MyLcdSurfaceComponentInstanceEvent::OnUpdateSpriteCollection),
            Self::Unknown { .. } => None,
        }
    }
}
