//! Instance events for Sandbox.Game.EntityComponents.MyPathRecorderComponent.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyPathRecorderComponent::DeleteWaypoints instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_DeleteWaypointsPayload {
    pub waypoint_indexes: VarVec<BitAligned<i32>>,
}

/// Payload for MyPathRecorderComponent::DeleteActions instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_DeleteActionsPayload {
    pub waypoint_index: BitAligned<i32>,
    pub actions: VarVec<space_engineers_sys::types::ToolbarItem>,
}

/// Payload for MyPathRecorderComponent::ChangeActions instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_ChangeActionsPayload {
    pub waypoint_index: BitAligned<i32>,
    pub toolbar_ob: space_engineers_sys::types::MyObjectBuilder_Toolbar,
}

/// Payload for MyPathRecorderComponent::AddWaypointBroadcast_5 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_AddWaypointBroadcast_5Payload {
    pub position: space_engineers_sys::math::MatrixD,
}

/// Payload for MyPathRecorderComponent::AddWaypointBroadcast_6 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_AddWaypointBroadcast_6Payload {
    pub matrix: space_engineers_sys::math::MatrixD,
    pub related_entity_id: BitAligned<i64>,
    pub name: VarString,
}

/// Payload for MyPathRecorderComponent::AddWaypointBroadcast_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyPathRecorderComponent_AddWaypointBroadcast_7Payload {
    pub position: space_engineers_sys::math::MatrixD,
    pub item: space_engineers_sys::types::ToolbarItem,
}

/// Stable instance event identities for Sandbox.Game.EntityComponents.MyPathRecorderComponent.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyPathRecorderComponentInstanceEvent {
    /// Hash: 1762576984
    ReverseAllWaypoints,
    /// Hash: -1772682474
    DeleteAllWaypoints,
    /// Hash: -456104911
    DeleteWaypoints,
    /// Hash: -1647276026
    DeleteActions,
    /// Hash: 262523279
    ChangeActions,
    /// Hash: 600188137
    AddWaypointBroadcast_5,
    /// Hash: -60023827
    AddWaypointBroadcast_6,
    /// Hash: 46293344
    AddWaypointBroadcast_7,
}

impl MyPathRecorderComponentInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::ReverseAllWaypoints => 1762576984,
            Self::DeleteAllWaypoints => -1772682474,
            Self::DeleteWaypoints => -456104911,
            Self::DeleteActions => -1647276026,
            Self::ChangeActions => 262523279,
            Self::AddWaypointBroadcast_5 => 600188137,
            Self::AddWaypointBroadcast_6 => -60023827,
            Self::AddWaypointBroadcast_7 => 46293344,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            1762576984 => Some(Self::ReverseAllWaypoints),
            -1772682474 => Some(Self::DeleteAllWaypoints),
            -456104911 => Some(Self::DeleteWaypoints),
            -1647276026 => Some(Self::DeleteActions),
            262523279 => Some(Self::ChangeActions),
            600188137 => Some(Self::AddWaypointBroadcast_5),
            -60023827 => Some(Self::AddWaypointBroadcast_6),
            46293344 => Some(Self::AddWaypointBroadcast_7),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.EntityComponents.MyPathRecorderComponent.
///
/// Use `MyPathRecorderComponentInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyPathRecorderComponentInstanceEventPayload {
    /// ReverseAllWaypoints event (no payload)
    ReverseAllWaypoints,
    /// DeleteAllWaypoints event (no payload)
    DeleteAllWaypoints,
    /// DeleteWaypoints event payload
    DeleteWaypoints(MyPathRecorderComponent_DeleteWaypointsPayload),
    /// DeleteActions event payload
    DeleteActions(MyPathRecorderComponent_DeleteActionsPayload),
    /// ChangeActions event payload
    ChangeActions(MyPathRecorderComponent_ChangeActionsPayload),
    /// AddWaypointBroadcast_5 event payload
    AddWaypointBroadcast_5(MyPathRecorderComponent_AddWaypointBroadcast_5Payload),
    /// AddWaypointBroadcast_6 event payload
    AddWaypointBroadcast_6(MyPathRecorderComponent_AddWaypointBroadcast_6Payload),
    /// AddWaypointBroadcast_7 event payload
    AddWaypointBroadcast_7(MyPathRecorderComponent_AddWaypointBroadcast_7Payload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyPathRecorderComponentInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyPathRecorderComponentInstanceEventPayload, deku::DekuError> {
        match self {
            Self::ReverseAllWaypoints => Ok(MyPathRecorderComponentInstanceEventPayload::ReverseAllWaypoints),
            Self::DeleteAllWaypoints => Ok(MyPathRecorderComponentInstanceEventPayload::DeleteAllWaypoints),
            Self::DeleteWaypoints => {
                let (_, payload) = MyPathRecorderComponent_DeleteWaypointsPayload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::DeleteWaypoints(payload))
            }
            Self::DeleteActions => {
                let (_, payload) = MyPathRecorderComponent_DeleteActionsPayload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::DeleteActions(payload))
            }
            Self::ChangeActions => {
                let (_, payload) = MyPathRecorderComponent_ChangeActionsPayload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::ChangeActions(payload))
            }
            Self::AddWaypointBroadcast_5 => {
                let (_, payload) = MyPathRecorderComponent_AddWaypointBroadcast_5Payload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::AddWaypointBroadcast_5(payload))
            }
            Self::AddWaypointBroadcast_6 => {
                let (_, payload) = MyPathRecorderComponent_AddWaypointBroadcast_6Payload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::AddWaypointBroadcast_6(payload))
            }
            Self::AddWaypointBroadcast_7 => {
                let (_, payload) = MyPathRecorderComponent_AddWaypointBroadcast_7Payload::from_bytes((bytes, 0))?;
                Ok(MyPathRecorderComponentInstanceEventPayload::AddWaypointBroadcast_7(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyPathRecorderComponent from raw event hash and bytes.
pub fn parse_my_path_recorder_component_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyPathRecorderComponentInstanceEventPayload, deku::DekuError> {
    match MyPathRecorderComponentInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyPathRecorderComponentInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyPathRecorderComponent instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyPathRecorderComponentInstanceEventVisitor {
    /// Called when visiting ReverseAllWaypoints event (no payload).
    fn visit_reverse_all_waypoints(&mut self) {}
    /// Called when visiting DeleteAllWaypoints event (no payload).
    fn visit_delete_all_waypoints(&mut self) {}
    /// Called when visiting DeleteWaypoints event.
    fn visit_delete_waypoints(&mut self, payload: &MyPathRecorderComponent_DeleteWaypointsPayload) {}
    /// Called when visiting DeleteActions event.
    fn visit_delete_actions(&mut self, payload: &MyPathRecorderComponent_DeleteActionsPayload) {}
    /// Called when visiting ChangeActions event.
    fn visit_change_actions(&mut self, payload: &MyPathRecorderComponent_ChangeActionsPayload) {}
    /// Called when visiting AddWaypointBroadcast_5 event.
    fn visit_add_waypoint_broadcast_5(&mut self, payload: &MyPathRecorderComponent_AddWaypointBroadcast_5Payload) {}
    /// Called when visiting AddWaypointBroadcast_6 event.
    fn visit_add_waypoint_broadcast_6(&mut self, payload: &MyPathRecorderComponent_AddWaypointBroadcast_6Payload) {}
    /// Called when visiting AddWaypointBroadcast_7 event.
    fn visit_add_waypoint_broadcast_7(&mut self, payload: &MyPathRecorderComponent_AddWaypointBroadcast_7Payload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyPathRecorderComponentInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyPathRecorderComponentInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::ReverseAllWaypoints => visitor.visit_reverse_all_waypoints(),
            Self::DeleteAllWaypoints => visitor.visit_delete_all_waypoints(),
            Self::DeleteWaypoints(payload) => visitor.visit_delete_waypoints(payload),
            Self::DeleteActions(payload) => visitor.visit_delete_actions(payload),
            Self::ChangeActions(payload) => visitor.visit_change_actions(payload),
            Self::AddWaypointBroadcast_5(payload) => visitor.visit_add_waypoint_broadcast_5(payload),
            Self::AddWaypointBroadcast_6(payload) => visitor.visit_add_waypoint_broadcast_6(payload),
            Self::AddWaypointBroadcast_7(payload) => visitor.visit_add_waypoint_broadcast_7(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyPathRecorderComponentInstanceEvent> {
        match self {
            Self::ReverseAllWaypoints => Some(MyPathRecorderComponentInstanceEvent::ReverseAllWaypoints),
            Self::DeleteAllWaypoints => Some(MyPathRecorderComponentInstanceEvent::DeleteAllWaypoints),
            Self::DeleteWaypoints(_) => Some(MyPathRecorderComponentInstanceEvent::DeleteWaypoints),
            Self::DeleteActions(_) => Some(MyPathRecorderComponentInstanceEvent::DeleteActions),
            Self::ChangeActions(_) => Some(MyPathRecorderComponentInstanceEvent::ChangeActions),
            Self::AddWaypointBroadcast_5(_) => Some(MyPathRecorderComponentInstanceEvent::AddWaypointBroadcast_5),
            Self::AddWaypointBroadcast_6(_) => Some(MyPathRecorderComponentInstanceEvent::AddWaypointBroadcast_6),
            Self::AddWaypointBroadcast_7(_) => Some(MyPathRecorderComponentInstanceEvent::AddWaypointBroadcast_7),
            Self::Unknown { .. } => None,
        }
    }
}
