//! Instance events for Sandbox.Game.Entities.MyCubeGrid.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyCubeGrid::MergeGrid_MergeClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_MergeGrid_MergeClientPayload {
    pub grid_id: BitAligned<i64>,
    pub grid_offset: space_engineers_sys::math::SerializableVector3I,
    pub grid_forward: space_engineers_compat::direction::Direction,
    pub grid_up: space_engineers_compat::direction::Direction,
    pub merging_block_pos: space_engineers_sys::math::Vector3I,
}

/// Payload for MyCubeGrid::MergeGrid_MergeBlockClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_MergeGrid_MergeBlockClientPayload {
    pub grid_id: BitAligned<i64>,
    pub grid_offset: space_engineers_sys::math::SerializableVector3I,
    pub grid_forward: space_engineers_compat::direction::Direction,
    pub grid_up: space_engineers_compat::direction::Direction,
}

/// Payload for MyCubeGrid::CreateSplit_Implementation instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_CreateSplit_ImplementationPayload {
    pub blocks: VarVec<space_engineers_sys::math::Vector3I>,
    pub new_entity_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::CreateSplits_Implementation instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_CreateSplits_ImplementationPayload {
    pub blocks: VarVec<space_engineers_sys::math::Vector3I>,
    pub groups: VarVec<space_engineers_sys::types::MyDisconnectHelper_Group>,
}

/// Payload for MyCubeGrid::UpdateTimeOnClients instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_UpdateTimeOnClientsPayload {
    pub seconds_remaining: BitAligned<i32>,
}

/// Payload for MyCubeGrid::RemovedBlocks instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RemovedBlocksPayload {
    pub destroy_locations: VarVec<space_engineers_sys::math::Vector3I>,
    pub destruction_deformation_location: VarVec<space_engineers_sys::math::Vector3I>,
    pub locations_without_generator: VarVec<space_engineers_sys::math::Vector3I>,
}

/// Payload for MyCubeGrid::RemovedBlocksWithIds instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RemovedBlocksWithIdsPayload {
    pub destroy_block_with_id_queue_without_generators: VarVec<space_engineers_sys::types::MyCubeGrid_BlockPositionId>,
    pub remove_block_with_id_queue_without_generators: VarVec<space_engineers_sys::types::MyCubeGrid_BlockPositionId>,
}

/// Payload for MyCubeGrid::RemoveBlocksBuiltByIDs instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RemoveBlocksBuiltByIDsPayload {
    pub identity_ids: VarVec<BitAligned<i64>>,
}

/// Payload for MyCubeGrid::TransferBlocksBuiltByID instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_TransferBlocksBuiltByIDPayload {
    pub old_author: BitAligned<i64>,
    pub new_author: BitAligned<i64>,
}

/// Payload for MyCubeGrid::BuildBlockSucess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BuildBlockSucessPayload {
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub location: space_engineers_sys::types::MyCubeGrid_MyBlockLocation,
    pub block_object_builder: space_engineers_sys::types::MyObjectBuilder_CubeBlock,
    pub builder_entity_id: BitAligned<i64>,
    pub instant_build: BitBool,
    pub owner_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::BuildBlocksRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BuildBlocksRequestPayload {
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub locations: VarVec<space_engineers_sys::types::MyCubeGrid_MyBlockLocation>,
    pub builder_entity_id: BitAligned<i64>,
    pub instant_build: BitBool,
    pub owner_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::BuildBlocksClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BuildBlocksClientPayload {
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub locations: VarVec<space_engineers_sys::types::MyCubeGrid_MyBlockLocation>,
    pub builder_entity_id: BitAligned<i64>,
    pub instant_build: BitBool,
    pub owner_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::BuildBlocksAreaRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BuildBlocksAreaRequestPayload {
    pub area: space_engineers_sys::types::MyCubeGrid_MyBlockBuildArea,
    pub builder_entity_id: BitAligned<i64>,
    pub instant_build: BitBool,
    pub owner_id: BitAligned<i64>,
    pub placing_player: BitAligned<u64>,
    pub localized_display_name_base: VarString,
}

/// Payload for MyCubeGrid::BuildBlocksAreaClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BuildBlocksAreaClientPayload {
    pub area: space_engineers_sys::types::MyCubeGrid_MyBlockBuildArea,
    pub entity_id_seed: BitAligned<i32>,
    pub fail_list: VarVec<space_engineers_sys::types::Vector3UByte>,
    pub builder_entity_id: BitAligned<i64>,
    pub is_admin: BitBool,
    pub owner_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::RazeBlocksAreaRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RazeBlocksAreaRequestPayload {
    pub pos: space_engineers_sys::math::Vector3I,
    pub size: space_engineers_sys::types::Vector3UByte,
    pub builder_entity_id: BitAligned<i64>,
    pub placing_player: BitAligned<u64>,
}

/// Payload for MyCubeGrid::RazeBlocksAreaSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RazeBlocksAreaSuccessPayload {
    pub pos: space_engineers_sys::math::Vector3I,
    pub size: space_engineers_sys::types::Vector3UByte,
    pub result_fail_list: VarVec<space_engineers_sys::types::Vector3UByte>,
}

/// Payload for MyCubeGrid::RazeBlocksRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RazeBlocksRequestPayload {
    pub locations: VarVec<space_engineers_sys::math::Vector3I>,
    pub builder_entity_id: BitAligned<i64>,
    pub user: BitAligned<u64>,
}

/// Payload for MyCubeGrid::RazeBlocksClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RazeBlocksClientPayload {
    pub locations: VarVec<space_engineers_sys::math::Vector3I>,
}

/// Payload for MyCubeGrid::ColorGridFriendlyRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_ColorGridFriendlyRequestPayload {
    pub new_hsv: Vector3F,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::OnColorGridFriendly instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnColorGridFriendlyPayload {
    pub new_hsv: Vector3F,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::ColorBlockRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_ColorBlockRequestPayload {
    pub min: space_engineers_sys::math::Vector3I,
    pub max: space_engineers_sys::math::Vector3I,
    pub new_hsv: Vector3F,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::OnColorBlock instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnColorBlockPayload {
    pub min: space_engineers_sys::math::Vector3I,
    pub max: space_engineers_sys::math::Vector3I,
    pub new_hsv: Vector3F,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::SkinGridFriendlyRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_SkinGridFriendlyRequestPayload {
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::OnSkinGridFriendly instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnSkinGridFriendlyPayload {
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::SkinBlockRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_SkinBlockRequestPayload {
    pub min: space_engineers_sys::math::Vector3I,
    pub max: space_engineers_sys::math::Vector3I,
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::OnSkinBlock instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnSkinBlockPayload {
    pub min: space_engineers_sys::math::Vector3I,
    pub max: space_engineers_sys::math::Vector3I,
    pub visuals: space_engineers_sys::types::MyCubeGrid_MyBlockVisuals,
    pub play_sound: BitBool,
}

/// Payload for MyCubeGrid::BlockIntegrityChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BlockIntegrityChangedPayload {
    pub pos: space_engineers_sys::math::Vector3I,
    pub build_integrity: BitAligned<f32>,
    pub integrity: BitAligned<f32>,
    pub integrity_change_type: space_engineers_sys::types::MyIntegrityChangeEnum,
    pub grinder_owner: BitAligned<i64>,
}

/// Payload for MyCubeGrid::BlockStockpileChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_BlockStockpileChangedPayload {
    pub pos: space_engineers_sys::math::Vector3I,
    pub items: VarVec<space_engineers_sys::types::MyStockpileItem>,
}

/// Payload for MyCubeGrid::PasteBlocksToGridServer_Implementation instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_PasteBlocksToGridServer_ImplementationPayload {
    pub grids_to_merge: VarVec<space_engineers_sys::types::MyObjectBuilder_CubeGrid>,
    pub inventory_entity_id: BitAligned<i64>,
    pub instant_build: BitBool,
    pub client_dlcids: VarVec<BitAligned<u64>>,
}

/// Payload for MyCubeGrid::PasteBlocksToGridClient_Implementation instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_PasteBlocksToGridClient_ImplementationPayload {
    pub grid_to_merge: space_engineers_sys::types::MyObjectBuilder_CubeGrid,
    pub merge_transform: space_engineers_sys::types::MatrixI,
}

/// Payload for MyCubeGrid::OnBonesReceived instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnBonesReceivedPayload {
    pub segments_count: BitAligned<i32>,
    pub bone_byte_list: VarVec<BitAligned<u8>>,
}

/// Payload for MyCubeGrid::OnBonesMultiplied instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnBonesMultipliedPayload {
    pub block_location: space_engineers_sys::math::Vector3I,
    pub multiplier: BitAligned<f32>,
}

/// Payload for MyCubeGrid::RelfectorStateRecived instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RelfectorStateRecivedPayload {
    pub value: space_engineers_sys::types::MyMultipleEnabledEnum,
}

/// Payload for MyCubeGrid::OnStockpileFillRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnStockpileFillRequestPayload {
    pub block_position: space_engineers_sys::math::Vector3I,
    pub owner_entity_id: BitAligned<i64>,
    pub inventory_index: BitAligned<u8>,
}

/// Payload for MyCubeGrid::OnPowerProducerStateRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnPowerProducerStateRequestPayload {
    pub enabled_state: space_engineers_sys::types::MyMultipleEnabledEnum,
    pub local_grid_only: BitBool,
}

/// Payload for MyCubeGrid::OnConvertedToShipRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnConvertedToShipRequestPayload {
    pub reason: space_engineers_sys::types::MyCubeGrid_MyTestDynamicReason,
}

/// Payload for MyCubeGrid::OnChangeOwnerRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnChangeOwnerRequestPayload {
    pub block_id: BitAligned<i64>,
    pub owner: BitAligned<i64>,
    pub share_mode: space_engineers_sys::types::MyOwnershipShareModeEnum,
}

/// Payload for MyCubeGrid::OnChangeOwner instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnChangeOwnerPayload {
    pub block_id: BitAligned<i64>,
    pub owner: BitAligned<i64>,
    pub share_mode: space_engineers_sys::types::MyOwnershipShareModeEnum,
}

/// Payload for MyCubeGrid::ReceiveHandbrakeRequestResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_ReceiveHandbrakeRequestResultPayload {
    pub result: space_engineers_sys::types::MyCubeGrid_HandbrakeToggleResult,
    pub message: VarString,
}

/// Payload for MyCubeGrid::ReceiveParkRequestResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_ReceiveParkRequestResultPayload {
    pub result: space_engineers_sys::types::MyCubeGrid_HandbrakeToggleResult,
    pub message: VarString,
}

/// Payload for MyCubeGrid::OnChangeGridOwner instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnChangeGridOwnerPayload {
    pub player_id: BitAligned<i64>,
    pub share_mode: space_engineers_sys::types::MyOwnershipShareModeEnum,
}

/// Payload for MyCubeGrid::OnRemoveSplit instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnRemoveSplitPayload {
    pub removed_blocks: VarVec<space_engineers_sys::math::Vector3I>,
}

/// Payload for MyCubeGrid::OnChangeDisplayNameRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnChangeDisplayNameRequestPayload {
    pub display_name: VarString,
}

/// Payload for MyCubeGrid::OnModifyGroupSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnModifyGroupSuccessPayload {
    pub name: VarString,
    pub blocks: VarVec<BitAligned<i64>>,
}

/// Payload for MyCubeGrid::DepressurizeEffect instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_DepressurizeEffectPayload {
    pub from: space_engineers_sys::math::Vector3I,
    pub to: space_engineers_sys::math::Vector3I,
}

/// Payload for MyCubeGrid::InvokeJumpInternal instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_InvokeJumpInternalPayload {
    pub initiate: BitBool,
}

/// Payload for MyCubeGrid::OnJumpRequested instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnJumpRequestedPayload {
    pub jump_target: Vector3D,
    pub user_id: BitAligned<i64>,
    pub jump_drive_delay: BitAligned<f32>,
    pub drive_entity_id: Nullable<BitAligned<i64>>,
}

/// Payload for MyCubeGrid::OnJumpSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_OnJumpSuccessPayload {
    pub jump_target: Vector3D,
    pub user_id: BitAligned<i64>,
    pub jump_drive_delay: BitAligned<f32>,
    pub drive_entity_id: Nullable<BitAligned<i64>>,
}

/// Payload for MyCubeGrid::PlayParticleBroadcast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_PlayParticleBroadcastPayload {
    pub particle_name: VarString,
    pub smoke: BitBool,
}

/// Payload for MyCubeGrid::RemoveContainerDropComponent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_RemoveContainerDropComponentPayload {
    pub block_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::ContainerOpened instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_ContainerOpenedPayload {
    pub entity_id: BitAligned<i64>,
}

/// Payload for MyCubeGrid::CompetetiveContainerOpened instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCubeGrid_CompetetiveContainerOpenedPayload {
    pub entity_id: BitAligned<i64>,
    pub time: BitAligned<i32>,
    pub color: space_engineers_sys::types::Color,
}

/// Stable instance event identities for Sandbox.Game.Entities.MyCubeGrid.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyCubeGridInstanceEvent {
    /// Hash: 575530984
    MergeGrid_MergeClient,
    /// Hash: -1909161668
    MergeGrid_MergeBlockClient,
    /// Hash: -770670173
    OnGridChangedRPC,
    /// Hash: 823858902
    CreateSplit_Implementation,
    /// Hash: -681223766
    CreateSplits_Implementation,
    /// Hash: 1491101698
    UpdateTimeOnClients,
    /// Hash: 1561893632
    RemovedBlocks,
    /// Hash: 581563810
    RemovedBlocksWithIds,
    /// Hash: 550591225
    RemoveBlocksBuiltByIDs,
    /// Hash: 1969620910
    TransferBlocksBuiltByID,
    /// Hash: -354205189
    BuildBlockSucess,
    /// Hash: 1249233947
    BuildBlocksRequest,
    /// Hash: -263130719
    BuildBlocksFailedNotify,
    /// Hash: 834026264
    BuildBlocksClient,
    /// Hash: -1946750553
    BuildBlocksAreaRequest,
    /// Hash: -1812935001
    BuildBlocksAreaClient,
    /// Hash: -603394896
    RazeBlocksAreaRequest,
    /// Hash: -1054063648
    RazeBlocksAreaSuccess,
    /// Hash: -1646669051
    RazeBlocksRequest,
    /// Hash: 495093934
    RazeBlocksClient,
    /// Hash: 1734727161
    ColorGridFriendlyRequest,
    /// Hash: 151435633
    OnColorGridFriendly,
    /// Hash: -1362921269
    OnColorGridBlockFailed,
    /// Hash: -602048454
    ColorBlockRequest,
    /// Hash: -404146891
    OnColorBlock,
    /// Hash: -4381308
    SkinGridFriendlyRequest,
    /// Hash: -781634572
    OnSkinGridFriendly,
    /// Hash: -354556542
    SkinBlockRequest,
    /// Hash: -884973083
    OnSkinBlock,
    /// Hash: -487709288
    OnConvertToDynamic,
    /// Hash: -938916014
    ConvertToStatic,
    /// Hash: 1631008544
    BlockIntegrityChanged,
    /// Hash: 1760065692
    BlockStockpileChanged,
    /// Hash: -1099364648
    PasteBlocksToGridServer_Implementation,
    /// Hash: -743959690
    PasteBlocksToGridClient_Implementation,
    /// Hash: 622249059
    StationClosingDenied,
    /// Hash: 1028864154
    OnGridClosedRequest,
    /// Hash: -183493786
    OnBonesReceived,
    /// Hash: 260096413
    OnBonesMultiplied,
    /// Hash: 276084550
    RelfectorStateRecived,
    /// Hash: 99995844
    OnStockpileFillRequest,
    /// Hash: -61192616
    OnPowerProducerStateRequest,
    /// Hash: 1155167915
    OnConvertedToShipRequest,
    /// Hash: 1177176633
    OnConvertToShipFailed,
    /// Hash: 1774231477
    OnConvertedToStationRequest,
    /// Hash: -1490620503
    OnChangeOwnerRequest,
    /// Hash: 1461916729
    OnChangeOwner,
    /// Hash: -496826902
    ToggleHandbrakeRequest,
    /// Hash: -174639469
    ReceiveHandbrakeRequestResult,
    /// Hash: 1173731473
    ToggleParkStateRequest,
    /// Hash: 850402221
    ReceiveParkRequestResult,
    /// Hash: -863725756
    OnChangeGridOwner,
    /// Hash: -1058060139
    OnRemoveSplit,
    /// Hash: 95137188
    OnChangeDisplayNameRequest,
    /// Hash: 739298117
    OnModifyGroupSuccess,
    /// Hash: -79926208
    OnLogHierarchy,
    /// Hash: -603502464
    DepressurizeEffect,
    /// Hash: -1242219506
    InvokeJumpInternal,
    /// Hash: 1777655630
    OnAbortJump,
    /// Hash: -1648812944
    OnJumpRequested,
    /// Hash: -442493598
    OnJumpSuccess,
    /// Hash: 696694534
    PlayParticleBroadcast,
    /// Hash: -1225717816
    RemoveContainerDropComponent,
    /// Hash: -581775129
    StopSmoke,
    /// Hash: -1982159355
    ContainerOpened,
    /// Hash: -308851915
    CompetetiveContainerOpened,
}

impl MyCubeGridInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::MergeGrid_MergeClient => 575530984,
            Self::MergeGrid_MergeBlockClient => -1909161668,
            Self::OnGridChangedRPC => -770670173,
            Self::CreateSplit_Implementation => 823858902,
            Self::CreateSplits_Implementation => -681223766,
            Self::UpdateTimeOnClients => 1491101698,
            Self::RemovedBlocks => 1561893632,
            Self::RemovedBlocksWithIds => 581563810,
            Self::RemoveBlocksBuiltByIDs => 550591225,
            Self::TransferBlocksBuiltByID => 1969620910,
            Self::BuildBlockSucess => -354205189,
            Self::BuildBlocksRequest => 1249233947,
            Self::BuildBlocksFailedNotify => -263130719,
            Self::BuildBlocksClient => 834026264,
            Self::BuildBlocksAreaRequest => -1946750553,
            Self::BuildBlocksAreaClient => -1812935001,
            Self::RazeBlocksAreaRequest => -603394896,
            Self::RazeBlocksAreaSuccess => -1054063648,
            Self::RazeBlocksRequest => -1646669051,
            Self::RazeBlocksClient => 495093934,
            Self::ColorGridFriendlyRequest => 1734727161,
            Self::OnColorGridFriendly => 151435633,
            Self::OnColorGridBlockFailed => -1362921269,
            Self::ColorBlockRequest => -602048454,
            Self::OnColorBlock => -404146891,
            Self::SkinGridFriendlyRequest => -4381308,
            Self::OnSkinGridFriendly => -781634572,
            Self::SkinBlockRequest => -354556542,
            Self::OnSkinBlock => -884973083,
            Self::OnConvertToDynamic => -487709288,
            Self::ConvertToStatic => -938916014,
            Self::BlockIntegrityChanged => 1631008544,
            Self::BlockStockpileChanged => 1760065692,
            Self::PasteBlocksToGridServer_Implementation => -1099364648,
            Self::PasteBlocksToGridClient_Implementation => -743959690,
            Self::StationClosingDenied => 622249059,
            Self::OnGridClosedRequest => 1028864154,
            Self::OnBonesReceived => -183493786,
            Self::OnBonesMultiplied => 260096413,
            Self::RelfectorStateRecived => 276084550,
            Self::OnStockpileFillRequest => 99995844,
            Self::OnPowerProducerStateRequest => -61192616,
            Self::OnConvertedToShipRequest => 1155167915,
            Self::OnConvertToShipFailed => 1177176633,
            Self::OnConvertedToStationRequest => 1774231477,
            Self::OnChangeOwnerRequest => -1490620503,
            Self::OnChangeOwner => 1461916729,
            Self::ToggleHandbrakeRequest => -496826902,
            Self::ReceiveHandbrakeRequestResult => -174639469,
            Self::ToggleParkStateRequest => 1173731473,
            Self::ReceiveParkRequestResult => 850402221,
            Self::OnChangeGridOwner => -863725756,
            Self::OnRemoveSplit => -1058060139,
            Self::OnChangeDisplayNameRequest => 95137188,
            Self::OnModifyGroupSuccess => 739298117,
            Self::OnLogHierarchy => -79926208,
            Self::DepressurizeEffect => -603502464,
            Self::InvokeJumpInternal => -1242219506,
            Self::OnAbortJump => 1777655630,
            Self::OnJumpRequested => -1648812944,
            Self::OnJumpSuccess => -442493598,
            Self::PlayParticleBroadcast => 696694534,
            Self::RemoveContainerDropComponent => -1225717816,
            Self::StopSmoke => -581775129,
            Self::ContainerOpened => -1982159355,
            Self::CompetetiveContainerOpened => -308851915,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            575530984 => Some(Self::MergeGrid_MergeClient),
            -1909161668 => Some(Self::MergeGrid_MergeBlockClient),
            -770670173 => Some(Self::OnGridChangedRPC),
            823858902 => Some(Self::CreateSplit_Implementation),
            -681223766 => Some(Self::CreateSplits_Implementation),
            1491101698 => Some(Self::UpdateTimeOnClients),
            1561893632 => Some(Self::RemovedBlocks),
            581563810 => Some(Self::RemovedBlocksWithIds),
            550591225 => Some(Self::RemoveBlocksBuiltByIDs),
            1969620910 => Some(Self::TransferBlocksBuiltByID),
            -354205189 => Some(Self::BuildBlockSucess),
            1249233947 => Some(Self::BuildBlocksRequest),
            -263130719 => Some(Self::BuildBlocksFailedNotify),
            834026264 => Some(Self::BuildBlocksClient),
            -1946750553 => Some(Self::BuildBlocksAreaRequest),
            -1812935001 => Some(Self::BuildBlocksAreaClient),
            -603394896 => Some(Self::RazeBlocksAreaRequest),
            -1054063648 => Some(Self::RazeBlocksAreaSuccess),
            -1646669051 => Some(Self::RazeBlocksRequest),
            495093934 => Some(Self::RazeBlocksClient),
            1734727161 => Some(Self::ColorGridFriendlyRequest),
            151435633 => Some(Self::OnColorGridFriendly),
            -1362921269 => Some(Self::OnColorGridBlockFailed),
            -602048454 => Some(Self::ColorBlockRequest),
            -404146891 => Some(Self::OnColorBlock),
            -4381308 => Some(Self::SkinGridFriendlyRequest),
            -781634572 => Some(Self::OnSkinGridFriendly),
            -354556542 => Some(Self::SkinBlockRequest),
            -884973083 => Some(Self::OnSkinBlock),
            -487709288 => Some(Self::OnConvertToDynamic),
            -938916014 => Some(Self::ConvertToStatic),
            1631008544 => Some(Self::BlockIntegrityChanged),
            1760065692 => Some(Self::BlockStockpileChanged),
            -1099364648 => Some(Self::PasteBlocksToGridServer_Implementation),
            -743959690 => Some(Self::PasteBlocksToGridClient_Implementation),
            622249059 => Some(Self::StationClosingDenied),
            1028864154 => Some(Self::OnGridClosedRequest),
            -183493786 => Some(Self::OnBonesReceived),
            260096413 => Some(Self::OnBonesMultiplied),
            276084550 => Some(Self::RelfectorStateRecived),
            99995844 => Some(Self::OnStockpileFillRequest),
            -61192616 => Some(Self::OnPowerProducerStateRequest),
            1155167915 => Some(Self::OnConvertedToShipRequest),
            1177176633 => Some(Self::OnConvertToShipFailed),
            1774231477 => Some(Self::OnConvertedToStationRequest),
            -1490620503 => Some(Self::OnChangeOwnerRequest),
            1461916729 => Some(Self::OnChangeOwner),
            -496826902 => Some(Self::ToggleHandbrakeRequest),
            -174639469 => Some(Self::ReceiveHandbrakeRequestResult),
            1173731473 => Some(Self::ToggleParkStateRequest),
            850402221 => Some(Self::ReceiveParkRequestResult),
            -863725756 => Some(Self::OnChangeGridOwner),
            -1058060139 => Some(Self::OnRemoveSplit),
            95137188 => Some(Self::OnChangeDisplayNameRequest),
            739298117 => Some(Self::OnModifyGroupSuccess),
            -79926208 => Some(Self::OnLogHierarchy),
            -603502464 => Some(Self::DepressurizeEffect),
            -1242219506 => Some(Self::InvokeJumpInternal),
            1777655630 => Some(Self::OnAbortJump),
            -1648812944 => Some(Self::OnJumpRequested),
            -442493598 => Some(Self::OnJumpSuccess),
            696694534 => Some(Self::PlayParticleBroadcast),
            -1225717816 => Some(Self::RemoveContainerDropComponent),
            -581775129 => Some(Self::StopSmoke),
            -1982159355 => Some(Self::ContainerOpened),
            -308851915 => Some(Self::CompetetiveContainerOpened),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.MyCubeGrid.
///
/// Use `MyCubeGridInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyCubeGridInstanceEventPayload {
    /// MergeGrid_MergeClient event payload
    MergeGrid_MergeClient(MyCubeGrid_MergeGrid_MergeClientPayload),
    /// MergeGrid_MergeBlockClient event payload
    MergeGrid_MergeBlockClient(MyCubeGrid_MergeGrid_MergeBlockClientPayload),
    /// OnGridChangedRPC event (no payload)
    OnGridChangedRPC,
    /// CreateSplit_Implementation event payload
    CreateSplit_Implementation(MyCubeGrid_CreateSplit_ImplementationPayload),
    /// CreateSplits_Implementation event payload
    CreateSplits_Implementation(MyCubeGrid_CreateSplits_ImplementationPayload),
    /// UpdateTimeOnClients event payload
    UpdateTimeOnClients(MyCubeGrid_UpdateTimeOnClientsPayload),
    /// RemovedBlocks event payload
    RemovedBlocks(MyCubeGrid_RemovedBlocksPayload),
    /// RemovedBlocksWithIds event payload
    RemovedBlocksWithIds(MyCubeGrid_RemovedBlocksWithIdsPayload),
    /// RemoveBlocksBuiltByIDs event payload
    RemoveBlocksBuiltByIDs(MyCubeGrid_RemoveBlocksBuiltByIDsPayload),
    /// TransferBlocksBuiltByID event payload
    TransferBlocksBuiltByID(MyCubeGrid_TransferBlocksBuiltByIDPayload),
    /// BuildBlockSucess event payload
    BuildBlockSucess(MyCubeGrid_BuildBlockSucessPayload),
    /// BuildBlocksRequest event payload
    BuildBlocksRequest(MyCubeGrid_BuildBlocksRequestPayload),
    /// BuildBlocksFailedNotify event (no payload)
    BuildBlocksFailedNotify,
    /// BuildBlocksClient event payload
    BuildBlocksClient(MyCubeGrid_BuildBlocksClientPayload),
    /// BuildBlocksAreaRequest event payload
    BuildBlocksAreaRequest(MyCubeGrid_BuildBlocksAreaRequestPayload),
    /// BuildBlocksAreaClient event payload
    BuildBlocksAreaClient(MyCubeGrid_BuildBlocksAreaClientPayload),
    /// RazeBlocksAreaRequest event payload
    RazeBlocksAreaRequest(MyCubeGrid_RazeBlocksAreaRequestPayload),
    /// RazeBlocksAreaSuccess event payload
    RazeBlocksAreaSuccess(MyCubeGrid_RazeBlocksAreaSuccessPayload),
    /// RazeBlocksRequest event payload
    RazeBlocksRequest(MyCubeGrid_RazeBlocksRequestPayload),
    /// RazeBlocksClient event payload
    RazeBlocksClient(MyCubeGrid_RazeBlocksClientPayload),
    /// ColorGridFriendlyRequest event payload
    ColorGridFriendlyRequest(MyCubeGrid_ColorGridFriendlyRequestPayload),
    /// OnColorGridFriendly event payload
    OnColorGridFriendly(MyCubeGrid_OnColorGridFriendlyPayload),
    /// OnColorGridBlockFailed event (no payload)
    OnColorGridBlockFailed,
    /// ColorBlockRequest event payload
    ColorBlockRequest(MyCubeGrid_ColorBlockRequestPayload),
    /// OnColorBlock event payload
    OnColorBlock(MyCubeGrid_OnColorBlockPayload),
    /// SkinGridFriendlyRequest event payload
    SkinGridFriendlyRequest(MyCubeGrid_SkinGridFriendlyRequestPayload),
    /// OnSkinGridFriendly event payload
    OnSkinGridFriendly(MyCubeGrid_OnSkinGridFriendlyPayload),
    /// SkinBlockRequest event payload
    SkinBlockRequest(MyCubeGrid_SkinBlockRequestPayload),
    /// OnSkinBlock event payload
    OnSkinBlock(MyCubeGrid_OnSkinBlockPayload),
    /// OnConvertToDynamic event (no payload)
    OnConvertToDynamic,
    /// ConvertToStatic event (no payload)
    ConvertToStatic,
    /// BlockIntegrityChanged event payload
    BlockIntegrityChanged(MyCubeGrid_BlockIntegrityChangedPayload),
    /// BlockStockpileChanged event payload
    BlockStockpileChanged(MyCubeGrid_BlockStockpileChangedPayload),
    /// PasteBlocksToGridServer_Implementation event payload
    PasteBlocksToGridServer_Implementation(MyCubeGrid_PasteBlocksToGridServer_ImplementationPayload),
    /// PasteBlocksToGridClient_Implementation event payload
    PasteBlocksToGridClient_Implementation(MyCubeGrid_PasteBlocksToGridClient_ImplementationPayload),
    /// StationClosingDenied event (no payload)
    StationClosingDenied,
    /// OnGridClosedRequest event (no payload)
    OnGridClosedRequest,
    /// OnBonesReceived event payload
    OnBonesReceived(MyCubeGrid_OnBonesReceivedPayload),
    /// OnBonesMultiplied event payload
    OnBonesMultiplied(MyCubeGrid_OnBonesMultipliedPayload),
    /// RelfectorStateRecived event payload
    RelfectorStateRecived(MyCubeGrid_RelfectorStateRecivedPayload),
    /// OnStockpileFillRequest event payload
    OnStockpileFillRequest(MyCubeGrid_OnStockpileFillRequestPayload),
    /// OnPowerProducerStateRequest event payload
    OnPowerProducerStateRequest(MyCubeGrid_OnPowerProducerStateRequestPayload),
    /// OnConvertedToShipRequest event payload
    OnConvertedToShipRequest(MyCubeGrid_OnConvertedToShipRequestPayload),
    /// OnConvertToShipFailed event (no payload)
    OnConvertToShipFailed,
    /// OnConvertedToStationRequest event (no payload)
    OnConvertedToStationRequest,
    /// OnChangeOwnerRequest event payload
    OnChangeOwnerRequest(MyCubeGrid_OnChangeOwnerRequestPayload),
    /// OnChangeOwner event payload
    OnChangeOwner(MyCubeGrid_OnChangeOwnerPayload),
    /// ToggleHandbrakeRequest event (no payload)
    ToggleHandbrakeRequest,
    /// ReceiveHandbrakeRequestResult event payload
    ReceiveHandbrakeRequestResult(MyCubeGrid_ReceiveHandbrakeRequestResultPayload),
    /// ToggleParkStateRequest event (no payload)
    ToggleParkStateRequest,
    /// ReceiveParkRequestResult event payload
    ReceiveParkRequestResult(MyCubeGrid_ReceiveParkRequestResultPayload),
    /// OnChangeGridOwner event payload
    OnChangeGridOwner(MyCubeGrid_OnChangeGridOwnerPayload),
    /// OnRemoveSplit event payload
    OnRemoveSplit(MyCubeGrid_OnRemoveSplitPayload),
    /// OnChangeDisplayNameRequest event payload
    OnChangeDisplayNameRequest(MyCubeGrid_OnChangeDisplayNameRequestPayload),
    /// OnModifyGroupSuccess event payload
    OnModifyGroupSuccess(MyCubeGrid_OnModifyGroupSuccessPayload),
    /// OnLogHierarchy event (no payload)
    OnLogHierarchy,
    /// DepressurizeEffect event payload
    DepressurizeEffect(MyCubeGrid_DepressurizeEffectPayload),
    /// InvokeJumpInternal event payload
    InvokeJumpInternal(MyCubeGrid_InvokeJumpInternalPayload),
    /// OnAbortJump event (no payload)
    OnAbortJump,
    /// OnJumpRequested event payload
    OnJumpRequested(MyCubeGrid_OnJumpRequestedPayload),
    /// OnJumpSuccess event payload
    OnJumpSuccess(MyCubeGrid_OnJumpSuccessPayload),
    /// PlayParticleBroadcast event payload
    PlayParticleBroadcast(MyCubeGrid_PlayParticleBroadcastPayload),
    /// RemoveContainerDropComponent event payload
    RemoveContainerDropComponent(MyCubeGrid_RemoveContainerDropComponentPayload),
    /// StopSmoke event (no payload)
    StopSmoke,
    /// ContainerOpened event payload
    ContainerOpened(MyCubeGrid_ContainerOpenedPayload),
    /// CompetetiveContainerOpened event payload
    CompetetiveContainerOpened(MyCubeGrid_CompetetiveContainerOpenedPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyCubeGridInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyCubeGridInstanceEventPayload, deku::DekuError> {
        match self {
            Self::MergeGrid_MergeClient => {
                let (_, payload) = MyCubeGrid_MergeGrid_MergeClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::MergeGrid_MergeClient(payload))
            }
            Self::MergeGrid_MergeBlockClient => {
                let (_, payload) = MyCubeGrid_MergeGrid_MergeBlockClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::MergeGrid_MergeBlockClient(payload))
            }
            Self::OnGridChangedRPC => Ok(MyCubeGridInstanceEventPayload::OnGridChangedRPC),
            Self::CreateSplit_Implementation => {
                let (_, payload) = MyCubeGrid_CreateSplit_ImplementationPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::CreateSplit_Implementation(payload))
            }
            Self::CreateSplits_Implementation => {
                let (_, payload) = MyCubeGrid_CreateSplits_ImplementationPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::CreateSplits_Implementation(payload))
            }
            Self::UpdateTimeOnClients => {
                let (_, payload) = MyCubeGrid_UpdateTimeOnClientsPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::UpdateTimeOnClients(payload))
            }
            Self::RemovedBlocks => {
                let (_, payload) = MyCubeGrid_RemovedBlocksPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RemovedBlocks(payload))
            }
            Self::RemovedBlocksWithIds => {
                let (_, payload) = MyCubeGrid_RemovedBlocksWithIdsPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RemovedBlocksWithIds(payload))
            }
            Self::RemoveBlocksBuiltByIDs => {
                let (_, payload) = MyCubeGrid_RemoveBlocksBuiltByIDsPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RemoveBlocksBuiltByIDs(payload))
            }
            Self::TransferBlocksBuiltByID => {
                let (_, payload) = MyCubeGrid_TransferBlocksBuiltByIDPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::TransferBlocksBuiltByID(payload))
            }
            Self::BuildBlockSucess => {
                let (_, payload) = MyCubeGrid_BuildBlockSucessPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BuildBlockSucess(payload))
            }
            Self::BuildBlocksRequest => {
                let (_, payload) = MyCubeGrid_BuildBlocksRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BuildBlocksRequest(payload))
            }
            Self::BuildBlocksFailedNotify => Ok(MyCubeGridInstanceEventPayload::BuildBlocksFailedNotify),
            Self::BuildBlocksClient => {
                let (_, payload) = MyCubeGrid_BuildBlocksClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BuildBlocksClient(payload))
            }
            Self::BuildBlocksAreaRequest => {
                let (_, payload) = MyCubeGrid_BuildBlocksAreaRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BuildBlocksAreaRequest(payload))
            }
            Self::BuildBlocksAreaClient => {
                let (_, payload) = MyCubeGrid_BuildBlocksAreaClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BuildBlocksAreaClient(payload))
            }
            Self::RazeBlocksAreaRequest => {
                let (_, payload) = MyCubeGrid_RazeBlocksAreaRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RazeBlocksAreaRequest(payload))
            }
            Self::RazeBlocksAreaSuccess => {
                let (_, payload) = MyCubeGrid_RazeBlocksAreaSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RazeBlocksAreaSuccess(payload))
            }
            Self::RazeBlocksRequest => {
                let (_, payload) = MyCubeGrid_RazeBlocksRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RazeBlocksRequest(payload))
            }
            Self::RazeBlocksClient => {
                let (_, payload) = MyCubeGrid_RazeBlocksClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RazeBlocksClient(payload))
            }
            Self::ColorGridFriendlyRequest => {
                let (_, payload) = MyCubeGrid_ColorGridFriendlyRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::ColorGridFriendlyRequest(payload))
            }
            Self::OnColorGridFriendly => {
                let (_, payload) = MyCubeGrid_OnColorGridFriendlyPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnColorGridFriendly(payload))
            }
            Self::OnColorGridBlockFailed => Ok(MyCubeGridInstanceEventPayload::OnColorGridBlockFailed),
            Self::ColorBlockRequest => {
                let (_, payload) = MyCubeGrid_ColorBlockRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::ColorBlockRequest(payload))
            }
            Self::OnColorBlock => {
                let (_, payload) = MyCubeGrid_OnColorBlockPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnColorBlock(payload))
            }
            Self::SkinGridFriendlyRequest => {
                let (_, payload) = MyCubeGrid_SkinGridFriendlyRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::SkinGridFriendlyRequest(payload))
            }
            Self::OnSkinGridFriendly => {
                let (_, payload) = MyCubeGrid_OnSkinGridFriendlyPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnSkinGridFriendly(payload))
            }
            Self::SkinBlockRequest => {
                let (_, payload) = MyCubeGrid_SkinBlockRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::SkinBlockRequest(payload))
            }
            Self::OnSkinBlock => {
                let (_, payload) = MyCubeGrid_OnSkinBlockPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnSkinBlock(payload))
            }
            Self::OnConvertToDynamic => Ok(MyCubeGridInstanceEventPayload::OnConvertToDynamic),
            Self::ConvertToStatic => Ok(MyCubeGridInstanceEventPayload::ConvertToStatic),
            Self::BlockIntegrityChanged => {
                let (_, payload) = MyCubeGrid_BlockIntegrityChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BlockIntegrityChanged(payload))
            }
            Self::BlockStockpileChanged => {
                let (_, payload) = MyCubeGrid_BlockStockpileChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::BlockStockpileChanged(payload))
            }
            Self::PasteBlocksToGridServer_Implementation => {
                let (_, payload) = MyCubeGrid_PasteBlocksToGridServer_ImplementationPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::PasteBlocksToGridServer_Implementation(payload))
            }
            Self::PasteBlocksToGridClient_Implementation => {
                let (_, payload) = MyCubeGrid_PasteBlocksToGridClient_ImplementationPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::PasteBlocksToGridClient_Implementation(payload))
            }
            Self::StationClosingDenied => Ok(MyCubeGridInstanceEventPayload::StationClosingDenied),
            Self::OnGridClosedRequest => Ok(MyCubeGridInstanceEventPayload::OnGridClosedRequest),
            Self::OnBonesReceived => {
                let (_, payload) = MyCubeGrid_OnBonesReceivedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnBonesReceived(payload))
            }
            Self::OnBonesMultiplied => {
                let (_, payload) = MyCubeGrid_OnBonesMultipliedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnBonesMultiplied(payload))
            }
            Self::RelfectorStateRecived => {
                let (_, payload) = MyCubeGrid_RelfectorStateRecivedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RelfectorStateRecived(payload))
            }
            Self::OnStockpileFillRequest => {
                let (_, payload) = MyCubeGrid_OnStockpileFillRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnStockpileFillRequest(payload))
            }
            Self::OnPowerProducerStateRequest => {
                let (_, payload) = MyCubeGrid_OnPowerProducerStateRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnPowerProducerStateRequest(payload))
            }
            Self::OnConvertedToShipRequest => {
                let (_, payload) = MyCubeGrid_OnConvertedToShipRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnConvertedToShipRequest(payload))
            }
            Self::OnConvertToShipFailed => Ok(MyCubeGridInstanceEventPayload::OnConvertToShipFailed),
            Self::OnConvertedToStationRequest => Ok(MyCubeGridInstanceEventPayload::OnConvertedToStationRequest),
            Self::OnChangeOwnerRequest => {
                let (_, payload) = MyCubeGrid_OnChangeOwnerRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnChangeOwnerRequest(payload))
            }
            Self::OnChangeOwner => {
                let (_, payload) = MyCubeGrid_OnChangeOwnerPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnChangeOwner(payload))
            }
            Self::ToggleHandbrakeRequest => Ok(MyCubeGridInstanceEventPayload::ToggleHandbrakeRequest),
            Self::ReceiveHandbrakeRequestResult => {
                let (_, payload) = MyCubeGrid_ReceiveHandbrakeRequestResultPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::ReceiveHandbrakeRequestResult(payload))
            }
            Self::ToggleParkStateRequest => Ok(MyCubeGridInstanceEventPayload::ToggleParkStateRequest),
            Self::ReceiveParkRequestResult => {
                let (_, payload) = MyCubeGrid_ReceiveParkRequestResultPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::ReceiveParkRequestResult(payload))
            }
            Self::OnChangeGridOwner => {
                let (_, payload) = MyCubeGrid_OnChangeGridOwnerPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnChangeGridOwner(payload))
            }
            Self::OnRemoveSplit => {
                let (_, payload) = MyCubeGrid_OnRemoveSplitPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnRemoveSplit(payload))
            }
            Self::OnChangeDisplayNameRequest => {
                let (_, payload) = MyCubeGrid_OnChangeDisplayNameRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnChangeDisplayNameRequest(payload))
            }
            Self::OnModifyGroupSuccess => {
                let (_, payload) = MyCubeGrid_OnModifyGroupSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnModifyGroupSuccess(payload))
            }
            Self::OnLogHierarchy => Ok(MyCubeGridInstanceEventPayload::OnLogHierarchy),
            Self::DepressurizeEffect => {
                let (_, payload) = MyCubeGrid_DepressurizeEffectPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::DepressurizeEffect(payload))
            }
            Self::InvokeJumpInternal => {
                let (_, payload) = MyCubeGrid_InvokeJumpInternalPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::InvokeJumpInternal(payload))
            }
            Self::OnAbortJump => Ok(MyCubeGridInstanceEventPayload::OnAbortJump),
            Self::OnJumpRequested => {
                let (_, payload) = MyCubeGrid_OnJumpRequestedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnJumpRequested(payload))
            }
            Self::OnJumpSuccess => {
                let (_, payload) = MyCubeGrid_OnJumpSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::OnJumpSuccess(payload))
            }
            Self::PlayParticleBroadcast => {
                let (_, payload) = MyCubeGrid_PlayParticleBroadcastPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::PlayParticleBroadcast(payload))
            }
            Self::RemoveContainerDropComponent => {
                let (_, payload) = MyCubeGrid_RemoveContainerDropComponentPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::RemoveContainerDropComponent(payload))
            }
            Self::StopSmoke => Ok(MyCubeGridInstanceEventPayload::StopSmoke),
            Self::ContainerOpened => {
                let (_, payload) = MyCubeGrid_ContainerOpenedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::ContainerOpened(payload))
            }
            Self::CompetetiveContainerOpened => {
                let (_, payload) = MyCubeGrid_CompetetiveContainerOpenedPayload::from_bytes((bytes, 0))?;
                Ok(MyCubeGridInstanceEventPayload::CompetetiveContainerOpened(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyCubeGrid from raw event hash and bytes.
pub fn parse_my_cube_grid_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyCubeGridInstanceEventPayload, deku::DekuError> {
    match MyCubeGridInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyCubeGridInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyCubeGrid instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyCubeGridInstanceEventVisitor {
    /// Called when visiting MergeGrid_MergeClient event.
    fn visit_merge_grid_merge_client(&mut self, payload: &MyCubeGrid_MergeGrid_MergeClientPayload) {}
    /// Called when visiting MergeGrid_MergeBlockClient event.
    fn visit_merge_grid_merge_block_client(&mut self, payload: &MyCubeGrid_MergeGrid_MergeBlockClientPayload) {}
    /// Called when visiting OnGridChangedRPC event (no payload).
    fn visit_on_grid_changed_rpc(&mut self) {}
    /// Called when visiting CreateSplit_Implementation event.
    fn visit_create_split_implementation(&mut self, payload: &MyCubeGrid_CreateSplit_ImplementationPayload) {}
    /// Called when visiting CreateSplits_Implementation event.
    fn visit_create_splits_implementation(&mut self, payload: &MyCubeGrid_CreateSplits_ImplementationPayload) {}
    /// Called when visiting UpdateTimeOnClients event.
    fn visit_update_time_on_clients(&mut self, payload: &MyCubeGrid_UpdateTimeOnClientsPayload) {}
    /// Called when visiting RemovedBlocks event.
    fn visit_removed_blocks(&mut self, payload: &MyCubeGrid_RemovedBlocksPayload) {}
    /// Called when visiting RemovedBlocksWithIds event.
    fn visit_removed_blocks_with_ids(&mut self, payload: &MyCubeGrid_RemovedBlocksWithIdsPayload) {}
    /// Called when visiting RemoveBlocksBuiltByIDs event.
    fn visit_remove_blocks_built_by_ids(&mut self, payload: &MyCubeGrid_RemoveBlocksBuiltByIDsPayload) {}
    /// Called when visiting TransferBlocksBuiltByID event.
    fn visit_transfer_blocks_built_by_id(&mut self, payload: &MyCubeGrid_TransferBlocksBuiltByIDPayload) {}
    /// Called when visiting BuildBlockSucess event.
    fn visit_build_block_sucess(&mut self, payload: &MyCubeGrid_BuildBlockSucessPayload) {}
    /// Called when visiting BuildBlocksRequest event.
    fn visit_build_blocks_request(&mut self, payload: &MyCubeGrid_BuildBlocksRequestPayload) {}
    /// Called when visiting BuildBlocksFailedNotify event (no payload).
    fn visit_build_blocks_failed_notify(&mut self) {}
    /// Called when visiting BuildBlocksClient event.
    fn visit_build_blocks_client(&mut self, payload: &MyCubeGrid_BuildBlocksClientPayload) {}
    /// Called when visiting BuildBlocksAreaRequest event.
    fn visit_build_blocks_area_request(&mut self, payload: &MyCubeGrid_BuildBlocksAreaRequestPayload) {}
    /// Called when visiting BuildBlocksAreaClient event.
    fn visit_build_blocks_area_client(&mut self, payload: &MyCubeGrid_BuildBlocksAreaClientPayload) {}
    /// Called when visiting RazeBlocksAreaRequest event.
    fn visit_raze_blocks_area_request(&mut self, payload: &MyCubeGrid_RazeBlocksAreaRequestPayload) {}
    /// Called when visiting RazeBlocksAreaSuccess event.
    fn visit_raze_blocks_area_success(&mut self, payload: &MyCubeGrid_RazeBlocksAreaSuccessPayload) {}
    /// Called when visiting RazeBlocksRequest event.
    fn visit_raze_blocks_request(&mut self, payload: &MyCubeGrid_RazeBlocksRequestPayload) {}
    /// Called when visiting RazeBlocksClient event.
    fn visit_raze_blocks_client(&mut self, payload: &MyCubeGrid_RazeBlocksClientPayload) {}
    /// Called when visiting ColorGridFriendlyRequest event.
    fn visit_color_grid_friendly_request(&mut self, payload: &MyCubeGrid_ColorGridFriendlyRequestPayload) {}
    /// Called when visiting OnColorGridFriendly event.
    fn visit_on_color_grid_friendly(&mut self, payload: &MyCubeGrid_OnColorGridFriendlyPayload) {}
    /// Called when visiting OnColorGridBlockFailed event (no payload).
    fn visit_on_color_grid_block_failed(&mut self) {}
    /// Called when visiting ColorBlockRequest event.
    fn visit_color_block_request(&mut self, payload: &MyCubeGrid_ColorBlockRequestPayload) {}
    /// Called when visiting OnColorBlock event.
    fn visit_on_color_block(&mut self, payload: &MyCubeGrid_OnColorBlockPayload) {}
    /// Called when visiting SkinGridFriendlyRequest event.
    fn visit_skin_grid_friendly_request(&mut self, payload: &MyCubeGrid_SkinGridFriendlyRequestPayload) {}
    /// Called when visiting OnSkinGridFriendly event.
    fn visit_on_skin_grid_friendly(&mut self, payload: &MyCubeGrid_OnSkinGridFriendlyPayload) {}
    /// Called when visiting SkinBlockRequest event.
    fn visit_skin_block_request(&mut self, payload: &MyCubeGrid_SkinBlockRequestPayload) {}
    /// Called when visiting OnSkinBlock event.
    fn visit_on_skin_block(&mut self, payload: &MyCubeGrid_OnSkinBlockPayload) {}
    /// Called when visiting OnConvertToDynamic event (no payload).
    fn visit_on_convert_to_dynamic(&mut self) {}
    /// Called when visiting ConvertToStatic event (no payload).
    fn visit_convert_to_static(&mut self) {}
    /// Called when visiting BlockIntegrityChanged event.
    fn visit_block_integrity_changed(&mut self, payload: &MyCubeGrid_BlockIntegrityChangedPayload) {}
    /// Called when visiting BlockStockpileChanged event.
    fn visit_block_stockpile_changed(&mut self, payload: &MyCubeGrid_BlockStockpileChangedPayload) {}
    /// Called when visiting PasteBlocksToGridServer_Implementation event.
    fn visit_paste_blocks_to_grid_server_implementation(&mut self, payload: &MyCubeGrid_PasteBlocksToGridServer_ImplementationPayload) {}
    /// Called when visiting PasteBlocksToGridClient_Implementation event.
    fn visit_paste_blocks_to_grid_client_implementation(&mut self, payload: &MyCubeGrid_PasteBlocksToGridClient_ImplementationPayload) {}
    /// Called when visiting StationClosingDenied event (no payload).
    fn visit_station_closing_denied(&mut self) {}
    /// Called when visiting OnGridClosedRequest event (no payload).
    fn visit_on_grid_closed_request(&mut self) {}
    /// Called when visiting OnBonesReceived event.
    fn visit_on_bones_received(&mut self, payload: &MyCubeGrid_OnBonesReceivedPayload) {}
    /// Called when visiting OnBonesMultiplied event.
    fn visit_on_bones_multiplied(&mut self, payload: &MyCubeGrid_OnBonesMultipliedPayload) {}
    /// Called when visiting RelfectorStateRecived event.
    fn visit_relfector_state_recived(&mut self, payload: &MyCubeGrid_RelfectorStateRecivedPayload) {}
    /// Called when visiting OnStockpileFillRequest event.
    fn visit_on_stockpile_fill_request(&mut self, payload: &MyCubeGrid_OnStockpileFillRequestPayload) {}
    /// Called when visiting OnPowerProducerStateRequest event.
    fn visit_on_power_producer_state_request(&mut self, payload: &MyCubeGrid_OnPowerProducerStateRequestPayload) {}
    /// Called when visiting OnConvertedToShipRequest event.
    fn visit_on_converted_to_ship_request(&mut self, payload: &MyCubeGrid_OnConvertedToShipRequestPayload) {}
    /// Called when visiting OnConvertToShipFailed event (no payload).
    fn visit_on_convert_to_ship_failed(&mut self) {}
    /// Called when visiting OnConvertedToStationRequest event (no payload).
    fn visit_on_converted_to_station_request(&mut self) {}
    /// Called when visiting OnChangeOwnerRequest event.
    fn visit_on_change_owner_request(&mut self, payload: &MyCubeGrid_OnChangeOwnerRequestPayload) {}
    /// Called when visiting OnChangeOwner event.
    fn visit_on_change_owner(&mut self, payload: &MyCubeGrid_OnChangeOwnerPayload) {}
    /// Called when visiting ToggleHandbrakeRequest event (no payload).
    fn visit_toggle_handbrake_request(&mut self) {}
    /// Called when visiting ReceiveHandbrakeRequestResult event.
    fn visit_receive_handbrake_request_result(&mut self, payload: &MyCubeGrid_ReceiveHandbrakeRequestResultPayload) {}
    /// Called when visiting ToggleParkStateRequest event (no payload).
    fn visit_toggle_park_state_request(&mut self) {}
    /// Called when visiting ReceiveParkRequestResult event.
    fn visit_receive_park_request_result(&mut self, payload: &MyCubeGrid_ReceiveParkRequestResultPayload) {}
    /// Called when visiting OnChangeGridOwner event.
    fn visit_on_change_grid_owner(&mut self, payload: &MyCubeGrid_OnChangeGridOwnerPayload) {}
    /// Called when visiting OnRemoveSplit event.
    fn visit_on_remove_split(&mut self, payload: &MyCubeGrid_OnRemoveSplitPayload) {}
    /// Called when visiting OnChangeDisplayNameRequest event.
    fn visit_on_change_display_name_request(&mut self, payload: &MyCubeGrid_OnChangeDisplayNameRequestPayload) {}
    /// Called when visiting OnModifyGroupSuccess event.
    fn visit_on_modify_group_success(&mut self, payload: &MyCubeGrid_OnModifyGroupSuccessPayload) {}
    /// Called when visiting OnLogHierarchy event (no payload).
    fn visit_on_log_hierarchy(&mut self) {}
    /// Called when visiting DepressurizeEffect event.
    fn visit_depressurize_effect(&mut self, payload: &MyCubeGrid_DepressurizeEffectPayload) {}
    /// Called when visiting InvokeJumpInternal event.
    fn visit_invoke_jump_internal(&mut self, payload: &MyCubeGrid_InvokeJumpInternalPayload) {}
    /// Called when visiting OnAbortJump event (no payload).
    fn visit_on_abort_jump(&mut self) {}
    /// Called when visiting OnJumpRequested event.
    fn visit_on_jump_requested(&mut self, payload: &MyCubeGrid_OnJumpRequestedPayload) {}
    /// Called when visiting OnJumpSuccess event.
    fn visit_on_jump_success(&mut self, payload: &MyCubeGrid_OnJumpSuccessPayload) {}
    /// Called when visiting PlayParticleBroadcast event.
    fn visit_play_particle_broadcast(&mut self, payload: &MyCubeGrid_PlayParticleBroadcastPayload) {}
    /// Called when visiting RemoveContainerDropComponent event.
    fn visit_remove_container_drop_component(&mut self, payload: &MyCubeGrid_RemoveContainerDropComponentPayload) {}
    /// Called when visiting StopSmoke event (no payload).
    fn visit_stop_smoke(&mut self) {}
    /// Called when visiting ContainerOpened event.
    fn visit_container_opened(&mut self, payload: &MyCubeGrid_ContainerOpenedPayload) {}
    /// Called when visiting CompetetiveContainerOpened event.
    fn visit_competetive_container_opened(&mut self, payload: &MyCubeGrid_CompetetiveContainerOpenedPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyCubeGridInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyCubeGridInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::MergeGrid_MergeClient(payload) => visitor.visit_merge_grid_merge_client(payload),
            Self::MergeGrid_MergeBlockClient(payload) => visitor.visit_merge_grid_merge_block_client(payload),
            Self::OnGridChangedRPC => visitor.visit_on_grid_changed_rpc(),
            Self::CreateSplit_Implementation(payload) => visitor.visit_create_split_implementation(payload),
            Self::CreateSplits_Implementation(payload) => visitor.visit_create_splits_implementation(payload),
            Self::UpdateTimeOnClients(payload) => visitor.visit_update_time_on_clients(payload),
            Self::RemovedBlocks(payload) => visitor.visit_removed_blocks(payload),
            Self::RemovedBlocksWithIds(payload) => visitor.visit_removed_blocks_with_ids(payload),
            Self::RemoveBlocksBuiltByIDs(payload) => visitor.visit_remove_blocks_built_by_ids(payload),
            Self::TransferBlocksBuiltByID(payload) => visitor.visit_transfer_blocks_built_by_id(payload),
            Self::BuildBlockSucess(payload) => visitor.visit_build_block_sucess(payload),
            Self::BuildBlocksRequest(payload) => visitor.visit_build_blocks_request(payload),
            Self::BuildBlocksFailedNotify => visitor.visit_build_blocks_failed_notify(),
            Self::BuildBlocksClient(payload) => visitor.visit_build_blocks_client(payload),
            Self::BuildBlocksAreaRequest(payload) => visitor.visit_build_blocks_area_request(payload),
            Self::BuildBlocksAreaClient(payload) => visitor.visit_build_blocks_area_client(payload),
            Self::RazeBlocksAreaRequest(payload) => visitor.visit_raze_blocks_area_request(payload),
            Self::RazeBlocksAreaSuccess(payload) => visitor.visit_raze_blocks_area_success(payload),
            Self::RazeBlocksRequest(payload) => visitor.visit_raze_blocks_request(payload),
            Self::RazeBlocksClient(payload) => visitor.visit_raze_blocks_client(payload),
            Self::ColorGridFriendlyRequest(payload) => visitor.visit_color_grid_friendly_request(payload),
            Self::OnColorGridFriendly(payload) => visitor.visit_on_color_grid_friendly(payload),
            Self::OnColorGridBlockFailed => visitor.visit_on_color_grid_block_failed(),
            Self::ColorBlockRequest(payload) => visitor.visit_color_block_request(payload),
            Self::OnColorBlock(payload) => visitor.visit_on_color_block(payload),
            Self::SkinGridFriendlyRequest(payload) => visitor.visit_skin_grid_friendly_request(payload),
            Self::OnSkinGridFriendly(payload) => visitor.visit_on_skin_grid_friendly(payload),
            Self::SkinBlockRequest(payload) => visitor.visit_skin_block_request(payload),
            Self::OnSkinBlock(payload) => visitor.visit_on_skin_block(payload),
            Self::OnConvertToDynamic => visitor.visit_on_convert_to_dynamic(),
            Self::ConvertToStatic => visitor.visit_convert_to_static(),
            Self::BlockIntegrityChanged(payload) => visitor.visit_block_integrity_changed(payload),
            Self::BlockStockpileChanged(payload) => visitor.visit_block_stockpile_changed(payload),
            Self::PasteBlocksToGridServer_Implementation(payload) => visitor.visit_paste_blocks_to_grid_server_implementation(payload),
            Self::PasteBlocksToGridClient_Implementation(payload) => visitor.visit_paste_blocks_to_grid_client_implementation(payload),
            Self::StationClosingDenied => visitor.visit_station_closing_denied(),
            Self::OnGridClosedRequest => visitor.visit_on_grid_closed_request(),
            Self::OnBonesReceived(payload) => visitor.visit_on_bones_received(payload),
            Self::OnBonesMultiplied(payload) => visitor.visit_on_bones_multiplied(payload),
            Self::RelfectorStateRecived(payload) => visitor.visit_relfector_state_recived(payload),
            Self::OnStockpileFillRequest(payload) => visitor.visit_on_stockpile_fill_request(payload),
            Self::OnPowerProducerStateRequest(payload) => visitor.visit_on_power_producer_state_request(payload),
            Self::OnConvertedToShipRequest(payload) => visitor.visit_on_converted_to_ship_request(payload),
            Self::OnConvertToShipFailed => visitor.visit_on_convert_to_ship_failed(),
            Self::OnConvertedToStationRequest => visitor.visit_on_converted_to_station_request(),
            Self::OnChangeOwnerRequest(payload) => visitor.visit_on_change_owner_request(payload),
            Self::OnChangeOwner(payload) => visitor.visit_on_change_owner(payload),
            Self::ToggleHandbrakeRequest => visitor.visit_toggle_handbrake_request(),
            Self::ReceiveHandbrakeRequestResult(payload) => visitor.visit_receive_handbrake_request_result(payload),
            Self::ToggleParkStateRequest => visitor.visit_toggle_park_state_request(),
            Self::ReceiveParkRequestResult(payload) => visitor.visit_receive_park_request_result(payload),
            Self::OnChangeGridOwner(payload) => visitor.visit_on_change_grid_owner(payload),
            Self::OnRemoveSplit(payload) => visitor.visit_on_remove_split(payload),
            Self::OnChangeDisplayNameRequest(payload) => visitor.visit_on_change_display_name_request(payload),
            Self::OnModifyGroupSuccess(payload) => visitor.visit_on_modify_group_success(payload),
            Self::OnLogHierarchy => visitor.visit_on_log_hierarchy(),
            Self::DepressurizeEffect(payload) => visitor.visit_depressurize_effect(payload),
            Self::InvokeJumpInternal(payload) => visitor.visit_invoke_jump_internal(payload),
            Self::OnAbortJump => visitor.visit_on_abort_jump(),
            Self::OnJumpRequested(payload) => visitor.visit_on_jump_requested(payload),
            Self::OnJumpSuccess(payload) => visitor.visit_on_jump_success(payload),
            Self::PlayParticleBroadcast(payload) => visitor.visit_play_particle_broadcast(payload),
            Self::RemoveContainerDropComponent(payload) => visitor.visit_remove_container_drop_component(payload),
            Self::StopSmoke => visitor.visit_stop_smoke(),
            Self::ContainerOpened(payload) => visitor.visit_container_opened(payload),
            Self::CompetetiveContainerOpened(payload) => visitor.visit_competetive_container_opened(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyCubeGridInstanceEvent> {
        match self {
            Self::MergeGrid_MergeClient(_) => Some(MyCubeGridInstanceEvent::MergeGrid_MergeClient),
            Self::MergeGrid_MergeBlockClient(_) => Some(MyCubeGridInstanceEvent::MergeGrid_MergeBlockClient),
            Self::OnGridChangedRPC => Some(MyCubeGridInstanceEvent::OnGridChangedRPC),
            Self::CreateSplit_Implementation(_) => Some(MyCubeGridInstanceEvent::CreateSplit_Implementation),
            Self::CreateSplits_Implementation(_) => Some(MyCubeGridInstanceEvent::CreateSplits_Implementation),
            Self::UpdateTimeOnClients(_) => Some(MyCubeGridInstanceEvent::UpdateTimeOnClients),
            Self::RemovedBlocks(_) => Some(MyCubeGridInstanceEvent::RemovedBlocks),
            Self::RemovedBlocksWithIds(_) => Some(MyCubeGridInstanceEvent::RemovedBlocksWithIds),
            Self::RemoveBlocksBuiltByIDs(_) => Some(MyCubeGridInstanceEvent::RemoveBlocksBuiltByIDs),
            Self::TransferBlocksBuiltByID(_) => Some(MyCubeGridInstanceEvent::TransferBlocksBuiltByID),
            Self::BuildBlockSucess(_) => Some(MyCubeGridInstanceEvent::BuildBlockSucess),
            Self::BuildBlocksRequest(_) => Some(MyCubeGridInstanceEvent::BuildBlocksRequest),
            Self::BuildBlocksFailedNotify => Some(MyCubeGridInstanceEvent::BuildBlocksFailedNotify),
            Self::BuildBlocksClient(_) => Some(MyCubeGridInstanceEvent::BuildBlocksClient),
            Self::BuildBlocksAreaRequest(_) => Some(MyCubeGridInstanceEvent::BuildBlocksAreaRequest),
            Self::BuildBlocksAreaClient(_) => Some(MyCubeGridInstanceEvent::BuildBlocksAreaClient),
            Self::RazeBlocksAreaRequest(_) => Some(MyCubeGridInstanceEvent::RazeBlocksAreaRequest),
            Self::RazeBlocksAreaSuccess(_) => Some(MyCubeGridInstanceEvent::RazeBlocksAreaSuccess),
            Self::RazeBlocksRequest(_) => Some(MyCubeGridInstanceEvent::RazeBlocksRequest),
            Self::RazeBlocksClient(_) => Some(MyCubeGridInstanceEvent::RazeBlocksClient),
            Self::ColorGridFriendlyRequest(_) => Some(MyCubeGridInstanceEvent::ColorGridFriendlyRequest),
            Self::OnColorGridFriendly(_) => Some(MyCubeGridInstanceEvent::OnColorGridFriendly),
            Self::OnColorGridBlockFailed => Some(MyCubeGridInstanceEvent::OnColorGridBlockFailed),
            Self::ColorBlockRequest(_) => Some(MyCubeGridInstanceEvent::ColorBlockRequest),
            Self::OnColorBlock(_) => Some(MyCubeGridInstanceEvent::OnColorBlock),
            Self::SkinGridFriendlyRequest(_) => Some(MyCubeGridInstanceEvent::SkinGridFriendlyRequest),
            Self::OnSkinGridFriendly(_) => Some(MyCubeGridInstanceEvent::OnSkinGridFriendly),
            Self::SkinBlockRequest(_) => Some(MyCubeGridInstanceEvent::SkinBlockRequest),
            Self::OnSkinBlock(_) => Some(MyCubeGridInstanceEvent::OnSkinBlock),
            Self::OnConvertToDynamic => Some(MyCubeGridInstanceEvent::OnConvertToDynamic),
            Self::ConvertToStatic => Some(MyCubeGridInstanceEvent::ConvertToStatic),
            Self::BlockIntegrityChanged(_) => Some(MyCubeGridInstanceEvent::BlockIntegrityChanged),
            Self::BlockStockpileChanged(_) => Some(MyCubeGridInstanceEvent::BlockStockpileChanged),
            Self::PasteBlocksToGridServer_Implementation(_) => Some(MyCubeGridInstanceEvent::PasteBlocksToGridServer_Implementation),
            Self::PasteBlocksToGridClient_Implementation(_) => Some(MyCubeGridInstanceEvent::PasteBlocksToGridClient_Implementation),
            Self::StationClosingDenied => Some(MyCubeGridInstanceEvent::StationClosingDenied),
            Self::OnGridClosedRequest => Some(MyCubeGridInstanceEvent::OnGridClosedRequest),
            Self::OnBonesReceived(_) => Some(MyCubeGridInstanceEvent::OnBonesReceived),
            Self::OnBonesMultiplied(_) => Some(MyCubeGridInstanceEvent::OnBonesMultiplied),
            Self::RelfectorStateRecived(_) => Some(MyCubeGridInstanceEvent::RelfectorStateRecived),
            Self::OnStockpileFillRequest(_) => Some(MyCubeGridInstanceEvent::OnStockpileFillRequest),
            Self::OnPowerProducerStateRequest(_) => Some(MyCubeGridInstanceEvent::OnPowerProducerStateRequest),
            Self::OnConvertedToShipRequest(_) => Some(MyCubeGridInstanceEvent::OnConvertedToShipRequest),
            Self::OnConvertToShipFailed => Some(MyCubeGridInstanceEvent::OnConvertToShipFailed),
            Self::OnConvertedToStationRequest => Some(MyCubeGridInstanceEvent::OnConvertedToStationRequest),
            Self::OnChangeOwnerRequest(_) => Some(MyCubeGridInstanceEvent::OnChangeOwnerRequest),
            Self::OnChangeOwner(_) => Some(MyCubeGridInstanceEvent::OnChangeOwner),
            Self::ToggleHandbrakeRequest => Some(MyCubeGridInstanceEvent::ToggleHandbrakeRequest),
            Self::ReceiveHandbrakeRequestResult(_) => Some(MyCubeGridInstanceEvent::ReceiveHandbrakeRequestResult),
            Self::ToggleParkStateRequest => Some(MyCubeGridInstanceEvent::ToggleParkStateRequest),
            Self::ReceiveParkRequestResult(_) => Some(MyCubeGridInstanceEvent::ReceiveParkRequestResult),
            Self::OnChangeGridOwner(_) => Some(MyCubeGridInstanceEvent::OnChangeGridOwner),
            Self::OnRemoveSplit(_) => Some(MyCubeGridInstanceEvent::OnRemoveSplit),
            Self::OnChangeDisplayNameRequest(_) => Some(MyCubeGridInstanceEvent::OnChangeDisplayNameRequest),
            Self::OnModifyGroupSuccess(_) => Some(MyCubeGridInstanceEvent::OnModifyGroupSuccess),
            Self::OnLogHierarchy => Some(MyCubeGridInstanceEvent::OnLogHierarchy),
            Self::DepressurizeEffect(_) => Some(MyCubeGridInstanceEvent::DepressurizeEffect),
            Self::InvokeJumpInternal(_) => Some(MyCubeGridInstanceEvent::InvokeJumpInternal),
            Self::OnAbortJump => Some(MyCubeGridInstanceEvent::OnAbortJump),
            Self::OnJumpRequested(_) => Some(MyCubeGridInstanceEvent::OnJumpRequested),
            Self::OnJumpSuccess(_) => Some(MyCubeGridInstanceEvent::OnJumpSuccess),
            Self::PlayParticleBroadcast(_) => Some(MyCubeGridInstanceEvent::PlayParticleBroadcast),
            Self::RemoveContainerDropComponent(_) => Some(MyCubeGridInstanceEvent::RemoveContainerDropComponent),
            Self::StopSmoke => Some(MyCubeGridInstanceEvent::StopSmoke),
            Self::ContainerOpened(_) => Some(MyCubeGridInstanceEvent::ContainerOpened),
            Self::CompetetiveContainerOpened(_) => Some(MyCubeGridInstanceEvent::CompetetiveContainerOpened),
            Self::Unknown { .. } => None,
        }
    }
}
