//! Instance events for Sandbox.Game.Entities.MyCockpit.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyCockpit::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyCockpit::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyCockpit::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyCockpit::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyCockpit::SyncMoveIndicator instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SyncMoveIndicatorPayload {
    pub move_indicator: Vector3F,
}

/// Payload for MyCockpit::SwitchToWeaponMessage instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SwitchToWeaponMessagePayload {
    pub weapon: Nullable<space_engineers_sys::types::SerializableDefinitionId>,
    pub weapon_object_builder: space_engineers_sys::types::MyObjectBuilder_EntityBase,
    pub weapon_entity_id: BitAligned<i64>,
}

/// Payload for MyCockpit::OnSwitchToWeaponFailure instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnSwitchToWeaponFailurePayload {
    pub weapon: Nullable<space_engineers_sys::types::SerializableDefinitionId>,
    pub weapon_object_builder: space_engineers_sys::types::MyObjectBuilder_EntityBase,
    pub weapon_entity_id: BitAligned<i64>,
}

/// Payload for MyCockpit::OnSwitchToWeaponSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnSwitchToWeaponSuccessPayload {
    pub weapon: Nullable<space_engineers_sys::types::SerializableDefinitionId>,
    pub weapon_object_builder: space_engineers_sys::types::MyObjectBuilder_EntityBase,
    pub weapon_entity_id: BitAligned<i64>,
}

/// Payload for MyCockpit::ShootBeginCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_ShootBeginCallbackPayload {
    pub action: space_engineers_sys::types::MyShootActionEnum,
}

/// Payload for MyCockpit::ShootEndCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_ShootEndCallbackPayload {
    pub action: space_engineers_sys::types::MyShootActionEnum,
}

/// Payload for MyCockpit::SendToolbarItemRemoved instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SendToolbarItemRemovedPayload {
    pub index: BitAligned<i32>,
    pub is_gamepad: BitBool,
    pub toolbar_index: BitAligned<i32>,
}

/// Payload for MyCockpit::SendToolbarItemChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SendToolbarItemChangedPayload {
    pub sent_item: space_engineers_sys::types::MyObjectBuilder_ToolbarItem,
    pub index: BitAligned<i32>,
    pub is_gamepad: BitBool,
    pub toolbar_index: BitAligned<i32>,
}

/// Payload for MyCockpit::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyCockpit::OnChangeOpenRequest_18 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnChangeOpenRequest_18Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyCockpit::OnChangeOpenSuccess_19 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnChangeOpenSuccess_19Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyCockpit::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
}

/// Payload for MyCockpit::AttachPilotEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_AttachPilotEventPayload {
    pub action_enum: space_engineers_compat::BitField<space_engineers_sys::types::UseActionEnum>,
    pub character_id: BitAligned<i64>,
    pub animation: BitAligned<i32>,
}

/// Payload for MyCockpit::SetAutopilot_Client instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SetAutopilot_ClientPayload {
    pub autopilot: space_engineers_sys::types::MyObjectBuilder_AutopilotBase,
}

/// Payload for MyCockpit::NotifyClientPilotChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_NotifyClientPilotChangedPayload {
    pub pilot_entity_id: BitAligned<i64>,
    pub pilot_relative_world: Nullable<space_engineers_sys::types::Matrix>,
    pub seed: BitAligned<i32>,
}

/// Payload for MyCockpit::SyncHeadOffsetToServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyCockpit_SyncHeadOffsetToServerPayload {
    pub offset: Vector3F,
}

/// Stable instance event identities for Sandbox.Game.Entities.MyCockpit.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyCockpitInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 1321451312
    SyncMoveIndicator,
    /// Hash: -1683711406
    sync_ControlledEntity_Used,
    /// Hash: -66260535
    OnSwitchHelmet,
    /// Hash: -1768488079
    SwitchToWeaponMessage,
    /// Hash: 1764761355
    OnSwitchToWeaponFailure,
    /// Hash: 516373990
    OnSwitchToWeaponSuccess,
    /// Hash: 299738882
    OnSwitchAmmoMagazineRequest,
    /// Hash: 425962628
    OnSwitchAmmoMagazineSuccess,
    /// Hash: 1984244588
    ShootBeginCallback,
    /// Hash: -1861716540
    ShootEndCallback,
    /// Hash: -1414436781
    SendToolbarItemRemoved,
    /// Hash: -1402487407
    SendToolbarItemChanged,
    /// Hash: 1993740115
    SelectPanelServer,
    /// Hash: 39147070
    OnChangeOpenRequest_18,
    /// Hash: -1232498120
    OnChangeOpenSuccess_19,
    /// Hash: -1371193045
    OnChangeDescription,
    /// Hash: 249686699
    OnRequestRemovePilot,
    /// Hash: 910305643
    AttachPilotEvent,
    /// Hash: 1089119382
    SetAutopilot_Client,
    /// Hash: -1540021254
    NotifyClientPilotChanged,
    /// Hash: -988089109
    SyncHeadOffsetToServer,
    /// Hash: -307867555
    RequestClientSeatedAnimationHeadOffset,
}

impl MyCockpitInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::SyncMoveIndicator => 1321451312,
            Self::sync_ControlledEntity_Used => -1683711406,
            Self::OnSwitchHelmet => -66260535,
            Self::SwitchToWeaponMessage => -1768488079,
            Self::OnSwitchToWeaponFailure => 1764761355,
            Self::OnSwitchToWeaponSuccess => 516373990,
            Self::OnSwitchAmmoMagazineRequest => 299738882,
            Self::OnSwitchAmmoMagazineSuccess => 425962628,
            Self::ShootBeginCallback => 1984244588,
            Self::ShootEndCallback => -1861716540,
            Self::SendToolbarItemRemoved => -1414436781,
            Self::SendToolbarItemChanged => -1402487407,
            Self::SelectPanelServer => 1993740115,
            Self::OnChangeOpenRequest_18 => 39147070,
            Self::OnChangeOpenSuccess_19 => -1232498120,
            Self::OnChangeDescription => -1371193045,
            Self::OnRequestRemovePilot => 249686699,
            Self::AttachPilotEvent => 910305643,
            Self::SetAutopilot_Client => 1089119382,
            Self::NotifyClientPilotChanged => -1540021254,
            Self::SyncHeadOffsetToServer => -988089109,
            Self::RequestClientSeatedAnimationHeadOffset => -307867555,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            1321451312 => Some(Self::SyncMoveIndicator),
            -1683711406 => Some(Self::sync_ControlledEntity_Used),
            -66260535 => Some(Self::OnSwitchHelmet),
            -1768488079 => Some(Self::SwitchToWeaponMessage),
            1764761355 => Some(Self::OnSwitchToWeaponFailure),
            516373990 => Some(Self::OnSwitchToWeaponSuccess),
            299738882 => Some(Self::OnSwitchAmmoMagazineRequest),
            425962628 => Some(Self::OnSwitchAmmoMagazineSuccess),
            1984244588 => Some(Self::ShootBeginCallback),
            -1861716540 => Some(Self::ShootEndCallback),
            -1414436781 => Some(Self::SendToolbarItemRemoved),
            -1402487407 => Some(Self::SendToolbarItemChanged),
            1993740115 => Some(Self::SelectPanelServer),
            39147070 => Some(Self::OnChangeOpenRequest_18),
            -1232498120 => Some(Self::OnChangeOpenSuccess_19),
            -1371193045 => Some(Self::OnChangeDescription),
            249686699 => Some(Self::OnRequestRemovePilot),
            910305643 => Some(Self::AttachPilotEvent),
            1089119382 => Some(Self::SetAutopilot_Client),
            -1540021254 => Some(Self::NotifyClientPilotChanged),
            -988089109 => Some(Self::SyncHeadOffsetToServer),
            -307867555 => Some(Self::RequestClientSeatedAnimationHeadOffset),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.MyCockpit.
///
/// Use `MyCockpitInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyCockpitInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyCockpit_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyCockpit_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyCockpit_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyCockpit_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// SyncMoveIndicator event payload
    SyncMoveIndicator(MyCockpit_SyncMoveIndicatorPayload),
    /// sync_ControlledEntity_Used event (no payload)
    sync_ControlledEntity_Used,
    /// OnSwitchHelmet event (no payload)
    OnSwitchHelmet,
    /// SwitchToWeaponMessage event payload
    SwitchToWeaponMessage(MyCockpit_SwitchToWeaponMessagePayload),
    /// OnSwitchToWeaponFailure event payload
    OnSwitchToWeaponFailure(MyCockpit_OnSwitchToWeaponFailurePayload),
    /// OnSwitchToWeaponSuccess event payload
    OnSwitchToWeaponSuccess(MyCockpit_OnSwitchToWeaponSuccessPayload),
    /// OnSwitchAmmoMagazineRequest event (no payload)
    OnSwitchAmmoMagazineRequest,
    /// OnSwitchAmmoMagazineSuccess event (no payload)
    OnSwitchAmmoMagazineSuccess,
    /// ShootBeginCallback event payload
    ShootBeginCallback(MyCockpit_ShootBeginCallbackPayload),
    /// ShootEndCallback event payload
    ShootEndCallback(MyCockpit_ShootEndCallbackPayload),
    /// SendToolbarItemRemoved event payload
    SendToolbarItemRemoved(MyCockpit_SendToolbarItemRemovedPayload),
    /// SendToolbarItemChanged event payload
    SendToolbarItemChanged(MyCockpit_SendToolbarItemChangedPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyCockpit_SelectPanelServerPayload),
    /// OnChangeOpenRequest_18 event payload
    OnChangeOpenRequest_18(MyCockpit_OnChangeOpenRequest_18Payload),
    /// OnChangeOpenSuccess_19 event payload
    OnChangeOpenSuccess_19(MyCockpit_OnChangeOpenSuccess_19Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyCockpit_OnChangeDescriptionPayload),
    /// OnRequestRemovePilot event (no payload)
    OnRequestRemovePilot,
    /// AttachPilotEvent event payload
    AttachPilotEvent(MyCockpit_AttachPilotEventPayload),
    /// SetAutopilot_Client event payload
    SetAutopilot_Client(MyCockpit_SetAutopilot_ClientPayload),
    /// NotifyClientPilotChanged event payload
    NotifyClientPilotChanged(MyCockpit_NotifyClientPilotChangedPayload),
    /// SyncHeadOffsetToServer event payload
    SyncHeadOffsetToServer(MyCockpit_SyncHeadOffsetToServerPayload),
    /// RequestClientSeatedAnimationHeadOffset event (no payload)
    RequestClientSeatedAnimationHeadOffset,
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyCockpitInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyCockpitInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyCockpit_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyCockpit_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyCockpit_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyCockpit_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyCockpitInstanceEventPayload::RemoveContainerDropComponent),
            Self::SyncMoveIndicator => {
                let (_, payload) = MyCockpit_SyncMoveIndicatorPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SyncMoveIndicator(payload))
            }
            Self::sync_ControlledEntity_Used => Ok(MyCockpitInstanceEventPayload::sync_ControlledEntity_Used),
            Self::OnSwitchHelmet => Ok(MyCockpitInstanceEventPayload::OnSwitchHelmet),
            Self::SwitchToWeaponMessage => {
                let (_, payload) = MyCockpit_SwitchToWeaponMessagePayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SwitchToWeaponMessage(payload))
            }
            Self::OnSwitchToWeaponFailure => {
                let (_, payload) = MyCockpit_OnSwitchToWeaponFailurePayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnSwitchToWeaponFailure(payload))
            }
            Self::OnSwitchToWeaponSuccess => {
                let (_, payload) = MyCockpit_OnSwitchToWeaponSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnSwitchToWeaponSuccess(payload))
            }
            Self::OnSwitchAmmoMagazineRequest => Ok(MyCockpitInstanceEventPayload::OnSwitchAmmoMagazineRequest),
            Self::OnSwitchAmmoMagazineSuccess => Ok(MyCockpitInstanceEventPayload::OnSwitchAmmoMagazineSuccess),
            Self::ShootBeginCallback => {
                let (_, payload) = MyCockpit_ShootBeginCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::ShootBeginCallback(payload))
            }
            Self::ShootEndCallback => {
                let (_, payload) = MyCockpit_ShootEndCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::ShootEndCallback(payload))
            }
            Self::SendToolbarItemRemoved => {
                let (_, payload) = MyCockpit_SendToolbarItemRemovedPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SendToolbarItemRemoved(payload))
            }
            Self::SendToolbarItemChanged => {
                let (_, payload) = MyCockpit_SendToolbarItemChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SendToolbarItemChanged(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyCockpit_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenRequest_18 => {
                let (_, payload) = MyCockpit_OnChangeOpenRequest_18Payload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnChangeOpenRequest_18(payload))
            }
            Self::OnChangeOpenSuccess_19 => {
                let (_, payload) = MyCockpit_OnChangeOpenSuccess_19Payload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnChangeOpenSuccess_19(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyCockpit_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::OnRequestRemovePilot => Ok(MyCockpitInstanceEventPayload::OnRequestRemovePilot),
            Self::AttachPilotEvent => {
                let (_, payload) = MyCockpit_AttachPilotEventPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::AttachPilotEvent(payload))
            }
            Self::SetAutopilot_Client => {
                let (_, payload) = MyCockpit_SetAutopilot_ClientPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SetAutopilot_Client(payload))
            }
            Self::NotifyClientPilotChanged => {
                let (_, payload) = MyCockpit_NotifyClientPilotChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::NotifyClientPilotChanged(payload))
            }
            Self::SyncHeadOffsetToServer => {
                let (_, payload) = MyCockpit_SyncHeadOffsetToServerPayload::from_bytes((bytes, 0))?;
                Ok(MyCockpitInstanceEventPayload::SyncHeadOffsetToServer(payload))
            }
            Self::RequestClientSeatedAnimationHeadOffset => Ok(MyCockpitInstanceEventPayload::RequestClientSeatedAnimationHeadOffset),
        }
    }
}

/// Parse an instance event payload for MyCockpit from raw event hash and bytes.
pub fn parse_my_cockpit_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyCockpitInstanceEventPayload, deku::DekuError> {
    match MyCockpitInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyCockpitInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyCockpit instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyCockpitInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyCockpit_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyCockpit_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyCockpit_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyCockpit_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting SyncMoveIndicator event.
    fn visit_sync_move_indicator(&mut self, payload: &MyCockpit_SyncMoveIndicatorPayload) {}
    /// Called when visiting sync_ControlledEntity_Used event (no payload).
    fn visit_sync_controlled_entity_used(&mut self) {}
    /// Called when visiting OnSwitchHelmet event (no payload).
    fn visit_on_switch_helmet(&mut self) {}
    /// Called when visiting SwitchToWeaponMessage event.
    fn visit_switch_to_weapon_message(&mut self, payload: &MyCockpit_SwitchToWeaponMessagePayload) {}
    /// Called when visiting OnSwitchToWeaponFailure event.
    fn visit_on_switch_to_weapon_failure(&mut self, payload: &MyCockpit_OnSwitchToWeaponFailurePayload) {}
    /// Called when visiting OnSwitchToWeaponSuccess event.
    fn visit_on_switch_to_weapon_success(&mut self, payload: &MyCockpit_OnSwitchToWeaponSuccessPayload) {}
    /// Called when visiting OnSwitchAmmoMagazineRequest event (no payload).
    fn visit_on_switch_ammo_magazine_request(&mut self) {}
    /// Called when visiting OnSwitchAmmoMagazineSuccess event (no payload).
    fn visit_on_switch_ammo_magazine_success(&mut self) {}
    /// Called when visiting ShootBeginCallback event.
    fn visit_shoot_begin_callback(&mut self, payload: &MyCockpit_ShootBeginCallbackPayload) {}
    /// Called when visiting ShootEndCallback event.
    fn visit_shoot_end_callback(&mut self, payload: &MyCockpit_ShootEndCallbackPayload) {}
    /// Called when visiting SendToolbarItemRemoved event.
    fn visit_send_toolbar_item_removed(&mut self, payload: &MyCockpit_SendToolbarItemRemovedPayload) {}
    /// Called when visiting SendToolbarItemChanged event.
    fn visit_send_toolbar_item_changed(&mut self, payload: &MyCockpit_SendToolbarItemChangedPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyCockpit_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenRequest_18 event.
    fn visit_on_change_open_request_18(&mut self, payload: &MyCockpit_OnChangeOpenRequest_18Payload) {}
    /// Called when visiting OnChangeOpenSuccess_19 event.
    fn visit_on_change_open_success_19(&mut self, payload: &MyCockpit_OnChangeOpenSuccess_19Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyCockpit_OnChangeDescriptionPayload) {}
    /// Called when visiting OnRequestRemovePilot event (no payload).
    fn visit_on_request_remove_pilot(&mut self) {}
    /// Called when visiting AttachPilotEvent event.
    fn visit_attach_pilot_event(&mut self, payload: &MyCockpit_AttachPilotEventPayload) {}
    /// Called when visiting SetAutopilot_Client event.
    fn visit_set_autopilot_client(&mut self, payload: &MyCockpit_SetAutopilot_ClientPayload) {}
    /// Called when visiting NotifyClientPilotChanged event.
    fn visit_notify_client_pilot_changed(&mut self, payload: &MyCockpit_NotifyClientPilotChangedPayload) {}
    /// Called when visiting SyncHeadOffsetToServer event.
    fn visit_sync_head_offset_to_server(&mut self, payload: &MyCockpit_SyncHeadOffsetToServerPayload) {}
    /// Called when visiting RequestClientSeatedAnimationHeadOffset event (no payload).
    fn visit_request_client_seated_animation_head_offset(&mut self) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyCockpitInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyCockpitInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::SyncMoveIndicator(payload) => visitor.visit_sync_move_indicator(payload),
            Self::sync_ControlledEntity_Used => visitor.visit_sync_controlled_entity_used(),
            Self::OnSwitchHelmet => visitor.visit_on_switch_helmet(),
            Self::SwitchToWeaponMessage(payload) => visitor.visit_switch_to_weapon_message(payload),
            Self::OnSwitchToWeaponFailure(payload) => visitor.visit_on_switch_to_weapon_failure(payload),
            Self::OnSwitchToWeaponSuccess(payload) => visitor.visit_on_switch_to_weapon_success(payload),
            Self::OnSwitchAmmoMagazineRequest => visitor.visit_on_switch_ammo_magazine_request(),
            Self::OnSwitchAmmoMagazineSuccess => visitor.visit_on_switch_ammo_magazine_success(),
            Self::ShootBeginCallback(payload) => visitor.visit_shoot_begin_callback(payload),
            Self::ShootEndCallback(payload) => visitor.visit_shoot_end_callback(payload),
            Self::SendToolbarItemRemoved(payload) => visitor.visit_send_toolbar_item_removed(payload),
            Self::SendToolbarItemChanged(payload) => visitor.visit_send_toolbar_item_changed(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenRequest_18(payload) => visitor.visit_on_change_open_request_18(payload),
            Self::OnChangeOpenSuccess_19(payload) => visitor.visit_on_change_open_success_19(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::OnRequestRemovePilot => visitor.visit_on_request_remove_pilot(),
            Self::AttachPilotEvent(payload) => visitor.visit_attach_pilot_event(payload),
            Self::SetAutopilot_Client(payload) => visitor.visit_set_autopilot_client(payload),
            Self::NotifyClientPilotChanged(payload) => visitor.visit_notify_client_pilot_changed(payload),
            Self::SyncHeadOffsetToServer(payload) => visitor.visit_sync_head_offset_to_server(payload),
            Self::RequestClientSeatedAnimationHeadOffset => visitor.visit_request_client_seated_animation_head_offset(),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyCockpitInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyCockpitInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyCockpitInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyCockpitInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyCockpitInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyCockpitInstanceEvent::RemoveContainerDropComponent),
            Self::SyncMoveIndicator(_) => Some(MyCockpitInstanceEvent::SyncMoveIndicator),
            Self::sync_ControlledEntity_Used => Some(MyCockpitInstanceEvent::sync_ControlledEntity_Used),
            Self::OnSwitchHelmet => Some(MyCockpitInstanceEvent::OnSwitchHelmet),
            Self::SwitchToWeaponMessage(_) => Some(MyCockpitInstanceEvent::SwitchToWeaponMessage),
            Self::OnSwitchToWeaponFailure(_) => Some(MyCockpitInstanceEvent::OnSwitchToWeaponFailure),
            Self::OnSwitchToWeaponSuccess(_) => Some(MyCockpitInstanceEvent::OnSwitchToWeaponSuccess),
            Self::OnSwitchAmmoMagazineRequest => Some(MyCockpitInstanceEvent::OnSwitchAmmoMagazineRequest),
            Self::OnSwitchAmmoMagazineSuccess => Some(MyCockpitInstanceEvent::OnSwitchAmmoMagazineSuccess),
            Self::ShootBeginCallback(_) => Some(MyCockpitInstanceEvent::ShootBeginCallback),
            Self::ShootEndCallback(_) => Some(MyCockpitInstanceEvent::ShootEndCallback),
            Self::SendToolbarItemRemoved(_) => Some(MyCockpitInstanceEvent::SendToolbarItemRemoved),
            Self::SendToolbarItemChanged(_) => Some(MyCockpitInstanceEvent::SendToolbarItemChanged),
            Self::SelectPanelServer(_) => Some(MyCockpitInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenRequest_18(_) => Some(MyCockpitInstanceEvent::OnChangeOpenRequest_18),
            Self::OnChangeOpenSuccess_19(_) => Some(MyCockpitInstanceEvent::OnChangeOpenSuccess_19),
            Self::OnChangeDescription(_) => Some(MyCockpitInstanceEvent::OnChangeDescription),
            Self::OnRequestRemovePilot => Some(MyCockpitInstanceEvent::OnRequestRemovePilot),
            Self::AttachPilotEvent(_) => Some(MyCockpitInstanceEvent::AttachPilotEvent),
            Self::SetAutopilot_Client(_) => Some(MyCockpitInstanceEvent::SetAutopilot_Client),
            Self::NotifyClientPilotChanged(_) => Some(MyCockpitInstanceEvent::NotifyClientPilotChanged),
            Self::SyncHeadOffsetToServer(_) => Some(MyCockpitInstanceEvent::SyncHeadOffsetToServer),
            Self::RequestClientSeatedAnimationHeadOffset => Some(MyCockpitInstanceEvent::RequestClientSeatedAnimationHeadOffset),
            Self::Unknown { .. } => None,
        }
    }
}
