//! Instance events for Sandbox.Game.Entities.Blocks.MyGasGenerator.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyGasGenerator::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyGasGenerator::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyGasGenerator::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyGasGenerator::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyGasGenerator::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyGasGenerator::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyGasGenerator::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyGasGenerator::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyGasGenerator::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasGenerator_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Stable instance event identities for Sandbox.Game.Entities.Blocks.MyGasGenerator.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyGasGeneratorInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: 1636291607
    OnRefillCallback,
}

impl MyGasGeneratorInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::OnRefillCallback => 1636291607,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            1636291607 => Some(Self::OnRefillCallback),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Blocks.MyGasGenerator.
///
/// Use `MyGasGeneratorInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyGasGeneratorInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyGasGenerator_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyGasGenerator_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyGasGenerator_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyGasGenerator_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyGasGenerator_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyGasGenerator_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyGasGenerator_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyGasGenerator_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyGasGenerator_OnChangeDescriptionPayload),
    /// OnRefillCallback event (no payload)
    OnRefillCallback,
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyGasGeneratorInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyGasGeneratorInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyGasGenerator_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyGasGenerator_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyGasGenerator_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyGasGenerator_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyGasGeneratorInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyGasGenerator_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyGasGenerator_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyGasGenerator_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyGasGenerator_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyGasGenerator_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyGasGeneratorInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::OnRefillCallback => Ok(MyGasGeneratorInstanceEventPayload::OnRefillCallback),
        }
    }
}

/// Parse an instance event payload for MyGasGenerator from raw event hash and bytes.
pub fn parse_my_gas_generator_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyGasGeneratorInstanceEventPayload, deku::DekuError> {
    match MyGasGeneratorInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyGasGeneratorInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyGasGenerator instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyGasGeneratorInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyGasGenerator_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyGasGenerator_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyGasGenerator_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyGasGenerator_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyGasGenerator_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyGasGenerator_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyGasGenerator_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyGasGenerator_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyGasGenerator_OnChangeDescriptionPayload) {}
    /// Called when visiting OnRefillCallback event (no payload).
    fn visit_on_refill_callback(&mut self) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyGasGeneratorInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyGasGeneratorInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::OnRefillCallback => visitor.visit_on_refill_callback(),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyGasGeneratorInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyGasGeneratorInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyGasGeneratorInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyGasGeneratorInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyGasGeneratorInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyGasGeneratorInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyGasGeneratorInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyGasGeneratorInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyGasGeneratorInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyGasGeneratorInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyGasGeneratorInstanceEvent::OnChangeDescription),
            Self::OnRefillCallback => Some(MyGasGeneratorInstanceEvent::OnRefillCallback),
            Self::Unknown { .. } => None,
        }
    }
}
