//! Instance events for Sandbox.Game.Entities.Blocks.MyGasTank.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyGasTank::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyGasTank::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyGasTank::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyGasTank::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyGasTank::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyGasTank::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyGasTank::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyGasTank::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyGasTank::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyGasTank::OnStockpileModeCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnStockpileModeCallbackPayload {
    pub new_stockpile_mode: BitBool,
}

/// Payload for MyGasTank::OnFilledRatioCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyGasTank_OnFilledRatioCallbackPayload {
    pub new_filled_ratio: BitAligned<f64>,
}

/// Stable instance event identities for Sandbox.Game.Entities.Blocks.MyGasTank.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyGasTankInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: -1214041612
    OnStockpileModeCallback,
    /// Hash: 463707949
    OnFilledRatioCallback,
    /// Hash: -1609946042
    OnRefillCallback,
}

impl MyGasTankInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::OnStockpileModeCallback => -1214041612,
            Self::OnFilledRatioCallback => 463707949,
            Self::OnRefillCallback => -1609946042,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            -1214041612 => Some(Self::OnStockpileModeCallback),
            463707949 => Some(Self::OnFilledRatioCallback),
            -1609946042 => Some(Self::OnRefillCallback),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Blocks.MyGasTank.
///
/// Use `MyGasTankInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyGasTankInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyGasTank_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyGasTank_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyGasTank_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyGasTank_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyGasTank_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyGasTank_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyGasTank_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyGasTank_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyGasTank_OnChangeDescriptionPayload),
    /// OnStockpileModeCallback event payload
    OnStockpileModeCallback(MyGasTank_OnStockpileModeCallbackPayload),
    /// OnFilledRatioCallback event payload
    OnFilledRatioCallback(MyGasTank_OnFilledRatioCallbackPayload),
    /// OnRefillCallback event (no payload)
    OnRefillCallback,
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyGasTankInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyGasTankInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyGasTank_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyGasTank_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyGasTank_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyGasTank_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyGasTankInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyGasTank_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyGasTank_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyGasTank_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyGasTank_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyGasTank_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::OnStockpileModeCallback => {
                let (_, payload) = MyGasTank_OnStockpileModeCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnStockpileModeCallback(payload))
            }
            Self::OnFilledRatioCallback => {
                let (_, payload) = MyGasTank_OnFilledRatioCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MyGasTankInstanceEventPayload::OnFilledRatioCallback(payload))
            }
            Self::OnRefillCallback => Ok(MyGasTankInstanceEventPayload::OnRefillCallback),
        }
    }
}

/// Parse an instance event payload for MyGasTank from raw event hash and bytes.
pub fn parse_my_gas_tank_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyGasTankInstanceEventPayload, deku::DekuError> {
    match MyGasTankInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyGasTankInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyGasTank instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyGasTankInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyGasTank_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyGasTank_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyGasTank_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyGasTank_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyGasTank_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyGasTank_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyGasTank_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyGasTank_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyGasTank_OnChangeDescriptionPayload) {}
    /// Called when visiting OnStockpileModeCallback event.
    fn visit_on_stockpile_mode_callback(&mut self, payload: &MyGasTank_OnStockpileModeCallbackPayload) {}
    /// Called when visiting OnFilledRatioCallback event.
    fn visit_on_filled_ratio_callback(&mut self, payload: &MyGasTank_OnFilledRatioCallbackPayload) {}
    /// Called when visiting OnRefillCallback event (no payload).
    fn visit_on_refill_callback(&mut self) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyGasTankInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyGasTankInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::OnStockpileModeCallback(payload) => visitor.visit_on_stockpile_mode_callback(payload),
            Self::OnFilledRatioCallback(payload) => visitor.visit_on_filled_ratio_callback(payload),
            Self::OnRefillCallback => visitor.visit_on_refill_callback(),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyGasTankInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyGasTankInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyGasTankInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyGasTankInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyGasTankInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyGasTankInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyGasTankInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyGasTankInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyGasTankInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyGasTankInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyGasTankInstanceEvent::OnChangeDescription),
            Self::OnStockpileModeCallback(_) => Some(MyGasTankInstanceEvent::OnStockpileModeCallback),
            Self::OnFilledRatioCallback(_) => Some(MyGasTankInstanceEvent::OnFilledRatioCallback),
            Self::OnRefillCallback => Some(MyGasTankInstanceEvent::OnRefillCallback),
            Self::Unknown { .. } => None,
        }
    }
}
