//! Instance events for Sandbox.Game.Entities.MyJumpDrive.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyJumpDrive::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyJumpDrive::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyJumpDrive::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyJumpDrive::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyJumpDrive::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyJumpDrive::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyJumpDrive::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyJumpDrive::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyJumpDrive::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyJumpDrive::RequestJumpUpdateBeaconServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_RequestJumpUpdateBeaconServerPayload {
    pub ship_controller_id: BitAligned<i64>,
}

/// Payload for MyJumpDrive::RequestJumpUpdateBeaconCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_RequestJumpUpdateBeaconCallbackPayload {
    pub ship_controller_id: BitAligned<i64>,
    pub beacon_text: VarString,
    pub coords: Vector3D,
}

/// Payload for MyJumpDrive::SetBeaconAsTargetServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyJumpDrive_SetBeaconAsTargetServerPayload {
    pub beacon_id: BitAligned<i64>,
}

/// Stable instance event identities for Sandbox.Game.Entities.MyJumpDrive.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyJumpDriveInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: 644761588
    RequestJumpUpdateBeaconServer,
    /// Hash: -98084333
    RequestJumpUpdateBeaconCallback,
    /// Hash: 1786159509
    GetBeaconsInRangeServer,
    /// Hash: 287395288
    SetBeaconAsTargetServer,
}

impl MyJumpDriveInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::RequestJumpUpdateBeaconServer => 644761588,
            Self::RequestJumpUpdateBeaconCallback => -98084333,
            Self::GetBeaconsInRangeServer => 1786159509,
            Self::SetBeaconAsTargetServer => 287395288,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            644761588 => Some(Self::RequestJumpUpdateBeaconServer),
            -98084333 => Some(Self::RequestJumpUpdateBeaconCallback),
            1786159509 => Some(Self::GetBeaconsInRangeServer),
            287395288 => Some(Self::SetBeaconAsTargetServer),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.MyJumpDrive.
///
/// Use `MyJumpDriveInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyJumpDriveInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyJumpDrive_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyJumpDrive_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyJumpDrive_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyJumpDrive_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyJumpDrive_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyJumpDrive_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyJumpDrive_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyJumpDrive_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyJumpDrive_OnChangeDescriptionPayload),
    /// RequestJumpUpdateBeaconServer event payload
    RequestJumpUpdateBeaconServer(MyJumpDrive_RequestJumpUpdateBeaconServerPayload),
    /// RequestJumpUpdateBeaconCallback event payload
    RequestJumpUpdateBeaconCallback(MyJumpDrive_RequestJumpUpdateBeaconCallbackPayload),
    /// GetBeaconsInRangeServer event (no payload)
    GetBeaconsInRangeServer,
    /// SetBeaconAsTargetServer event payload
    SetBeaconAsTargetServer(MyJumpDrive_SetBeaconAsTargetServerPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyJumpDriveInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyJumpDriveInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyJumpDrive_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyJumpDrive_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyJumpDrive_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyJumpDrive_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyJumpDriveInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyJumpDrive_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyJumpDrive_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyJumpDrive_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyJumpDrive_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyJumpDrive_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::RequestJumpUpdateBeaconServer => {
                let (_, payload) = MyJumpDrive_RequestJumpUpdateBeaconServerPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::RequestJumpUpdateBeaconServer(payload))
            }
            Self::RequestJumpUpdateBeaconCallback => {
                let (_, payload) = MyJumpDrive_RequestJumpUpdateBeaconCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::RequestJumpUpdateBeaconCallback(payload))
            }
            Self::GetBeaconsInRangeServer => Ok(MyJumpDriveInstanceEventPayload::GetBeaconsInRangeServer),
            Self::SetBeaconAsTargetServer => {
                let (_, payload) = MyJumpDrive_SetBeaconAsTargetServerPayload::from_bytes((bytes, 0))?;
                Ok(MyJumpDriveInstanceEventPayload::SetBeaconAsTargetServer(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyJumpDrive from raw event hash and bytes.
pub fn parse_my_jump_drive_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyJumpDriveInstanceEventPayload, deku::DekuError> {
    match MyJumpDriveInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyJumpDriveInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyJumpDrive instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyJumpDriveInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyJumpDrive_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyJumpDrive_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyJumpDrive_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyJumpDrive_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyJumpDrive_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyJumpDrive_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyJumpDrive_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyJumpDrive_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyJumpDrive_OnChangeDescriptionPayload) {}
    /// Called when visiting RequestJumpUpdateBeaconServer event.
    fn visit_request_jump_update_beacon_server(&mut self, payload: &MyJumpDrive_RequestJumpUpdateBeaconServerPayload) {}
    /// Called when visiting RequestJumpUpdateBeaconCallback event.
    fn visit_request_jump_update_beacon_callback(&mut self, payload: &MyJumpDrive_RequestJumpUpdateBeaconCallbackPayload) {}
    /// Called when visiting GetBeaconsInRangeServer event (no payload).
    fn visit_get_beacons_in_range_server(&mut self) {}
    /// Called when visiting SetBeaconAsTargetServer event.
    fn visit_set_beacon_as_target_server(&mut self, payload: &MyJumpDrive_SetBeaconAsTargetServerPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyJumpDriveInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyJumpDriveInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::RequestJumpUpdateBeaconServer(payload) => visitor.visit_request_jump_update_beacon_server(payload),
            Self::RequestJumpUpdateBeaconCallback(payload) => visitor.visit_request_jump_update_beacon_callback(payload),
            Self::GetBeaconsInRangeServer => visitor.visit_get_beacons_in_range_server(),
            Self::SetBeaconAsTargetServer(payload) => visitor.visit_set_beacon_as_target_server(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyJumpDriveInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyJumpDriveInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyJumpDriveInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyJumpDriveInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyJumpDriveInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyJumpDriveInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyJumpDriveInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyJumpDriveInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyJumpDriveInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyJumpDriveInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyJumpDriveInstanceEvent::OnChangeDescription),
            Self::RequestJumpUpdateBeaconServer(_) => Some(MyJumpDriveInstanceEvent::RequestJumpUpdateBeaconServer),
            Self::RequestJumpUpdateBeaconCallback(_) => Some(MyJumpDriveInstanceEvent::RequestJumpUpdateBeaconCallback),
            Self::GetBeaconsInRangeServer => Some(MyJumpDriveInstanceEvent::GetBeaconsInRangeServer),
            Self::SetBeaconAsTargetServer(_) => Some(MyJumpDriveInstanceEvent::SetBeaconAsTargetServer),
            Self::Unknown { .. } => None,
        }
    }
}
