//! Instance events for SpaceEngineers.Game.Entities.Blocks.MyLandingGear.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyLandingGear::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyLandingGear::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyLandingGear::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyLandingGear::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyLandingGear::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyLandingGear::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyLandingGear::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyLandingGear::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyLandingGear::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyLandingGear::ResetLockConstraint instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_ResetLockConstraintPayload {
    pub locked: BitBool,
    pub force: BitBool,
}

/// Payload for MyLandingGear::AttachRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyLandingGear_AttachRequestPayload {
    pub enable: BitBool,
}

/// Stable instance event identities for SpaceEngineers.Game.Entities.Blocks.MyLandingGear.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyLandingGearInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: 1023333955
    AttachFailed,
    /// Hash: -1886513118
    ResetLockConstraint,
    /// Hash: 1071846652
    AttachRequest,
}

impl MyLandingGearInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::AttachFailed => 1023333955,
            Self::ResetLockConstraint => -1886513118,
            Self::AttachRequest => 1071846652,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            1023333955 => Some(Self::AttachFailed),
            -1886513118 => Some(Self::ResetLockConstraint),
            1071846652 => Some(Self::AttachRequest),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.Entities.Blocks.MyLandingGear.
///
/// Use `MyLandingGearInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyLandingGearInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyLandingGear_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyLandingGear_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyLandingGear_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyLandingGear_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyLandingGear_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyLandingGear_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyLandingGear_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyLandingGear_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyLandingGear_OnChangeDescriptionPayload),
    /// AttachFailed event (no payload)
    AttachFailed,
    /// ResetLockConstraint event payload
    ResetLockConstraint(MyLandingGear_ResetLockConstraintPayload),
    /// AttachRequest event payload
    AttachRequest(MyLandingGear_AttachRequestPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyLandingGearInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyLandingGearInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyLandingGear_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyLandingGear_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyLandingGear_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyLandingGear_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyLandingGearInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyLandingGear_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyLandingGear_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyLandingGear_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyLandingGear_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyLandingGear_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::AttachFailed => Ok(MyLandingGearInstanceEventPayload::AttachFailed),
            Self::ResetLockConstraint => {
                let (_, payload) = MyLandingGear_ResetLockConstraintPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::ResetLockConstraint(payload))
            }
            Self::AttachRequest => {
                let (_, payload) = MyLandingGear_AttachRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyLandingGearInstanceEventPayload::AttachRequest(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyLandingGear from raw event hash and bytes.
pub fn parse_my_landing_gear_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyLandingGearInstanceEventPayload, deku::DekuError> {
    match MyLandingGearInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyLandingGearInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyLandingGear instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyLandingGearInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyLandingGear_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyLandingGear_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyLandingGear_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyLandingGear_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyLandingGear_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyLandingGear_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyLandingGear_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyLandingGear_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyLandingGear_OnChangeDescriptionPayload) {}
    /// Called when visiting AttachFailed event (no payload).
    fn visit_attach_failed(&mut self) {}
    /// Called when visiting ResetLockConstraint event.
    fn visit_reset_lock_constraint(&mut self, payload: &MyLandingGear_ResetLockConstraintPayload) {}
    /// Called when visiting AttachRequest event.
    fn visit_attach_request(&mut self, payload: &MyLandingGear_AttachRequestPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyLandingGearInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyLandingGearInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::AttachFailed => visitor.visit_attach_failed(),
            Self::ResetLockConstraint(payload) => visitor.visit_reset_lock_constraint(payload),
            Self::AttachRequest(payload) => visitor.visit_attach_request(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyLandingGearInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyLandingGearInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyLandingGearInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyLandingGearInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyLandingGearInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyLandingGearInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyLandingGearInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyLandingGearInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyLandingGearInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyLandingGearInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyLandingGearInstanceEvent::OnChangeDescription),
            Self::AttachFailed => Some(MyLandingGearInstanceEvent::AttachFailed),
            Self::ResetLockConstraint(_) => Some(MyLandingGearInstanceEvent::ResetLockConstraint),
            Self::AttachRequest(_) => Some(MyLandingGearInstanceEvent::AttachRequest),
            Self::Unknown { .. } => None,
        }
    }
}
