//! Instance events for Sandbox.Game.Entities.Cube.MyRadioBroadcaster.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyRadioBroadcaster::OnOwnerChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyRadioBroadcaster_OnOwnerChangedPayload {
    pub new_owner: BitAligned<i64>,
    pub new_share: space_engineers_sys::types::MyOwnershipShareModeEnum,
}

/// Payload for MyRadioBroadcaster::OnNameChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyRadioBroadcaster_OnNameChangedPayload {
    pub new_name: VarString,
}

/// Payload for MyRadioBroadcaster::UpdateRemoteControlState instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyRadioBroadcaster_UpdateRemoteControlStatePayload {
    pub has_remote: BitBool,
    pub owner: Nullable<BitAligned<i64>>,
    pub sharing: space_engineers_sys::types::MyOwnershipShareModeEnum,
    pub remote_id: Nullable<BitAligned<i64>>,
}

/// Payload for MyRadioBroadcaster::OnUpdateHudParams instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyRadioBroadcaster_OnUpdateHudParamsPayload {
    pub new_hud_params: VarVec<space_engineers_sys::types::MyObjectBuilder_HudEntityParams>,
}

/// Payload for MyRadioBroadcaster::ChangeBroadcastRadius instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyRadioBroadcaster_ChangeBroadcastRadiusPayload {
    pub new_radius: BitAligned<f32>,
}

/// Stable instance event identities for Sandbox.Game.Entities.Cube.MyRadioBroadcaster.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyRadioBroadcasterInstanceEvent {
    /// Hash: -1768876280
    OnOwnerChanged,
    /// Hash: -118597618
    OnNameChanged,
    /// Hash: -1155675924
    UpdateRemoteControlState,
    /// Hash: -672355139
    OnUpdateHudParams,
    /// Hash: 223115047
    ChangeBroadcastRadius,
}

impl MyRadioBroadcasterInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::OnOwnerChanged => -1768876280,
            Self::OnNameChanged => -118597618,
            Self::UpdateRemoteControlState => -1155675924,
            Self::OnUpdateHudParams => -672355139,
            Self::ChangeBroadcastRadius => 223115047,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1768876280 => Some(Self::OnOwnerChanged),
            -118597618 => Some(Self::OnNameChanged),
            -1155675924 => Some(Self::UpdateRemoteControlState),
            -672355139 => Some(Self::OnUpdateHudParams),
            223115047 => Some(Self::ChangeBroadcastRadius),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Cube.MyRadioBroadcaster.
///
/// Use `MyRadioBroadcasterInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyRadioBroadcasterInstanceEventPayload {
    /// OnOwnerChanged event payload
    OnOwnerChanged(MyRadioBroadcaster_OnOwnerChangedPayload),
    /// OnNameChanged event payload
    OnNameChanged(MyRadioBroadcaster_OnNameChangedPayload),
    /// UpdateRemoteControlState event payload
    UpdateRemoteControlState(MyRadioBroadcaster_UpdateRemoteControlStatePayload),
    /// OnUpdateHudParams event payload
    OnUpdateHudParams(MyRadioBroadcaster_OnUpdateHudParamsPayload),
    /// ChangeBroadcastRadius event payload
    ChangeBroadcastRadius(MyRadioBroadcaster_ChangeBroadcastRadiusPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyRadioBroadcasterInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyRadioBroadcasterInstanceEventPayload, deku::DekuError> {
        match self {
            Self::OnOwnerChanged => {
                let (_, payload) = MyRadioBroadcaster_OnOwnerChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyRadioBroadcasterInstanceEventPayload::OnOwnerChanged(payload))
            }
            Self::OnNameChanged => {
                let (_, payload) = MyRadioBroadcaster_OnNameChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyRadioBroadcasterInstanceEventPayload::OnNameChanged(payload))
            }
            Self::UpdateRemoteControlState => {
                let (_, payload) = MyRadioBroadcaster_UpdateRemoteControlStatePayload::from_bytes((bytes, 0))?;
                Ok(MyRadioBroadcasterInstanceEventPayload::UpdateRemoteControlState(payload))
            }
            Self::OnUpdateHudParams => {
                let (_, payload) = MyRadioBroadcaster_OnUpdateHudParamsPayload::from_bytes((bytes, 0))?;
                Ok(MyRadioBroadcasterInstanceEventPayload::OnUpdateHudParams(payload))
            }
            Self::ChangeBroadcastRadius => {
                let (_, payload) = MyRadioBroadcaster_ChangeBroadcastRadiusPayload::from_bytes((bytes, 0))?;
                Ok(MyRadioBroadcasterInstanceEventPayload::ChangeBroadcastRadius(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyRadioBroadcaster from raw event hash and bytes.
pub fn parse_my_radio_broadcaster_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyRadioBroadcasterInstanceEventPayload, deku::DekuError> {
    match MyRadioBroadcasterInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyRadioBroadcasterInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyRadioBroadcaster instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyRadioBroadcasterInstanceEventVisitor {
    /// Called when visiting OnOwnerChanged event.
    fn visit_on_owner_changed(&mut self, payload: &MyRadioBroadcaster_OnOwnerChangedPayload) {}
    /// Called when visiting OnNameChanged event.
    fn visit_on_name_changed(&mut self, payload: &MyRadioBroadcaster_OnNameChangedPayload) {}
    /// Called when visiting UpdateRemoteControlState event.
    fn visit_update_remote_control_state(&mut self, payload: &MyRadioBroadcaster_UpdateRemoteControlStatePayload) {}
    /// Called when visiting OnUpdateHudParams event.
    fn visit_on_update_hud_params(&mut self, payload: &MyRadioBroadcaster_OnUpdateHudParamsPayload) {}
    /// Called when visiting ChangeBroadcastRadius event.
    fn visit_change_broadcast_radius(&mut self, payload: &MyRadioBroadcaster_ChangeBroadcastRadiusPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyRadioBroadcasterInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyRadioBroadcasterInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::OnOwnerChanged(payload) => visitor.visit_on_owner_changed(payload),
            Self::OnNameChanged(payload) => visitor.visit_on_name_changed(payload),
            Self::UpdateRemoteControlState(payload) => visitor.visit_update_remote_control_state(payload),
            Self::OnUpdateHudParams(payload) => visitor.visit_on_update_hud_params(payload),
            Self::ChangeBroadcastRadius(payload) => visitor.visit_change_broadcast_radius(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyRadioBroadcasterInstanceEvent> {
        match self {
            Self::OnOwnerChanged(_) => Some(MyRadioBroadcasterInstanceEvent::OnOwnerChanged),
            Self::OnNameChanged(_) => Some(MyRadioBroadcasterInstanceEvent::OnNameChanged),
            Self::UpdateRemoteControlState(_) => Some(MyRadioBroadcasterInstanceEvent::UpdateRemoteControlState),
            Self::OnUpdateHudParams(_) => Some(MyRadioBroadcasterInstanceEvent::OnUpdateHudParams),
            Self::ChangeBroadcastRadius(_) => Some(MyRadioBroadcasterInstanceEvent::ChangeBroadcastRadius),
            Self::Unknown { .. } => None,
        }
    }
}
