//! Instance events for Sandbox.Game.Entities.Blocks.MyStoreBlock.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyStoreBlock::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyStoreBlock::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyStoreBlock::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyStoreBlock::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyStoreBlock::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyStoreBlock::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyStoreBlock::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyStoreBlock::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyStoreBlock::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyStoreBlock::OnGetStoreItemsResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnGetStoreItemsResultPayload {
    pub store_items: VarVec<space_engineers_sys::types::MyStoreItem>,
    pub last_economy_tick: BitAligned<i64>,
    pub offers_bonus: BitAligned<f32>,
    pub orders_bonus: BitAligned<f32>,
}

/// Payload for MyStoreBlock::OnPlayerStoreItemsChanged_Broacast instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnPlayerStoreItemsChanged_BroacastPayload {
    pub store_items: VarVec<space_engineers_sys::types::MyStoreItem>,
    pub last_economy_tick: BitAligned<i64>,
}

/// Payload for MyStoreBlock::BuyItem instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_BuyItemPayload {
    pub id: BitAligned<i64>,
    pub amount: BitAligned<i32>,
    pub target_entity_id: BitAligned<i64>,
    pub last_economy_tick: BitAligned<i64>,
}

/// Payload for MyStoreBlock::OnBuyItemResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnBuyItemResultPayload {
    pub result: space_engineers_sys::types::MyStoreBuyItemResult,
}

/// Payload for MyStoreBlock::SellItem instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_SellItemPayload {
    pub id: BitAligned<i64>,
    pub amount: BitAligned<i32>,
    pub source_entity_id: BitAligned<i64>,
    pub last_economy_tick: BitAligned<i64>,
}

/// Payload for MyStoreBlock::OnSellItemResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnSellItemResultPayload {
    pub result: space_engineers_sys::types::MyStoreSellItemResult,
}

/// Payload for MyStoreBlock::OnGetConnectedGridInventoriesResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnGetConnectedGridInventoriesResultPayload {
    pub inventories: VarVec<BitAligned<i64>>,
}

/// Payload for MyStoreBlock::OnGetGridInventoriesResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnGetGridInventoriesResultPayload {
    pub inventories: VarVec<BitAligned<i64>>,
}

/// Payload for MyStoreBlock::CreateNewOffer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_CreateNewOfferPayload {
    pub item_id: space_engineers_sys::types::SerializableDefinitionId,
    pub amount: BitAligned<i32>,
    pub price_per_unit: BitAligned<i32>,
}

/// Payload for MyStoreBlock::OnCreateNewOfferResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnCreateNewOfferResultPayload {
    pub result: space_engineers_sys::types::MyStoreCreationResult,
}

/// Payload for MyStoreBlock::CreateNewOrder instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_CreateNewOrderPayload {
    pub item_id: space_engineers_sys::types::SerializableDefinitionId,
    pub amount: BitAligned<i32>,
    pub price_per_unit: BitAligned<i32>,
}

/// Payload for MyStoreBlock::OnCreateNewOrderResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnCreateNewOrderResultPayload {
    pub result: space_engineers_sys::types::MyStoreCreationResult,
}

/// Payload for MyStoreBlock::CancelStoreItemServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_CancelStoreItemServerPayload {
    pub id: BitAligned<i64>,
}

/// Payload for MyStoreBlock::OnCancelStoreItemResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnCancelStoreItemResultPayload {
    pub result: BitBool,
}

/// Payload for MyStoreBlock::ChangeBalance instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_ChangeBalancePayload {
    pub amount: BitAligned<i32>,
    pub target_entity_id: BitAligned<i64>,
}

/// Payload for MyStoreBlock::OnChangeBalanceResult instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_OnChangeBalanceResultPayload {
    pub result: space_engineers_sys::types::MyStoreBuyItemResults,
}

/// Payload for MyStoreBlock::ShowPreviewImplementation instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyStoreBlock_ShowPreviewImplementationPayload {
    pub store_item_id: BitAligned<i64>,
}

/// Stable instance event identities for Sandbox.Game.Entities.Blocks.MyStoreBlock.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyStoreBlockInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: 620557266
    GetStoreItems,
    /// Hash: 1573178102
    OnGetStoreItemsResult,
    /// Hash: -1001180266
    OnPlayerStoreItemsChanged_Broacast,
    /// Hash: -1013975700
    BuyItem,
    /// Hash: -468107841
    OnBuyItemResult,
    /// Hash: -1124822076
    SellItem,
    /// Hash: -230294525
    OnSellItemResult,
    /// Hash: -874137854
    GetConnectedGridInventories,
    /// Hash: 32502610
    OnGetConnectedGridInventoriesResult,
    /// Hash: 545663401
    GetGridInventories,
    /// Hash: -128722630
    OnGetGridInventoriesResult,
    /// Hash: 1500836146
    CreateNewOffer,
    /// Hash: -749413575
    OnCreateNewOfferResult,
    /// Hash: 379281956
    CreateNewOrder,
    /// Hash: 1552626135
    OnCreateNewOrderResult,
    /// Hash: -112977548
    CancelStoreItemServer,
    /// Hash: 1918143478
    OnCancelStoreItemResult,
    /// Hash: -2145874583
    ChangeBalance,
    /// Hash: 1163603713
    OnChangeBalanceResult,
    /// Hash: 911264488
    ShowPreviewImplementation,
}

impl MyStoreBlockInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::GetStoreItems => 620557266,
            Self::OnGetStoreItemsResult => 1573178102,
            Self::OnPlayerStoreItemsChanged_Broacast => -1001180266,
            Self::BuyItem => -1013975700,
            Self::OnBuyItemResult => -468107841,
            Self::SellItem => -1124822076,
            Self::OnSellItemResult => -230294525,
            Self::GetConnectedGridInventories => -874137854,
            Self::OnGetConnectedGridInventoriesResult => 32502610,
            Self::GetGridInventories => 545663401,
            Self::OnGetGridInventoriesResult => -128722630,
            Self::CreateNewOffer => 1500836146,
            Self::OnCreateNewOfferResult => -749413575,
            Self::CreateNewOrder => 379281956,
            Self::OnCreateNewOrderResult => 1552626135,
            Self::CancelStoreItemServer => -112977548,
            Self::OnCancelStoreItemResult => 1918143478,
            Self::ChangeBalance => -2145874583,
            Self::OnChangeBalanceResult => 1163603713,
            Self::ShowPreviewImplementation => 911264488,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            620557266 => Some(Self::GetStoreItems),
            1573178102 => Some(Self::OnGetStoreItemsResult),
            -1001180266 => Some(Self::OnPlayerStoreItemsChanged_Broacast),
            -1013975700 => Some(Self::BuyItem),
            -468107841 => Some(Self::OnBuyItemResult),
            -1124822076 => Some(Self::SellItem),
            -230294525 => Some(Self::OnSellItemResult),
            -874137854 => Some(Self::GetConnectedGridInventories),
            32502610 => Some(Self::OnGetConnectedGridInventoriesResult),
            545663401 => Some(Self::GetGridInventories),
            -128722630 => Some(Self::OnGetGridInventoriesResult),
            1500836146 => Some(Self::CreateNewOffer),
            -749413575 => Some(Self::OnCreateNewOfferResult),
            379281956 => Some(Self::CreateNewOrder),
            1552626135 => Some(Self::OnCreateNewOrderResult),
            -112977548 => Some(Self::CancelStoreItemServer),
            1918143478 => Some(Self::OnCancelStoreItemResult),
            -2145874583 => Some(Self::ChangeBalance),
            1163603713 => Some(Self::OnChangeBalanceResult),
            911264488 => Some(Self::ShowPreviewImplementation),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Blocks.MyStoreBlock.
///
/// Use `MyStoreBlockInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyStoreBlockInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyStoreBlock_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyStoreBlock_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyStoreBlock_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyStoreBlock_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyStoreBlock_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyStoreBlock_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyStoreBlock_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyStoreBlock_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyStoreBlock_OnChangeDescriptionPayload),
    /// GetStoreItems event (no payload)
    GetStoreItems,
    /// OnGetStoreItemsResult event payload
    OnGetStoreItemsResult(MyStoreBlock_OnGetStoreItemsResultPayload),
    /// OnPlayerStoreItemsChanged_Broacast event payload
    OnPlayerStoreItemsChanged_Broacast(MyStoreBlock_OnPlayerStoreItemsChanged_BroacastPayload),
    /// BuyItem event payload
    BuyItem(MyStoreBlock_BuyItemPayload),
    /// OnBuyItemResult event payload
    OnBuyItemResult(MyStoreBlock_OnBuyItemResultPayload),
    /// SellItem event payload
    SellItem(MyStoreBlock_SellItemPayload),
    /// OnSellItemResult event payload
    OnSellItemResult(MyStoreBlock_OnSellItemResultPayload),
    /// GetConnectedGridInventories event (no payload)
    GetConnectedGridInventories,
    /// OnGetConnectedGridInventoriesResult event payload
    OnGetConnectedGridInventoriesResult(MyStoreBlock_OnGetConnectedGridInventoriesResultPayload),
    /// GetGridInventories event (no payload)
    GetGridInventories,
    /// OnGetGridInventoriesResult event payload
    OnGetGridInventoriesResult(MyStoreBlock_OnGetGridInventoriesResultPayload),
    /// CreateNewOffer event payload
    CreateNewOffer(MyStoreBlock_CreateNewOfferPayload),
    /// OnCreateNewOfferResult event payload
    OnCreateNewOfferResult(MyStoreBlock_OnCreateNewOfferResultPayload),
    /// CreateNewOrder event payload
    CreateNewOrder(MyStoreBlock_CreateNewOrderPayload),
    /// OnCreateNewOrderResult event payload
    OnCreateNewOrderResult(MyStoreBlock_OnCreateNewOrderResultPayload),
    /// CancelStoreItemServer event payload
    CancelStoreItemServer(MyStoreBlock_CancelStoreItemServerPayload),
    /// OnCancelStoreItemResult event payload
    OnCancelStoreItemResult(MyStoreBlock_OnCancelStoreItemResultPayload),
    /// ChangeBalance event payload
    ChangeBalance(MyStoreBlock_ChangeBalancePayload),
    /// OnChangeBalanceResult event payload
    OnChangeBalanceResult(MyStoreBlock_OnChangeBalanceResultPayload),
    /// ShowPreviewImplementation event payload
    ShowPreviewImplementation(MyStoreBlock_ShowPreviewImplementationPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyStoreBlockInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyStoreBlockInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyStoreBlock_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyStoreBlock_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyStoreBlock_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyStoreBlock_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyStoreBlockInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyStoreBlock_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyStoreBlock_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyStoreBlock_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyStoreBlock_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyStoreBlock_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::GetStoreItems => Ok(MyStoreBlockInstanceEventPayload::GetStoreItems),
            Self::OnGetStoreItemsResult => {
                let (_, payload) = MyStoreBlock_OnGetStoreItemsResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnGetStoreItemsResult(payload))
            }
            Self::OnPlayerStoreItemsChanged_Broacast => {
                let (_, payload) = MyStoreBlock_OnPlayerStoreItemsChanged_BroacastPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnPlayerStoreItemsChanged_Broacast(payload))
            }
            Self::BuyItem => {
                let (_, payload) = MyStoreBlock_BuyItemPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::BuyItem(payload))
            }
            Self::OnBuyItemResult => {
                let (_, payload) = MyStoreBlock_OnBuyItemResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnBuyItemResult(payload))
            }
            Self::SellItem => {
                let (_, payload) = MyStoreBlock_SellItemPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::SellItem(payload))
            }
            Self::OnSellItemResult => {
                let (_, payload) = MyStoreBlock_OnSellItemResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnSellItemResult(payload))
            }
            Self::GetConnectedGridInventories => Ok(MyStoreBlockInstanceEventPayload::GetConnectedGridInventories),
            Self::OnGetConnectedGridInventoriesResult => {
                let (_, payload) = MyStoreBlock_OnGetConnectedGridInventoriesResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnGetConnectedGridInventoriesResult(payload))
            }
            Self::GetGridInventories => Ok(MyStoreBlockInstanceEventPayload::GetGridInventories),
            Self::OnGetGridInventoriesResult => {
                let (_, payload) = MyStoreBlock_OnGetGridInventoriesResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnGetGridInventoriesResult(payload))
            }
            Self::CreateNewOffer => {
                let (_, payload) = MyStoreBlock_CreateNewOfferPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::CreateNewOffer(payload))
            }
            Self::OnCreateNewOfferResult => {
                let (_, payload) = MyStoreBlock_OnCreateNewOfferResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnCreateNewOfferResult(payload))
            }
            Self::CreateNewOrder => {
                let (_, payload) = MyStoreBlock_CreateNewOrderPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::CreateNewOrder(payload))
            }
            Self::OnCreateNewOrderResult => {
                let (_, payload) = MyStoreBlock_OnCreateNewOrderResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnCreateNewOrderResult(payload))
            }
            Self::CancelStoreItemServer => {
                let (_, payload) = MyStoreBlock_CancelStoreItemServerPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::CancelStoreItemServer(payload))
            }
            Self::OnCancelStoreItemResult => {
                let (_, payload) = MyStoreBlock_OnCancelStoreItemResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnCancelStoreItemResult(payload))
            }
            Self::ChangeBalance => {
                let (_, payload) = MyStoreBlock_ChangeBalancePayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::ChangeBalance(payload))
            }
            Self::OnChangeBalanceResult => {
                let (_, payload) = MyStoreBlock_OnChangeBalanceResultPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::OnChangeBalanceResult(payload))
            }
            Self::ShowPreviewImplementation => {
                let (_, payload) = MyStoreBlock_ShowPreviewImplementationPayload::from_bytes((bytes, 0))?;
                Ok(MyStoreBlockInstanceEventPayload::ShowPreviewImplementation(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyStoreBlock from raw event hash and bytes.
pub fn parse_my_store_block_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyStoreBlockInstanceEventPayload, deku::DekuError> {
    match MyStoreBlockInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyStoreBlockInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyStoreBlock instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyStoreBlockInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyStoreBlock_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyStoreBlock_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyStoreBlock_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyStoreBlock_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyStoreBlock_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyStoreBlock_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyStoreBlock_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyStoreBlock_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyStoreBlock_OnChangeDescriptionPayload) {}
    /// Called when visiting GetStoreItems event (no payload).
    fn visit_get_store_items(&mut self) {}
    /// Called when visiting OnGetStoreItemsResult event.
    fn visit_on_get_store_items_result(&mut self, payload: &MyStoreBlock_OnGetStoreItemsResultPayload) {}
    /// Called when visiting OnPlayerStoreItemsChanged_Broacast event.
    fn visit_on_player_store_items_changed_broacast(&mut self, payload: &MyStoreBlock_OnPlayerStoreItemsChanged_BroacastPayload) {}
    /// Called when visiting BuyItem event.
    fn visit_buy_item(&mut self, payload: &MyStoreBlock_BuyItemPayload) {}
    /// Called when visiting OnBuyItemResult event.
    fn visit_on_buy_item_result(&mut self, payload: &MyStoreBlock_OnBuyItemResultPayload) {}
    /// Called when visiting SellItem event.
    fn visit_sell_item(&mut self, payload: &MyStoreBlock_SellItemPayload) {}
    /// Called when visiting OnSellItemResult event.
    fn visit_on_sell_item_result(&mut self, payload: &MyStoreBlock_OnSellItemResultPayload) {}
    /// Called when visiting GetConnectedGridInventories event (no payload).
    fn visit_get_connected_grid_inventories(&mut self) {}
    /// Called when visiting OnGetConnectedGridInventoriesResult event.
    fn visit_on_get_connected_grid_inventories_result(&mut self, payload: &MyStoreBlock_OnGetConnectedGridInventoriesResultPayload) {}
    /// Called when visiting GetGridInventories event (no payload).
    fn visit_get_grid_inventories(&mut self) {}
    /// Called when visiting OnGetGridInventoriesResult event.
    fn visit_on_get_grid_inventories_result(&mut self, payload: &MyStoreBlock_OnGetGridInventoriesResultPayload) {}
    /// Called when visiting CreateNewOffer event.
    fn visit_create_new_offer(&mut self, payload: &MyStoreBlock_CreateNewOfferPayload) {}
    /// Called when visiting OnCreateNewOfferResult event.
    fn visit_on_create_new_offer_result(&mut self, payload: &MyStoreBlock_OnCreateNewOfferResultPayload) {}
    /// Called when visiting CreateNewOrder event.
    fn visit_create_new_order(&mut self, payload: &MyStoreBlock_CreateNewOrderPayload) {}
    /// Called when visiting OnCreateNewOrderResult event.
    fn visit_on_create_new_order_result(&mut self, payload: &MyStoreBlock_OnCreateNewOrderResultPayload) {}
    /// Called when visiting CancelStoreItemServer event.
    fn visit_cancel_store_item_server(&mut self, payload: &MyStoreBlock_CancelStoreItemServerPayload) {}
    /// Called when visiting OnCancelStoreItemResult event.
    fn visit_on_cancel_store_item_result(&mut self, payload: &MyStoreBlock_OnCancelStoreItemResultPayload) {}
    /// Called when visiting ChangeBalance event.
    fn visit_change_balance(&mut self, payload: &MyStoreBlock_ChangeBalancePayload) {}
    /// Called when visiting OnChangeBalanceResult event.
    fn visit_on_change_balance_result(&mut self, payload: &MyStoreBlock_OnChangeBalanceResultPayload) {}
    /// Called when visiting ShowPreviewImplementation event.
    fn visit_show_preview_implementation(&mut self, payload: &MyStoreBlock_ShowPreviewImplementationPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyStoreBlockInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyStoreBlockInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::GetStoreItems => visitor.visit_get_store_items(),
            Self::OnGetStoreItemsResult(payload) => visitor.visit_on_get_store_items_result(payload),
            Self::OnPlayerStoreItemsChanged_Broacast(payload) => visitor.visit_on_player_store_items_changed_broacast(payload),
            Self::BuyItem(payload) => visitor.visit_buy_item(payload),
            Self::OnBuyItemResult(payload) => visitor.visit_on_buy_item_result(payload),
            Self::SellItem(payload) => visitor.visit_sell_item(payload),
            Self::OnSellItemResult(payload) => visitor.visit_on_sell_item_result(payload),
            Self::GetConnectedGridInventories => visitor.visit_get_connected_grid_inventories(),
            Self::OnGetConnectedGridInventoriesResult(payload) => visitor.visit_on_get_connected_grid_inventories_result(payload),
            Self::GetGridInventories => visitor.visit_get_grid_inventories(),
            Self::OnGetGridInventoriesResult(payload) => visitor.visit_on_get_grid_inventories_result(payload),
            Self::CreateNewOffer(payload) => visitor.visit_create_new_offer(payload),
            Self::OnCreateNewOfferResult(payload) => visitor.visit_on_create_new_offer_result(payload),
            Self::CreateNewOrder(payload) => visitor.visit_create_new_order(payload),
            Self::OnCreateNewOrderResult(payload) => visitor.visit_on_create_new_order_result(payload),
            Self::CancelStoreItemServer(payload) => visitor.visit_cancel_store_item_server(payload),
            Self::OnCancelStoreItemResult(payload) => visitor.visit_on_cancel_store_item_result(payload),
            Self::ChangeBalance(payload) => visitor.visit_change_balance(payload),
            Self::OnChangeBalanceResult(payload) => visitor.visit_on_change_balance_result(payload),
            Self::ShowPreviewImplementation(payload) => visitor.visit_show_preview_implementation(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyStoreBlockInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyStoreBlockInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyStoreBlockInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyStoreBlockInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyStoreBlockInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyStoreBlockInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyStoreBlockInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyStoreBlockInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyStoreBlockInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyStoreBlockInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyStoreBlockInstanceEvent::OnChangeDescription),
            Self::GetStoreItems => Some(MyStoreBlockInstanceEvent::GetStoreItems),
            Self::OnGetStoreItemsResult(_) => Some(MyStoreBlockInstanceEvent::OnGetStoreItemsResult),
            Self::OnPlayerStoreItemsChanged_Broacast(_) => Some(MyStoreBlockInstanceEvent::OnPlayerStoreItemsChanged_Broacast),
            Self::BuyItem(_) => Some(MyStoreBlockInstanceEvent::BuyItem),
            Self::OnBuyItemResult(_) => Some(MyStoreBlockInstanceEvent::OnBuyItemResult),
            Self::SellItem(_) => Some(MyStoreBlockInstanceEvent::SellItem),
            Self::OnSellItemResult(_) => Some(MyStoreBlockInstanceEvent::OnSellItemResult),
            Self::GetConnectedGridInventories => Some(MyStoreBlockInstanceEvent::GetConnectedGridInventories),
            Self::OnGetConnectedGridInventoriesResult(_) => Some(MyStoreBlockInstanceEvent::OnGetConnectedGridInventoriesResult),
            Self::GetGridInventories => Some(MyStoreBlockInstanceEvent::GetGridInventories),
            Self::OnGetGridInventoriesResult(_) => Some(MyStoreBlockInstanceEvent::OnGetGridInventoriesResult),
            Self::CreateNewOffer(_) => Some(MyStoreBlockInstanceEvent::CreateNewOffer),
            Self::OnCreateNewOfferResult(_) => Some(MyStoreBlockInstanceEvent::OnCreateNewOfferResult),
            Self::CreateNewOrder(_) => Some(MyStoreBlockInstanceEvent::CreateNewOrder),
            Self::OnCreateNewOrderResult(_) => Some(MyStoreBlockInstanceEvent::OnCreateNewOrderResult),
            Self::CancelStoreItemServer(_) => Some(MyStoreBlockInstanceEvent::CancelStoreItemServer),
            Self::OnCancelStoreItemResult(_) => Some(MyStoreBlockInstanceEvent::OnCancelStoreItemResult),
            Self::ChangeBalance(_) => Some(MyStoreBlockInstanceEvent::ChangeBalance),
            Self::OnChangeBalanceResult(_) => Some(MyStoreBlockInstanceEvent::OnChangeBalanceResult),
            Self::ShowPreviewImplementation(_) => Some(MyStoreBlockInstanceEvent::ShowPreviewImplementation),
            Self::Unknown { .. } => None,
        }
    }
}
