//! Instance events for SpaceEngineers.Game.Entities.Blocks.MySearchlight.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MySearchlight::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MySearchlight::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MySearchlight::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MySearchlight::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MySearchlight::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MySearchlight::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MySearchlight::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MySearchlight::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MySearchlight::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MySearchlight::RequestRelease instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySearchlight_RequestReleasePayload {
    pub previous_closed: BitBool,
}

/// Stable instance event identities for SpaceEngineers.Game.Entities.Blocks.MySearchlight.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MySearchlightInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: -1692662939
    sync_ControlledEntity_Used,
    /// Hash: 39741614
    RequestRelease,
}

impl MySearchlightInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::sync_ControlledEntity_Used => -1692662939,
            Self::RequestRelease => 39741614,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            -1692662939 => Some(Self::sync_ControlledEntity_Used),
            39741614 => Some(Self::RequestRelease),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.Entities.Blocks.MySearchlight.
///
/// Use `MySearchlightInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MySearchlightInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MySearchlight_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MySearchlight_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MySearchlight_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MySearchlight_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MySearchlight_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MySearchlight_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MySearchlight_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MySearchlight_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MySearchlight_OnChangeDescriptionPayload),
    /// sync_ControlledEntity_Used event (no payload)
    sync_ControlledEntity_Used,
    /// RequestRelease event payload
    RequestRelease(MySearchlight_RequestReleasePayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MySearchlightInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MySearchlightInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MySearchlight_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MySearchlight_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MySearchlight_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MySearchlight_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MySearchlightInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MySearchlight_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MySearchlight_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MySearchlight_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MySearchlight_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MySearchlight_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::sync_ControlledEntity_Used => Ok(MySearchlightInstanceEventPayload::sync_ControlledEntity_Used),
            Self::RequestRelease => {
                let (_, payload) = MySearchlight_RequestReleasePayload::from_bytes((bytes, 0))?;
                Ok(MySearchlightInstanceEventPayload::RequestRelease(payload))
            }
        }
    }
}

/// Parse an instance event payload for MySearchlight from raw event hash and bytes.
pub fn parse_my_searchlight_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MySearchlightInstanceEventPayload, deku::DekuError> {
    match MySearchlightInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MySearchlightInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MySearchlight instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MySearchlightInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MySearchlight_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MySearchlight_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MySearchlight_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MySearchlight_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MySearchlight_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MySearchlight_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MySearchlight_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MySearchlight_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MySearchlight_OnChangeDescriptionPayload) {}
    /// Called when visiting sync_ControlledEntity_Used event (no payload).
    fn visit_sync_controlled_entity_used(&mut self) {}
    /// Called when visiting RequestRelease event.
    fn visit_request_release(&mut self, payload: &MySearchlight_RequestReleasePayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MySearchlightInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MySearchlightInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::sync_ControlledEntity_Used => visitor.visit_sync_controlled_entity_used(),
            Self::RequestRelease(payload) => visitor.visit_request_release(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MySearchlightInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MySearchlightInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MySearchlightInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MySearchlightInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MySearchlightInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MySearchlightInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MySearchlightInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MySearchlightInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MySearchlightInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MySearchlightInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MySearchlightInstanceEvent::OnChangeDescription),
            Self::sync_ControlledEntity_Used => Some(MySearchlightInstanceEvent::sync_ControlledEntity_Used),
            Self::RequestRelease(_) => Some(MySearchlightInstanceEvent::RequestRelease),
            Self::Unknown { .. } => None,
        }
    }
}
