//! Instance events for SpaceEngineers.Game.Entities.Blocks.MySurvivalKit.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MySurvivalKit::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MySurvivalKit::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MySurvivalKit::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MySurvivalKit::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MySurvivalKit::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MySurvivalKit::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MySurvivalKit::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MySurvivalKit::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MySurvivalKit::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MySurvivalKit::OnAddQueueItemRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnAddQueueItemRequestPayload {
    pub idx: BitAligned<i32>,
    pub def_id: space_engineers_sys::types::SerializableDefinitionId,
    pub ammount: space_engineers_sys::types::MyFixedPoint,
}

/// Payload for MySurvivalKit::OnAddQueueItemSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnAddQueueItemSuccessPayload {
    pub idx: BitAligned<i32>,
    pub def_id: space_engineers_sys::types::SerializableDefinitionId,
    pub ammount: space_engineers_sys::types::MyFixedPoint,
}

/// Payload for MySurvivalKit::OnMoveQueueItemCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnMoveQueueItemCallbackPayload {
    pub src_item_id: BitAligned<u32>,
    pub dst_idx: BitAligned<i32>,
}

/// Payload for MySurvivalKit::OnRemoveQueueItemRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnRemoveQueueItemRequestPayload {
    pub idx: BitAligned<i32>,
    pub amount: space_engineers_sys::types::MyFixedPoint,
    pub progress: BitAligned<f32>,
}

/// Payload for MySurvivalKit::OnRemoveQueueItem instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_OnRemoveQueueItemPayload {
    pub idx: BitAligned<i32>,
    pub amount: space_engineers_sys::types::MyFixedPoint,
    pub progress: BitAligned<f32>,
}

/// Payload for MySurvivalKit::ModeSwitchCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_ModeSwitchCallbackPayload {
    pub disassemble_enabled: BitBool,
}

/// Payload for MySurvivalKit::ModeSwitchClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_ModeSwitchClientPayload {
    pub disassemble_enabled: BitBool,
}

/// Payload for MySurvivalKit::RepeatEnabledCallback instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_RepeatEnabledCallbackPayload {
    pub disassemble_enabled: BitBool,
    pub repeat_enable: BitBool,
}

/// Payload for MySurvivalKit::RequestSupport instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_RequestSupportPayload {
    pub user_id: BitAligned<i64>,
}

/// Payload for MySurvivalKit::SetSpawnTextEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MySurvivalKit_SetSpawnTextEventPayload {
    pub text: VarString,
}

/// Stable instance event identities for SpaceEngineers.Game.Entities.Blocks.MySurvivalKit.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MySurvivalKitInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: 461148917
    OnAddQueueItemRequest,
    /// Hash: 1487689679
    OnAddQueueItemSuccess,
    /// Hash: 898486702
    OnMoveQueueItemCallback,
    /// Hash: 1720972571
    ClearQueueRequest,
    /// Hash: 880307177
    OnRemoveQueueItemRequest,
    /// Hash: -1022361959
    OnRemoveQueueItem,
    /// Hash: -48352404
    ModeSwitchCallback,
    /// Hash: 344903392
    ModeSwitchClient,
    /// Hash: -423371665
    RepeatEnabledCallback,
    /// Hash: -224683126
    DisassembleAllCallback,
    /// Hash: -1444377254
    RequestSupport,
    /// Hash: 1518802751
    SetSpawnTextEvent,
}

impl MySurvivalKitInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::OnAddQueueItemRequest => 461148917,
            Self::OnAddQueueItemSuccess => 1487689679,
            Self::OnMoveQueueItemCallback => 898486702,
            Self::ClearQueueRequest => 1720972571,
            Self::OnRemoveQueueItemRequest => 880307177,
            Self::OnRemoveQueueItem => -1022361959,
            Self::ModeSwitchCallback => -48352404,
            Self::ModeSwitchClient => 344903392,
            Self::RepeatEnabledCallback => -423371665,
            Self::DisassembleAllCallback => -224683126,
            Self::RequestSupport => -1444377254,
            Self::SetSpawnTextEvent => 1518802751,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            461148917 => Some(Self::OnAddQueueItemRequest),
            1487689679 => Some(Self::OnAddQueueItemSuccess),
            898486702 => Some(Self::OnMoveQueueItemCallback),
            1720972571 => Some(Self::ClearQueueRequest),
            880307177 => Some(Self::OnRemoveQueueItemRequest),
            -1022361959 => Some(Self::OnRemoveQueueItem),
            -48352404 => Some(Self::ModeSwitchCallback),
            344903392 => Some(Self::ModeSwitchClient),
            -423371665 => Some(Self::RepeatEnabledCallback),
            -224683126 => Some(Self::DisassembleAllCallback),
            -1444377254 => Some(Self::RequestSupport),
            1518802751 => Some(Self::SetSpawnTextEvent),
            _ => None,
        }
    }
}

/// Parsed instance event payload for SpaceEngineers.Game.Entities.Blocks.MySurvivalKit.
///
/// Use `MySurvivalKitInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MySurvivalKitInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MySurvivalKit_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MySurvivalKit_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MySurvivalKit_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MySurvivalKit_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MySurvivalKit_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MySurvivalKit_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MySurvivalKit_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MySurvivalKit_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MySurvivalKit_OnChangeDescriptionPayload),
    /// OnAddQueueItemRequest event payload
    OnAddQueueItemRequest(MySurvivalKit_OnAddQueueItemRequestPayload),
    /// OnAddQueueItemSuccess event payload
    OnAddQueueItemSuccess(MySurvivalKit_OnAddQueueItemSuccessPayload),
    /// OnMoveQueueItemCallback event payload
    OnMoveQueueItemCallback(MySurvivalKit_OnMoveQueueItemCallbackPayload),
    /// ClearQueueRequest event (no payload)
    ClearQueueRequest,
    /// OnRemoveQueueItemRequest event payload
    OnRemoveQueueItemRequest(MySurvivalKit_OnRemoveQueueItemRequestPayload),
    /// OnRemoveQueueItem event payload
    OnRemoveQueueItem(MySurvivalKit_OnRemoveQueueItemPayload),
    /// ModeSwitchCallback event payload
    ModeSwitchCallback(MySurvivalKit_ModeSwitchCallbackPayload),
    /// ModeSwitchClient event payload
    ModeSwitchClient(MySurvivalKit_ModeSwitchClientPayload),
    /// RepeatEnabledCallback event payload
    RepeatEnabledCallback(MySurvivalKit_RepeatEnabledCallbackPayload),
    /// DisassembleAllCallback event (no payload)
    DisassembleAllCallback,
    /// RequestSupport event payload
    RequestSupport(MySurvivalKit_RequestSupportPayload),
    /// SetSpawnTextEvent event payload
    SetSpawnTextEvent(MySurvivalKit_SetSpawnTextEventPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MySurvivalKitInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MySurvivalKitInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MySurvivalKit_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MySurvivalKit_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MySurvivalKit_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MySurvivalKit_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MySurvivalKitInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MySurvivalKit_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MySurvivalKit_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MySurvivalKit_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MySurvivalKit_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MySurvivalKit_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::OnAddQueueItemRequest => {
                let (_, payload) = MySurvivalKit_OnAddQueueItemRequestPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnAddQueueItemRequest(payload))
            }
            Self::OnAddQueueItemSuccess => {
                let (_, payload) = MySurvivalKit_OnAddQueueItemSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnAddQueueItemSuccess(payload))
            }
            Self::OnMoveQueueItemCallback => {
                let (_, payload) = MySurvivalKit_OnMoveQueueItemCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnMoveQueueItemCallback(payload))
            }
            Self::ClearQueueRequest => Ok(MySurvivalKitInstanceEventPayload::ClearQueueRequest),
            Self::OnRemoveQueueItemRequest => {
                let (_, payload) = MySurvivalKit_OnRemoveQueueItemRequestPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnRemoveQueueItemRequest(payload))
            }
            Self::OnRemoveQueueItem => {
                let (_, payload) = MySurvivalKit_OnRemoveQueueItemPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::OnRemoveQueueItem(payload))
            }
            Self::ModeSwitchCallback => {
                let (_, payload) = MySurvivalKit_ModeSwitchCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::ModeSwitchCallback(payload))
            }
            Self::ModeSwitchClient => {
                let (_, payload) = MySurvivalKit_ModeSwitchClientPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::ModeSwitchClient(payload))
            }
            Self::RepeatEnabledCallback => {
                let (_, payload) = MySurvivalKit_RepeatEnabledCallbackPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::RepeatEnabledCallback(payload))
            }
            Self::DisassembleAllCallback => Ok(MySurvivalKitInstanceEventPayload::DisassembleAllCallback),
            Self::RequestSupport => {
                let (_, payload) = MySurvivalKit_RequestSupportPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::RequestSupport(payload))
            }
            Self::SetSpawnTextEvent => {
                let (_, payload) = MySurvivalKit_SetSpawnTextEventPayload::from_bytes((bytes, 0))?;
                Ok(MySurvivalKitInstanceEventPayload::SetSpawnTextEvent(payload))
            }
        }
    }
}

/// Parse an instance event payload for MySurvivalKit from raw event hash and bytes.
pub fn parse_my_survival_kit_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MySurvivalKitInstanceEventPayload, deku::DekuError> {
    match MySurvivalKitInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MySurvivalKitInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MySurvivalKit instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MySurvivalKitInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MySurvivalKit_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MySurvivalKit_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MySurvivalKit_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MySurvivalKit_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MySurvivalKit_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MySurvivalKit_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MySurvivalKit_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MySurvivalKit_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MySurvivalKit_OnChangeDescriptionPayload) {}
    /// Called when visiting OnAddQueueItemRequest event.
    fn visit_on_add_queue_item_request(&mut self, payload: &MySurvivalKit_OnAddQueueItemRequestPayload) {}
    /// Called when visiting OnAddQueueItemSuccess event.
    fn visit_on_add_queue_item_success(&mut self, payload: &MySurvivalKit_OnAddQueueItemSuccessPayload) {}
    /// Called when visiting OnMoveQueueItemCallback event.
    fn visit_on_move_queue_item_callback(&mut self, payload: &MySurvivalKit_OnMoveQueueItemCallbackPayload) {}
    /// Called when visiting ClearQueueRequest event (no payload).
    fn visit_clear_queue_request(&mut self) {}
    /// Called when visiting OnRemoveQueueItemRequest event.
    fn visit_on_remove_queue_item_request(&mut self, payload: &MySurvivalKit_OnRemoveQueueItemRequestPayload) {}
    /// Called when visiting OnRemoveQueueItem event.
    fn visit_on_remove_queue_item(&mut self, payload: &MySurvivalKit_OnRemoveQueueItemPayload) {}
    /// Called when visiting ModeSwitchCallback event.
    fn visit_mode_switch_callback(&mut self, payload: &MySurvivalKit_ModeSwitchCallbackPayload) {}
    /// Called when visiting ModeSwitchClient event.
    fn visit_mode_switch_client(&mut self, payload: &MySurvivalKit_ModeSwitchClientPayload) {}
    /// Called when visiting RepeatEnabledCallback event.
    fn visit_repeat_enabled_callback(&mut self, payload: &MySurvivalKit_RepeatEnabledCallbackPayload) {}
    /// Called when visiting DisassembleAllCallback event (no payload).
    fn visit_disassemble_all_callback(&mut self) {}
    /// Called when visiting RequestSupport event.
    fn visit_request_support(&mut self, payload: &MySurvivalKit_RequestSupportPayload) {}
    /// Called when visiting SetSpawnTextEvent event.
    fn visit_set_spawn_text_event(&mut self, payload: &MySurvivalKit_SetSpawnTextEventPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MySurvivalKitInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MySurvivalKitInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::OnAddQueueItemRequest(payload) => visitor.visit_on_add_queue_item_request(payload),
            Self::OnAddQueueItemSuccess(payload) => visitor.visit_on_add_queue_item_success(payload),
            Self::OnMoveQueueItemCallback(payload) => visitor.visit_on_move_queue_item_callback(payload),
            Self::ClearQueueRequest => visitor.visit_clear_queue_request(),
            Self::OnRemoveQueueItemRequest(payload) => visitor.visit_on_remove_queue_item_request(payload),
            Self::OnRemoveQueueItem(payload) => visitor.visit_on_remove_queue_item(payload),
            Self::ModeSwitchCallback(payload) => visitor.visit_mode_switch_callback(payload),
            Self::ModeSwitchClient(payload) => visitor.visit_mode_switch_client(payload),
            Self::RepeatEnabledCallback(payload) => visitor.visit_repeat_enabled_callback(payload),
            Self::DisassembleAllCallback => visitor.visit_disassemble_all_callback(),
            Self::RequestSupport(payload) => visitor.visit_request_support(payload),
            Self::SetSpawnTextEvent(payload) => visitor.visit_set_spawn_text_event(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MySurvivalKitInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MySurvivalKitInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MySurvivalKitInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MySurvivalKitInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MySurvivalKitInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MySurvivalKitInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MySurvivalKitInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MySurvivalKitInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MySurvivalKitInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MySurvivalKitInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MySurvivalKitInstanceEvent::OnChangeDescription),
            Self::OnAddQueueItemRequest(_) => Some(MySurvivalKitInstanceEvent::OnAddQueueItemRequest),
            Self::OnAddQueueItemSuccess(_) => Some(MySurvivalKitInstanceEvent::OnAddQueueItemSuccess),
            Self::OnMoveQueueItemCallback(_) => Some(MySurvivalKitInstanceEvent::OnMoveQueueItemCallback),
            Self::ClearQueueRequest => Some(MySurvivalKitInstanceEvent::ClearQueueRequest),
            Self::OnRemoveQueueItemRequest(_) => Some(MySurvivalKitInstanceEvent::OnRemoveQueueItemRequest),
            Self::OnRemoveQueueItem(_) => Some(MySurvivalKitInstanceEvent::OnRemoveQueueItem),
            Self::ModeSwitchCallback(_) => Some(MySurvivalKitInstanceEvent::ModeSwitchCallback),
            Self::ModeSwitchClient(_) => Some(MySurvivalKitInstanceEvent::ModeSwitchClient),
            Self::RepeatEnabledCallback(_) => Some(MySurvivalKitInstanceEvent::RepeatEnabledCallback),
            Self::DisassembleAllCallback => Some(MySurvivalKitInstanceEvent::DisassembleAllCallback),
            Self::RequestSupport(_) => Some(MySurvivalKitInstanceEvent::RequestSupport),
            Self::SetSpawnTextEvent(_) => Some(MySurvivalKitInstanceEvent::SetSpawnTextEvent),
            Self::Unknown { .. } => None,
        }
    }
}
