//! Instance events for Sandbox.Game.Entities.Cube.MyShipConnector.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyShipConnector::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyShipConnector::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyShipConnector::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyShipConnector::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyShipConnector::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyShipConnector::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyShipConnector::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyShipConnector::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyShipConnector::OnChangeDescription instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_OnChangeDescriptionPayload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyShipConnector::NotifyDisconnectTime instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_NotifyDisconnectTimePayload {
    pub set_trading_protection: BitBool,
}

/// Payload for MyShipConnector::PlayActionSoundAndParticle instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyShipConnector_PlayActionSoundAndParticlePayload {
    pub position: Vector3D,
    pub velocity: Vector3F,
}

/// Stable instance event identities for Sandbox.Game.Entities.Cube.MyShipConnector.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyShipConnectorInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription,
    /// Hash: -1444664607
    TryConnect,
    /// Hash: -730371870
    TryDisconnect,
    /// Hash: -871860903
    NotifyDisconnectTime,
    /// Hash: 2076250254
    PlayActionSoundAndParticle,
    /// Hash: 904598989
    PlayActionSound,
}

impl MyShipConnectorInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription => 348586933,
            Self::TryConnect => -1444664607,
            Self::TryDisconnect => -730371870,
            Self::NotifyDisconnectTime => -871860903,
            Self::PlayActionSoundAndParticle => 2076250254,
            Self::PlayActionSound => 904598989,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription),
            -1444664607 => Some(Self::TryConnect),
            -730371870 => Some(Self::TryDisconnect),
            -871860903 => Some(Self::NotifyDisconnectTime),
            2076250254 => Some(Self::PlayActionSoundAndParticle),
            904598989 => Some(Self::PlayActionSound),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Cube.MyShipConnector.
///
/// Use `MyShipConnectorInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyShipConnectorInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyShipConnector_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyShipConnector_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyShipConnector_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyShipConnector_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyShipConnector_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyShipConnector_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyShipConnector_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyShipConnector_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription event payload
    OnChangeDescription(MyShipConnector_OnChangeDescriptionPayload),
    /// TryConnect event (no payload)
    TryConnect,
    /// TryDisconnect event (no payload)
    TryDisconnect,
    /// NotifyDisconnectTime event payload
    NotifyDisconnectTime(MyShipConnector_NotifyDisconnectTimePayload),
    /// PlayActionSoundAndParticle event payload
    PlayActionSoundAndParticle(MyShipConnector_PlayActionSoundAndParticlePayload),
    /// PlayActionSound event (no payload)
    PlayActionSound,
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyShipConnectorInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyShipConnectorInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyShipConnector_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyShipConnector_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyShipConnector_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyShipConnector_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyShipConnectorInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyShipConnector_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyShipConnector_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyShipConnector_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyShipConnector_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription => {
                let (_, payload) = MyShipConnector_OnChangeDescriptionPayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::OnChangeDescription(payload))
            }
            Self::TryConnect => Ok(MyShipConnectorInstanceEventPayload::TryConnect),
            Self::TryDisconnect => Ok(MyShipConnectorInstanceEventPayload::TryDisconnect),
            Self::NotifyDisconnectTime => {
                let (_, payload) = MyShipConnector_NotifyDisconnectTimePayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::NotifyDisconnectTime(payload))
            }
            Self::PlayActionSoundAndParticle => {
                let (_, payload) = MyShipConnector_PlayActionSoundAndParticlePayload::from_bytes((bytes, 0))?;
                Ok(MyShipConnectorInstanceEventPayload::PlayActionSoundAndParticle(payload))
            }
            Self::PlayActionSound => Ok(MyShipConnectorInstanceEventPayload::PlayActionSound),
        }
    }
}

/// Parse an instance event payload for MyShipConnector from raw event hash and bytes.
pub fn parse_my_ship_connector_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyShipConnectorInstanceEventPayload, deku::DekuError> {
    match MyShipConnectorInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyShipConnectorInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyShipConnector instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyShipConnectorInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyShipConnector_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyShipConnector_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyShipConnector_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyShipConnector_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyShipConnector_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyShipConnector_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyShipConnector_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyShipConnector_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription event.
    fn visit_on_change_description(&mut self, payload: &MyShipConnector_OnChangeDescriptionPayload) {}
    /// Called when visiting TryConnect event (no payload).
    fn visit_try_connect(&mut self) {}
    /// Called when visiting TryDisconnect event (no payload).
    fn visit_try_disconnect(&mut self) {}
    /// Called when visiting NotifyDisconnectTime event.
    fn visit_notify_disconnect_time(&mut self, payload: &MyShipConnector_NotifyDisconnectTimePayload) {}
    /// Called when visiting PlayActionSoundAndParticle event.
    fn visit_play_action_sound_and_particle(&mut self, payload: &MyShipConnector_PlayActionSoundAndParticlePayload) {}
    /// Called when visiting PlayActionSound event (no payload).
    fn visit_play_action_sound(&mut self) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyShipConnectorInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyShipConnectorInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription(payload) => visitor.visit_on_change_description(payload),
            Self::TryConnect => visitor.visit_try_connect(),
            Self::TryDisconnect => visitor.visit_try_disconnect(),
            Self::NotifyDisconnectTime(payload) => visitor.visit_notify_disconnect_time(payload),
            Self::PlayActionSoundAndParticle(payload) => visitor.visit_play_action_sound_and_particle(payload),
            Self::PlayActionSound => visitor.visit_play_action_sound(),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyShipConnectorInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyShipConnectorInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyShipConnectorInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyShipConnectorInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyShipConnectorInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyShipConnectorInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyShipConnectorInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyShipConnectorInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyShipConnectorInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyShipConnectorInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription(_) => Some(MyShipConnectorInstanceEvent::OnChangeDescription),
            Self::TryConnect => Some(MyShipConnectorInstanceEvent::TryConnect),
            Self::TryDisconnect => Some(MyShipConnectorInstanceEvent::TryDisconnect),
            Self::NotifyDisconnectTime(_) => Some(MyShipConnectorInstanceEvent::NotifyDisconnectTime),
            Self::PlayActionSoundAndParticle(_) => Some(MyShipConnectorInstanceEvent::PlayActionSoundAndParticle),
            Self::PlayActionSound => Some(MyShipConnectorInstanceEvent::PlayActionSound),
            Self::Unknown { .. } => None,
        }
    }
}
