//! Instance events for Sandbox.Game.Entities.Blocks.MyTextPanel.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyTextPanel::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyTextPanel::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyTextPanel::OnChangeOpenRequest_2 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenRequest_2Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyTextPanel::OnChangeOpenSuccess_3 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenSuccess_3Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyTextPanel::OnSelectImageSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnSelectImageSuccessPayload {
    pub panel_index: BitAligned<i32>,
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyTextPanel::SelectPanelServer instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_SelectPanelServerPayload {
    pub index: BitAligned<i32>,
}

/// Payload for MyTextPanel::OnChangeOpenSuccess_7 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenSuccess_7Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnChangeOpenRequest_8 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenRequest_8Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnChangeDescription_9 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeDescription_9Payload {
    pub panel_id: BitAligned<i32>,
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnRemoveSelectedImageRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnRemoveSelectedImageRequestPayload {
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyTextPanel::OnSelectImageRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnSelectImageRequestPayload {
    pub selection: VarVec<BitAligned<i32>>,
}

/// Payload for MyTextPanel::OnChangeDescription_12 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeDescription_12Payload {
    pub description: VarString,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnChangeTitle instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeTitlePayload {
    pub title: VarString,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnChangeOpenRequest_14 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenRequest_14Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Payload for MyTextPanel::OnChangeOpenSuccess_15 instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTextPanel_OnChangeOpenSuccess_15Payload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
    pub is_public: BitBool,
}

/// Stable instance event identities for Sandbox.Game.Entities.Blocks.MyTextPanel.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyTextPanelInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest_2,
    /// Hash: 261877592
    OnChangeOpenSuccess_3,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 820627551
    OnSelectImageSuccess,
    /// Hash: -1079702347
    SelectPanelServer,
    /// Hash: 1461148993
    OnChangeOpenSuccess_7,
    /// Hash: 577727535
    OnChangeOpenRequest_8,
    /// Hash: 348586933
    OnChangeDescription_9,
    /// Hash: 1742829248
    OnRemoveSelectedImageRequest,
    /// Hash: 211481554
    OnSelectImageRequest,
    /// Hash: -975030822
    OnChangeDescription_12,
    /// Hash: -1388816913
    OnChangeTitle,
    /// Hash: 2041446479
    OnChangeOpenRequest_14,
    /// Hash: 1779787105
    OnChangeOpenSuccess_15,
}

impl MyTextPanelInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest_2 => -76257694,
            Self::OnChangeOpenSuccess_3 => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::OnSelectImageSuccess => 820627551,
            Self::SelectPanelServer => -1079702347,
            Self::OnChangeOpenSuccess_7 => 1461148993,
            Self::OnChangeOpenRequest_8 => 577727535,
            Self::OnChangeDescription_9 => 348586933,
            Self::OnRemoveSelectedImageRequest => 1742829248,
            Self::OnSelectImageRequest => 211481554,
            Self::OnChangeDescription_12 => -975030822,
            Self::OnChangeTitle => -1388816913,
            Self::OnChangeOpenRequest_14 => 2041446479,
            Self::OnChangeOpenSuccess_15 => 1779787105,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest_2),
            261877592 => Some(Self::OnChangeOpenSuccess_3),
            271720064 => Some(Self::RemoveContainerDropComponent),
            820627551 => Some(Self::OnSelectImageSuccess),
            -1079702347 => Some(Self::SelectPanelServer),
            1461148993 => Some(Self::OnChangeOpenSuccess_7),
            577727535 => Some(Self::OnChangeOpenRequest_8),
            348586933 => Some(Self::OnChangeDescription_9),
            1742829248 => Some(Self::OnRemoveSelectedImageRequest),
            211481554 => Some(Self::OnSelectImageRequest),
            -975030822 => Some(Self::OnChangeDescription_12),
            -1388816913 => Some(Self::OnChangeTitle),
            2041446479 => Some(Self::OnChangeOpenRequest_14),
            1779787105 => Some(Self::OnChangeOpenSuccess_15),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Blocks.MyTextPanel.
///
/// Use `MyTextPanelInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyTextPanelInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyTextPanel_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyTextPanel_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest_2 event payload
    OnChangeOpenRequest_2(MyTextPanel_OnChangeOpenRequest_2Payload),
    /// OnChangeOpenSuccess_3 event payload
    OnChangeOpenSuccess_3(MyTextPanel_OnChangeOpenSuccess_3Payload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// OnSelectImageSuccess event payload
    OnSelectImageSuccess(MyTextPanel_OnSelectImageSuccessPayload),
    /// SelectPanelServer event payload
    SelectPanelServer(MyTextPanel_SelectPanelServerPayload),
    /// OnChangeOpenSuccess_7 event payload
    OnChangeOpenSuccess_7(MyTextPanel_OnChangeOpenSuccess_7Payload),
    /// OnChangeOpenRequest_8 event payload
    OnChangeOpenRequest_8(MyTextPanel_OnChangeOpenRequest_8Payload),
    /// OnChangeDescription_9 event payload
    OnChangeDescription_9(MyTextPanel_OnChangeDescription_9Payload),
    /// OnRemoveSelectedImageRequest event payload
    OnRemoveSelectedImageRequest(MyTextPanel_OnRemoveSelectedImageRequestPayload),
    /// OnSelectImageRequest event payload
    OnSelectImageRequest(MyTextPanel_OnSelectImageRequestPayload),
    /// OnChangeDescription_12 event payload
    OnChangeDescription_12(MyTextPanel_OnChangeDescription_12Payload),
    /// OnChangeTitle event payload
    OnChangeTitle(MyTextPanel_OnChangeTitlePayload),
    /// OnChangeOpenRequest_14 event payload
    OnChangeOpenRequest_14(MyTextPanel_OnChangeOpenRequest_14Payload),
    /// OnChangeOpenSuccess_15 event payload
    OnChangeOpenSuccess_15(MyTextPanel_OnChangeOpenSuccess_15Payload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyTextPanelInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyTextPanelInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyTextPanel_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyTextPanel_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest_2 => {
                let (_, payload) = MyTextPanel_OnChangeOpenRequest_2Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenRequest_2(payload))
            }
            Self::OnChangeOpenSuccess_3 => {
                let (_, payload) = MyTextPanel_OnChangeOpenSuccess_3Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenSuccess_3(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyTextPanelInstanceEventPayload::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess => {
                let (_, payload) = MyTextPanel_OnSelectImageSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnSelectImageSuccess(payload))
            }
            Self::SelectPanelServer => {
                let (_, payload) = MyTextPanel_SelectPanelServerPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::SelectPanelServer(payload))
            }
            Self::OnChangeOpenSuccess_7 => {
                let (_, payload) = MyTextPanel_OnChangeOpenSuccess_7Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenSuccess_7(payload))
            }
            Self::OnChangeOpenRequest_8 => {
                let (_, payload) = MyTextPanel_OnChangeOpenRequest_8Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenRequest_8(payload))
            }
            Self::OnChangeDescription_9 => {
                let (_, payload) = MyTextPanel_OnChangeDescription_9Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeDescription_9(payload))
            }
            Self::OnRemoveSelectedImageRequest => {
                let (_, payload) = MyTextPanel_OnRemoveSelectedImageRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnRemoveSelectedImageRequest(payload))
            }
            Self::OnSelectImageRequest => {
                let (_, payload) = MyTextPanel_OnSelectImageRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnSelectImageRequest(payload))
            }
            Self::OnChangeDescription_12 => {
                let (_, payload) = MyTextPanel_OnChangeDescription_12Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeDescription_12(payload))
            }
            Self::OnChangeTitle => {
                let (_, payload) = MyTextPanel_OnChangeTitlePayload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeTitle(payload))
            }
            Self::OnChangeOpenRequest_14 => {
                let (_, payload) = MyTextPanel_OnChangeOpenRequest_14Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenRequest_14(payload))
            }
            Self::OnChangeOpenSuccess_15 => {
                let (_, payload) = MyTextPanel_OnChangeOpenSuccess_15Payload::from_bytes((bytes, 0))?;
                Ok(MyTextPanelInstanceEventPayload::OnChangeOpenSuccess_15(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyTextPanel from raw event hash and bytes.
pub fn parse_my_text_panel_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyTextPanelInstanceEventPayload, deku::DekuError> {
    match MyTextPanelInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyTextPanelInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyTextPanel instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyTextPanelInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyTextPanel_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyTextPanel_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest_2 event.
    fn visit_on_change_open_request_2(&mut self, payload: &MyTextPanel_OnChangeOpenRequest_2Payload) {}
    /// Called when visiting OnChangeOpenSuccess_3 event.
    fn visit_on_change_open_success_3(&mut self, payload: &MyTextPanel_OnChangeOpenSuccess_3Payload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting OnSelectImageSuccess event.
    fn visit_on_select_image_success(&mut self, payload: &MyTextPanel_OnSelectImageSuccessPayload) {}
    /// Called when visiting SelectPanelServer event.
    fn visit_select_panel_server(&mut self, payload: &MyTextPanel_SelectPanelServerPayload) {}
    /// Called when visiting OnChangeOpenSuccess_7 event.
    fn visit_on_change_open_success_7(&mut self, payload: &MyTextPanel_OnChangeOpenSuccess_7Payload) {}
    /// Called when visiting OnChangeOpenRequest_8 event.
    fn visit_on_change_open_request_8(&mut self, payload: &MyTextPanel_OnChangeOpenRequest_8Payload) {}
    /// Called when visiting OnChangeDescription_9 event.
    fn visit_on_change_description_9(&mut self, payload: &MyTextPanel_OnChangeDescription_9Payload) {}
    /// Called when visiting OnRemoveSelectedImageRequest event.
    fn visit_on_remove_selected_image_request(&mut self, payload: &MyTextPanel_OnRemoveSelectedImageRequestPayload) {}
    /// Called when visiting OnSelectImageRequest event.
    fn visit_on_select_image_request(&mut self, payload: &MyTextPanel_OnSelectImageRequestPayload) {}
    /// Called when visiting OnChangeDescription_12 event.
    fn visit_on_change_description_12(&mut self, payload: &MyTextPanel_OnChangeDescription_12Payload) {}
    /// Called when visiting OnChangeTitle event.
    fn visit_on_change_title(&mut self, payload: &MyTextPanel_OnChangeTitlePayload) {}
    /// Called when visiting OnChangeOpenRequest_14 event.
    fn visit_on_change_open_request_14(&mut self, payload: &MyTextPanel_OnChangeOpenRequest_14Payload) {}
    /// Called when visiting OnChangeOpenSuccess_15 event.
    fn visit_on_change_open_success_15(&mut self, payload: &MyTextPanel_OnChangeOpenSuccess_15Payload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyTextPanelInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyTextPanelInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest_2(payload) => visitor.visit_on_change_open_request_2(payload),
            Self::OnChangeOpenSuccess_3(payload) => visitor.visit_on_change_open_success_3(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::OnSelectImageSuccess(payload) => visitor.visit_on_select_image_success(payload),
            Self::SelectPanelServer(payload) => visitor.visit_select_panel_server(payload),
            Self::OnChangeOpenSuccess_7(payload) => visitor.visit_on_change_open_success_7(payload),
            Self::OnChangeOpenRequest_8(payload) => visitor.visit_on_change_open_request_8(payload),
            Self::OnChangeDescription_9(payload) => visitor.visit_on_change_description_9(payload),
            Self::OnRemoveSelectedImageRequest(payload) => visitor.visit_on_remove_selected_image_request(payload),
            Self::OnSelectImageRequest(payload) => visitor.visit_on_select_image_request(payload),
            Self::OnChangeDescription_12(payload) => visitor.visit_on_change_description_12(payload),
            Self::OnChangeTitle(payload) => visitor.visit_on_change_title(payload),
            Self::OnChangeOpenRequest_14(payload) => visitor.visit_on_change_open_request_14(payload),
            Self::OnChangeOpenSuccess_15(payload) => visitor.visit_on_change_open_success_15(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyTextPanelInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyTextPanelInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyTextPanelInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest_2(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenRequest_2),
            Self::OnChangeOpenSuccess_3(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenSuccess_3),
            Self::RemoveContainerDropComponent => Some(MyTextPanelInstanceEvent::RemoveContainerDropComponent),
            Self::OnSelectImageSuccess(_) => Some(MyTextPanelInstanceEvent::OnSelectImageSuccess),
            Self::SelectPanelServer(_) => Some(MyTextPanelInstanceEvent::SelectPanelServer),
            Self::OnChangeOpenSuccess_7(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenSuccess_7),
            Self::OnChangeOpenRequest_8(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenRequest_8),
            Self::OnChangeDescription_9(_) => Some(MyTextPanelInstanceEvent::OnChangeDescription_9),
            Self::OnRemoveSelectedImageRequest(_) => Some(MyTextPanelInstanceEvent::OnRemoveSelectedImageRequest),
            Self::OnSelectImageRequest(_) => Some(MyTextPanelInstanceEvent::OnSelectImageRequest),
            Self::OnChangeDescription_12(_) => Some(MyTextPanelInstanceEvent::OnChangeDescription_12),
            Self::OnChangeTitle(_) => Some(MyTextPanelInstanceEvent::OnChangeTitle),
            Self::OnChangeOpenRequest_14(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenRequest_14),
            Self::OnChangeOpenSuccess_15(_) => Some(MyTextPanelInstanceEvent::OnChangeOpenSuccess_15),
            Self::Unknown { .. } => None,
        }
    }
}
