//! Instance events for Sandbox.Game.Entities.Cube.MyTerminalBlock.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyTerminalBlock::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTerminalBlock_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyTerminalBlock::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTerminalBlock_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyTerminalBlock::OnChangeOpenRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTerminalBlock_OnChangeOpenRequestPayload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyTerminalBlock::OnChangeOpenSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyTerminalBlock_OnChangeOpenSuccessPayload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Stable instance event identities for Sandbox.Game.Entities.Cube.MyTerminalBlock.
///
/// Use `VersionSchema` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyTerminalBlockInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest,
    /// Hash: 261877592
    OnChangeOpenSuccess,
    /// Hash: 271720064
    RemoveContainerDropComponent,
}

impl MyTerminalBlockInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest => -76257694,
            Self::OnChangeOpenSuccess => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest),
            261877592 => Some(Self::OnChangeOpenSuccess),
            271720064 => Some(Self::RemoveContainerDropComponent),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Cube.MyTerminalBlock.
///
/// Use `MyTerminalBlockInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyTerminalBlockInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyTerminalBlock_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyTerminalBlock_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest event payload
    OnChangeOpenRequest(MyTerminalBlock_OnChangeOpenRequestPayload),
    /// OnChangeOpenSuccess event payload
    OnChangeOpenSuccess(MyTerminalBlock_OnChangeOpenSuccessPayload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyTerminalBlockInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyTerminalBlockInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyTerminalBlock_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyTerminalBlockInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyTerminalBlock_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyTerminalBlockInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest => {
                let (_, payload) = MyTerminalBlock_OnChangeOpenRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyTerminalBlockInstanceEventPayload::OnChangeOpenRequest(payload))
            }
            Self::OnChangeOpenSuccess => {
                let (_, payload) = MyTerminalBlock_OnChangeOpenSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyTerminalBlockInstanceEventPayload::OnChangeOpenSuccess(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyTerminalBlockInstanceEventPayload::RemoveContainerDropComponent),
        }
    }
}

/// Parse an instance event payload for MyTerminalBlock from raw event hash and bytes.
pub fn parse_my_terminal_block_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyTerminalBlockInstanceEventPayload, deku::DekuError> {
    match MyTerminalBlockInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyTerminalBlockInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyTerminalBlock instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyTerminalBlockInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyTerminalBlock_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyTerminalBlock_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest event.
    fn visit_on_change_open_request(&mut self, payload: &MyTerminalBlock_OnChangeOpenRequestPayload) {}
    /// Called when visiting OnChangeOpenSuccess event.
    fn visit_on_change_open_success(&mut self, payload: &MyTerminalBlock_OnChangeOpenSuccessPayload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyTerminalBlockInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyTerminalBlockInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest(payload) => visitor.visit_on_change_open_request(payload),
            Self::OnChangeOpenSuccess(payload) => visitor.visit_on_change_open_success(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyTerminalBlockInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyTerminalBlockInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyTerminalBlockInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest(_) => Some(MyTerminalBlockInstanceEvent::OnChangeOpenRequest),
            Self::OnChangeOpenSuccess(_) => Some(MyTerminalBlockInstanceEvent::OnChangeOpenSuccess),
            Self::RemoveContainerDropComponent => Some(MyTerminalBlockInstanceEvent::RemoveContainerDropComponent),
            Self::Unknown { .. } => None,
        }
    }
}
