//! Instance events for Sandbox.Game.Entities.Cube.MyWarhead.
//!
//! Auto-generated by codegen. Do not edit manually.

#![allow(unused_imports)]

use deku::prelude::*;
use space_engineers_compat::{BitAligned, BitBool, Nullable, VarMap, VarVec, VarBytes, VarString};
use space_engineers_compat::math::Vector3F;
use space_engineers_sys::math::Vector3D;

/// Payload for MyWarhead::SetCustomNameEvent instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_SetCustomNameEventPayload {
    pub name: VarString,
}

/// Payload for MyWarhead::OnCustomDataChanged instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_OnCustomDataChangedPayload {
    pub data: VarString,
}

/// Payload for MyWarhead::OnChangeOpenRequest instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_OnChangeOpenRequestPayload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyWarhead::OnChangeOpenSuccess instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_OnChangeOpenSuccessPayload {
    pub is_open: BitBool,
    pub editable: BitBool,
    pub user: BitAligned<u64>,
}

/// Payload for MyWarhead::SetCountdown instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_SetCountdownPayload {
    pub countdown_state: BitBool,
}

/// Payload for MyWarhead::SetCountdownClient instance event.
#[derive(Debug, Clone, PartialEq, DekuRead, DekuWrite)]
pub struct MyWarhead_SetCountdownClientPayload {
    pub countdown_state: BitBool,
}

/// Stable instance event identities for Sandbox.Game.Entities.Cube.MyWarhead.
///
/// Use `Version` to convert to/from version-specific event IDs.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum MyWarheadInstanceEvent {
    /// Hash: -1220660812
    SetCustomNameEvent,
    /// Hash: 2120665136
    OnCustomDataChanged,
    /// Hash: -76257694
    OnChangeOpenRequest,
    /// Hash: 261877592
    OnChangeOpenSuccess,
    /// Hash: 271720064
    RemoveContainerDropComponent,
    /// Hash: 1000001140
    DetonateRequest,
    /// Hash: -1238083730
    SetCountdown,
    /// Hash: 88006198
    SetCountdownClient,
}

impl MyWarheadInstanceEvent {
    /// Get the stable hash of this instance event.
    pub const fn event_hash(&self) -> i32 {
        match self {
            Self::SetCustomNameEvent => -1220660812,
            Self::OnCustomDataChanged => 2120665136,
            Self::OnChangeOpenRequest => -76257694,
            Self::OnChangeOpenSuccess => 261877592,
            Self::RemoveContainerDropComponent => 271720064,
            Self::DetonateRequest => 1000001140,
            Self::SetCountdown => -1238083730,
            Self::SetCountdownClient => 88006198,
        }
    }

    /// Look up from event hash. Returns None for unknown events.
    pub fn from_hash(hash: i32) -> Option<Self> {
        match hash {
            -1220660812 => Some(Self::SetCustomNameEvent),
            2120665136 => Some(Self::OnCustomDataChanged),
            -76257694 => Some(Self::OnChangeOpenRequest),
            261877592 => Some(Self::OnChangeOpenSuccess),
            271720064 => Some(Self::RemoveContainerDropComponent),
            1000001140 => Some(Self::DetonateRequest),
            -1238083730 => Some(Self::SetCountdown),
            88006198 => Some(Self::SetCountdownClient),
            _ => None,
        }
    }
}

/// Parsed instance event payload for Sandbox.Game.Entities.Cube.MyWarhead.
///
/// Use `MyWarheadInstanceEvent::parse_payload()` to parse raw bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum MyWarheadInstanceEventPayload {
    /// SetCustomNameEvent event payload
    SetCustomNameEvent(MyWarhead_SetCustomNameEventPayload),
    /// OnCustomDataChanged event payload
    OnCustomDataChanged(MyWarhead_OnCustomDataChangedPayload),
    /// OnChangeOpenRequest event payload
    OnChangeOpenRequest(MyWarhead_OnChangeOpenRequestPayload),
    /// OnChangeOpenSuccess event payload
    OnChangeOpenSuccess(MyWarhead_OnChangeOpenSuccessPayload),
    /// RemoveContainerDropComponent event (no payload)
    RemoveContainerDropComponent,
    /// DetonateRequest event (no payload)
    DetonateRequest,
    /// SetCountdown event payload
    SetCountdown(MyWarhead_SetCountdownPayload),
    /// SetCountdownClient event payload
    SetCountdownClient(MyWarhead_SetCountdownClientPayload),
    /// Unknown event (raw bytes preserved)
    Unknown { event_hash: i32, payload: Vec<u8> },
}

#[allow(unused_variables)]
impl MyWarheadInstanceEvent {
    /// Parse the payload bytes for this instance event type.
    ///
    /// # Errors
    ///
    /// Returns `Err` if the payload bytes don't match the expected format.
    pub fn parse_payload(&self, bytes: &[u8]) -> Result<MyWarheadInstanceEventPayload, deku::DekuError> {
        match self {
            Self::SetCustomNameEvent => {
                let (_, payload) = MyWarhead_SetCustomNameEventPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::SetCustomNameEvent(payload))
            }
            Self::OnCustomDataChanged => {
                let (_, payload) = MyWarhead_OnCustomDataChangedPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::OnCustomDataChanged(payload))
            }
            Self::OnChangeOpenRequest => {
                let (_, payload) = MyWarhead_OnChangeOpenRequestPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::OnChangeOpenRequest(payload))
            }
            Self::OnChangeOpenSuccess => {
                let (_, payload) = MyWarhead_OnChangeOpenSuccessPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::OnChangeOpenSuccess(payload))
            }
            Self::RemoveContainerDropComponent => Ok(MyWarheadInstanceEventPayload::RemoveContainerDropComponent),
            Self::DetonateRequest => Ok(MyWarheadInstanceEventPayload::DetonateRequest),
            Self::SetCountdown => {
                let (_, payload) = MyWarhead_SetCountdownPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::SetCountdown(payload))
            }
            Self::SetCountdownClient => {
                let (_, payload) = MyWarhead_SetCountdownClientPayload::from_bytes((bytes, 0))?;
                Ok(MyWarheadInstanceEventPayload::SetCountdownClient(payload))
            }
        }
    }
}

/// Parse an instance event payload for MyWarhead from raw event hash and bytes.
pub fn parse_my_warhead_instance_event(event_hash: i32, payload_bytes: &[u8]) -> Result<MyWarheadInstanceEventPayload, deku::DekuError> {
    match MyWarheadInstanceEvent::from_hash(event_hash) {
        Some(event_type) => event_type.parse_payload(payload_bytes),
        None => Ok(MyWarheadInstanceEventPayload::Unknown {
            event_hash,
            payload: payload_bytes.to_vec(),
        }),
    }
}

/// Visitor trait for MyWarhead instance events.
///
/// Implement only the methods you care about - all have default empty implementations.
#[allow(unused_variables)]
pub trait MyWarheadInstanceEventVisitor {
    /// Called when visiting SetCustomNameEvent event.
    fn visit_set_custom_name_event(&mut self, payload: &MyWarhead_SetCustomNameEventPayload) {}
    /// Called when visiting OnCustomDataChanged event.
    fn visit_on_custom_data_changed(&mut self, payload: &MyWarhead_OnCustomDataChangedPayload) {}
    /// Called when visiting OnChangeOpenRequest event.
    fn visit_on_change_open_request(&mut self, payload: &MyWarhead_OnChangeOpenRequestPayload) {}
    /// Called when visiting OnChangeOpenSuccess event.
    fn visit_on_change_open_success(&mut self, payload: &MyWarhead_OnChangeOpenSuccessPayload) {}
    /// Called when visiting RemoveContainerDropComponent event (no payload).
    fn visit_remove_container_drop_component(&mut self) {}
    /// Called when visiting DetonateRequest event (no payload).
    fn visit_detonate_request(&mut self) {}
    /// Called when visiting SetCountdown event.
    fn visit_set_countdown(&mut self, payload: &MyWarhead_SetCountdownPayload) {}
    /// Called when visiting SetCountdownClient event.
    fn visit_set_countdown_client(&mut self, payload: &MyWarhead_SetCountdownClientPayload) {}

    /// Called when visiting an unknown event.
    fn visit_unknown(&mut self, event_hash: i32, payload: &[u8]) {}
}

impl MyWarheadInstanceEventPayload {
    /// Accept a visitor, dispatching to the appropriate visit method.
    pub fn accept<V: MyWarheadInstanceEventVisitor>(&self, visitor: &mut V) {
        match self {
            Self::SetCustomNameEvent(payload) => visitor.visit_set_custom_name_event(payload),
            Self::OnCustomDataChanged(payload) => visitor.visit_on_custom_data_changed(payload),
            Self::OnChangeOpenRequest(payload) => visitor.visit_on_change_open_request(payload),
            Self::OnChangeOpenSuccess(payload) => visitor.visit_on_change_open_success(payload),
            Self::RemoveContainerDropComponent => visitor.visit_remove_container_drop_component(),
            Self::DetonateRequest => visitor.visit_detonate_request(),
            Self::SetCountdown(payload) => visitor.visit_set_countdown(payload),
            Self::SetCountdownClient(payload) => visitor.visit_set_countdown_client(payload),
            Self::Unknown { event_hash, payload } => visitor.visit_unknown(*event_hash, payload),
        }
    }

    /// Get the instance event type for this payload.
    pub fn event_type(&self) -> Option<MyWarheadInstanceEvent> {
        match self {
            Self::SetCustomNameEvent(_) => Some(MyWarheadInstanceEvent::SetCustomNameEvent),
            Self::OnCustomDataChanged(_) => Some(MyWarheadInstanceEvent::OnCustomDataChanged),
            Self::OnChangeOpenRequest(_) => Some(MyWarheadInstanceEvent::OnChangeOpenRequest),
            Self::OnChangeOpenSuccess(_) => Some(MyWarheadInstanceEvent::OnChangeOpenSuccess),
            Self::RemoveContainerDropComponent => Some(MyWarheadInstanceEvent::RemoveContainerDropComponent),
            Self::DetonateRequest => Some(MyWarheadInstanceEvent::DetonateRequest),
            Self::SetCountdown(_) => Some(MyWarheadInstanceEvent::SetCountdown),
            Self::SetCountdownClient(_) => Some(MyWarheadInstanceEvent::SetCountdownClient),
            Self::Unknown { .. } => None,
        }
    }
}
